# Installed-build acceptance for Snapmaker Studio.
#
# Installs the built NSIS installer into an isolated directory, launches the
# installed application with its WebView2 opened for remote debugging, drives the
# real UI over CDP, then uninstalls and proves the machine is clean.
#
# Why this exists: every capability check before this ran against the dev server.
# That proves the feature works; it does not prove the installer ships it. This
# runs the shipped exe and the frozen sidecar.
#
# SAFETY, and these are not negotiable:
#  * Every process this script starts is tracked by PID and only those are ever
#    stopped. A Snapmaker Orca or other user process is never touched.
#  * The app runs with an isolated WebView2 profile and an isolated engine data
#    directory, so the maintainer's own library, recent files and settings are
#    neither read nor modified — which also keeps private model names out of the
#    screenshots this produces.
#  * If another Snapmaker Studio is already installed, its uninstall registry key
#    is exported first and restored afterwards.
#  * Nothing is installed to a shared location and nothing needs administrator.
#
# Usage:
#   pwsh -File tools/acceptance/run.ps1 [-Installer <path>] [-KeepInstall]

[CmdletBinding()]
param(
    [string]$Installer,
    [string]$WorkDir = (Join-Path $env:TEMP "snapstudio-acceptance"),
    [int]$DebugPort = 9333,
    [switch]$KeepInstall,
    # A previous installer. When given, it is installed first and its settings and
    # library are checked for survival across the upgrade - the path every existing
    # user actually takes to a new release.
    [string]$UpgradeFrom
)

$ErrorActionPreference = "Stop"
$repo = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$started = @()          # every PID this script created
$checks = @()

function Add-Check($name, $ok, $detail = "") {
    $script:checks += [pscustomobject]@{ name = $name; ok = [bool]$ok; detail = $detail }
    $tag = if ($ok) { "PASS" } else { "FAIL" }
    Write-Host ("{0}  {1}{2}" -f $tag, $name, $(if ($detail) { "  — $detail" } else { "" }))
}

function Resolve-Installer {
    if ($Installer) { return (Resolve-Path $Installer).Path }
    $bundle = Join-Path $repo "desktop\src-tauri\target\release\bundle\nsis"
    $newest = Get-ChildItem $bundle -Filter "*_x64-setup.exe" -ErrorAction SilentlyContinue |
        Sort-Object LastWriteTime -Descending | Select-Object -First 1
    if (-not $newest) { throw "No installer found in $bundle — run `npm run release:windows` first." }
    return $newest.FullName
}

function Stop-Tracked {
    foreach ($procId in $script:started) {
        Stop-Process -Id $procId -Force -ErrorAction SilentlyContinue
    }
    Start-Sleep -Seconds 3
}

# --- prepare -----------------------------------------------------------------

$installer = Resolve-Installer
Write-Host "Installer: $installer"

$installDir = Join-Path $WorkDir "app"
$profileDir = Join-Path $WorkDir "webview-profile"
$dataDir    = Join-Path $WorkDir "engine-data"
$outDir     = Join-Path $WorkDir "evidence"
$sample     = Join-Path $repo "examples\demo_u1_showcase.3mf"
$sampleWork = Join-Path $WorkDir "demo_u1_showcase.3mf"

foreach ($d in @($WorkDir, $outDir)) { New-Item -ItemType Directory -Force -Path $d | Out-Null }
# Start from nothing. A WebView2 profile or engine data directory left by an
# earlier run carries recent-file names into the screenshots this produces, which
# is both a privacy problem and a reproducibility one.
foreach ($stale in @($installDir, $profileDir, $dataDir)) {
    if (Test-Path $stale) { Remove-Item $stale -Recurse -Force -ErrorAction SilentlyContinue }
}

# Work on a copy so the repository fixture is provably never written to.
Copy-Item $sample $sampleWork -Force
$sampleHashBefore = (Get-FileHash $sampleWork -Algorithm SHA256).Hash

# A sliced job. Studio does not slice, so the one input the installed build
# cannot make for itself is written here — shaped exactly like real Snapmaker
# Orca output from a physical U1.
$gcodeWork = Join-Path $WorkDir "acceptance_job.gcode"
@'
; HEADER_BLOCK_START
; generated by Snapmaker Orca 2.3.4 on 2026-08-23 at 10:00:00
; total layer number: 12
; max_z_height: 2.40
; HEADER_BLOCK_END
; EXECUTABLE_BLOCK_START
PRINT_START
M140 S60
M104 T1 S220
SET_PRINT_STATS_INFO TOTAL_LAYER=12 CURRENT_LAYER=0
T1
;LAYER_CHANGE
;Z:0.2
G1 X10 Y10 Z0.2 F1200
;LAYER_CHANGE
;Z:0.4
G1 X20 Y20 E1.0
;LAYER_CHANGE
;Z:0.6
G1 X30 Y30 E1.0
PRINT_END
; EXECUTABLE_BLOCK_END

; filament used [mm] = 0.00, 120.00, 0.00, 0.00
; filament used [g] = 0.00, 0.36, 0.00, 0.00
; total filament used [g] = 0.36
; total layers count = 12
; estimated printing time (normal mode) = 4m 10s

; CONFIG_BLOCK_START
; filament_type = PLA;PLA;PLA;PLA
; layer_height = 0.2
; nozzle_diameter = 0.4,0.4,0.4,0.4
; printable_area = 0.5x1,270.5x1,270.5x271,0.5x271
; printer_model = Snapmaker U1
; CONFIG_BLOCK_END
'@ | Set-Content $gcodeWork -Encoding utf8
$gcodeHashBefore = (Get-FileHash $gcodeWork -Algorithm SHA256).Hash

# An existing install of the same app shares the uninstall registry key. Save it.
$existing = Get-ChildItem 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Uninstall' |
    Where-Object { (Get-ItemProperty $_.PSPath -ErrorAction SilentlyContinue).DisplayName -like '*Snapmaker Studio*' }
$backupReg = Join-Path $WorkDir "backup-uninstall.reg"
if ($existing) {
    reg export $existing.Name $backupReg /y | Out-Null
    Write-Host "Existing install detected; its registry entry was exported to $backupReg"
}

try {
    # --- upgrade path --------------------------------------------------------
    if ($UpgradeFrom) {
        $old = (Resolve-Path $UpgradeFrom).Path
        Write-Host "Upgrading from $old"
        $prev = Start-Process -FilePath $old -ArgumentList '/S', '/NCRC', "/D=$installDir" -PassThru -Wait
        Add-Check "Previous version installs" ($prev.ExitCode -eq 0) "exit code $($prev.ExitCode)"

        # Give the old build a run so it creates the state a real user would have.
        $env:SNAPSTUDIO_DATA_DIR = $dataDir
        $warm = Start-Process -FilePath (Join-Path $installDir "snapmaker-studio-desktop.exe") -PassThru
        Start-Sleep -Seconds 12
        Stop-Process -Id $warm.Id -Force -ErrorAction SilentlyContinue
        Start-Sleep -Seconds 4
        Remove-Item Env:SNAPSTUDIO_DATA_DIR -ErrorAction SilentlyContinue

        Add-Check "Previous version left state to migrate" (Test-Path $dataDir) $dataDir
        $script:stateBefore = @(Get-ChildItem $dataDir -Recurse -File -ErrorAction SilentlyContinue).Count
    }

    # --- install -------------------------------------------------------------
    $proc = Start-Process -FilePath $installer -ArgumentList '/S', '/NCRC', "/D=$installDir" -PassThru -Wait
    Add-Check "Scripted install completes" ($proc.ExitCode -eq 0) "exit code $($proc.ExitCode)"

    if ($UpgradeFrom) {
        $stateAfter = @(Get-ChildItem $dataDir -Recurse -File -ErrorAction SilentlyContinue).Count
        Add-Check "Upgrade keeps the user's data" ($stateAfter -ge $script:stateBefore) `
            "$script:stateBefore file(s) before, $stateAfter after"
        $installs = @(Get-ChildItem 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Uninstall' |
            Where-Object { (Get-ItemProperty $_.PSPath -ErrorAction SilentlyContinue).DisplayName -like '*Snapmaker Studio*' })
        Add-Check "Upgrade does not leave two installations" ($installs.Count -le 1) `
            "$($installs.Count) registration(s)"
    }

    $appExe = Join-Path $installDir "snapmaker-studio-desktop.exe"
    $sidecarExe = Join-Path $installDir "snapstudio-api.exe"
    Add-Check "Application installed" (Test-Path $appExe)
    Add-Check "Frozen engine sidecar installed" (Test-Path $sidecarExe) `
        ("{0:N1} MB" -f ((Get-Item $sidecarExe -ErrorAction SilentlyContinue).Length / 1MB))
    Add-Check "Uninstaller installed" (Test-Path (Join-Path $installDir "uninstall.exe"))

    # --- launch --------------------------------------------------------------
    $env:WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS = "--remote-debugging-port=$DebugPort --remote-allow-origins=*"
    $env:WEBVIEW2_USER_DATA_FOLDER = $profileDir
    $env:SNAPSTUDIO_DATA_DIR = $dataDir

    # Hand the project to the app the same way a file association would.
    $app = Start-Process -FilePath $appExe -ArgumentList $sampleWork -PassThru
    $script:started += $app.Id
    Start-Sleep -Seconds 10

    $alive = $null -ne (Get-Process -Id $app.Id -ErrorAction SilentlyContinue)
    Add-Check "Application launches" $alive "pid $($app.Id)"
    Add-Check "Window title" (( Get-Process -Id $app.Id).MainWindowTitle -eq "Snapmaker Studio")

    $sidecars = @(Get-CimInstance Win32_Process -Filter "Name='snapstudio-api.exe'" |
        Where-Object { $_.ExecutablePath -like "$installDir*" })
    Add-Check "Sidecar boots from the install directory" ($sidecars.Count -ge 1) `
        "$($sidecars.Count) process(es)"

    $cdp = "http://127.0.0.1:$DebugPort"
    $node = Join-Path $PSScriptRoot "checks.mjs"

    function Invoke-Phase($phase, $arg = "", $arg2 = "") {
        $out = & node $node $phase $cdp $outDir $arg $arg2 2>&1
        $out | ForEach-Object { Write-Host "    $_" }
        return $LASTEXITCODE
    }

    Add-Check "CDP reachable on the installed webview" `
        ((Invoke-WebRequest "$cdp/json/version" -UseBasicParsing -TimeoutSec 10).StatusCode -eq 200)

    $code = Invoke-Phase "startup"
    Add-Check "Startup checks" ($code -eq 0)

    $code = Invoke-Phase "routes" $sampleWork $gcodeWork
    Add-Check "Engine routes answer from the installed sidecar" ($code -eq 0)

    # --- the project the app was launched with --------------------------------
    #
    # The native picker is deliberately not used here. It is a Win32 common
    # dialog with no DOM, and on this stack invoking it without real user input
    # blocks without ever creating a window — verified by enumerating every
    # top-level window while the call was pending. No UI-automation client can
    # reach a window that does not exist, so the app instead accepts a model on
    # its command line, which a file association needs anyway.
    $code = Invoke-Phase "launch-file"
    Add-Check "Model passed on the command line is open" ($code -eq 0)

    Invoke-Phase "goto-compatibility" | Out-Null
    Start-Sleep -Seconds 4

    $code = Invoke-Phase "ui"
    Add-Check "Project opens and its findings render" ($code -eq 0)

    # --- prepare a copy -------------------------------------------------------
    Invoke-Phase "prepare" | Out-Null
    Start-Sleep -Seconds 3
    $code = Invoke-Phase "prepared"
    Add-Check "Prepare, fidelity, ledger and best-tool render" ($code -eq 0)

    $code = Invoke-Phase "colours"
    Add-Check "Colour plan renders on its own page" ($code -eq 0)

    # --- the post-slice half of the workflow ---------------------------------
    $code = Invoke-Phase "post-slice" $sampleWork $gcodeWork
    Add-Check "Post-Slice Doctor reads a sliced job in the installed app" ($code -eq 0)

    $gcodeHashAfter = (Get-FileHash $gcodeWork -Algorithm SHA256).Hash
    Add-Check "Sliced job is byte-identical afterwards" ($gcodeHashBefore -eq $gcodeHashAfter)

    $sampleHashAfter = (Get-FileHash $sampleWork -Algorithm SHA256).Hash
    Add-Check "Original file is byte-identical afterwards" `
        ($sampleHashBefore -eq $sampleHashAfter)

    # --- close and prove no orphan -------------------------------------------
    Stop-Tracked
    $script:started = @()
    $orphans = @(Get-CimInstance Win32_Process -Filter "Name='snapstudio-api.exe'" |
        Where-Object { $_.ExecutablePath -like "$installDir*" })
    Add-Check "No orphan sidecar after close" ($orphans.Count -eq 0) `
        "$($orphans.Count) left running"

    # --- reopen ---------------------------------------------------------------
    $again = Start-Process -FilePath $appExe -PassThru
    $script:started += $again.Id
    Start-Sleep -Seconds 8
    Add-Check "Reopens cleanly" ($null -ne (Get-Process -Id $again.Id -ErrorAction SilentlyContinue))
    Stop-Tracked
    $script:started = @()
}
finally {
    Stop-Tracked
    Remove-Item Env:WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS -ErrorAction SilentlyContinue
    Remove-Item Env:WEBVIEW2_USER_DATA_FOLDER -ErrorAction SilentlyContinue
    Remove-Item Env:SNAPSTUDIO_DATA_DIR -ErrorAction SilentlyContinue
}

# --- uninstall ---------------------------------------------------------------
if (-not $KeepInstall) {
    $uninstaller = Join-Path $installDir "uninstall.exe"
    if (Test-Path $uninstaller) {
        $u = Start-Process -FilePath $uninstaller -ArgumentList '/S' -PassThru -Wait
        Start-Sleep -Seconds 3
        Add-Check "Uninstall completes" ($u.ExitCode -eq 0) "exit code $($u.ExitCode)"
        $leftovers = @(Get-ChildItem $installDir -Recurse -File -ErrorAction SilentlyContinue)
        Add-Check "Install directory removed" ($leftovers.Count -eq 0) "$($leftovers.Count) file(s) left"
        $stillRunning = @(Get-CimInstance Win32_Process -Filter "Name='snapstudio-api.exe'" |
            Where-Object { $_.ExecutablePath -like "$installDir*" })
        Add-Check "No sidecar survives uninstall" ($stillRunning.Count -eq 0)
    }
    # Put the maintainer's own uninstall entry back exactly as it was.
    if ($existing -and (Test-Path $backupReg)) {
        reg import $backupReg 2>&1 | Out-Null
        $restored = Get-ChildItem 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Uninstall' |
            Where-Object { (Get-ItemProperty $_.PSPath -ErrorAction SilentlyContinue).DisplayName -like '*Snapmaker Studio*' }
        Add-Check "Pre-existing install registration restored" ($null -ne $restored)
    }
}

# --- report -------------------------------------------------------------------
$passed = @($checks | Where-Object ok).Count
$total = $checks.Count
$report = [pscustomobject]@{
    schema_version = "acceptance/1"
    installer      = $installer
    checks         = $checks
    passed         = $passed
    total          = $total
    evidence       = $outDir
}
$reportPath = Join-Path $outDir "acceptance.json"

# The repository's own rules forbid local paths and usernames in tracked files,
# and this report is meant to be committed as release evidence. Replace them
# here rather than remembering to do it by hand later.
$json = $report | ConvertTo-Json -Depth 5
foreach ($pair in @(
    @{ from = $repo;      to = "<repo>" },
    @{ from = $WorkDir;   to = "<workdir>" },
    @{ from = $env:TEMP;  to = "<temp>" },
    @{ from = $env:USERNAME; to = "<user>" })) {
    if ($pair.from) {
        $json = $json.Replace($pair.from.Replace('\', '\\'), $pair.to)
        $json = $json.Replace($pair.from, $pair.to)
    }
}
$json | Set-Content $reportPath -Encoding utf8

Write-Host ""
Write-Host "$passed/$total checks passed"
Write-Host "Evidence and screenshots: $outDir"
if ($passed -ne $total) { exit 1 }
