"""Canonical project representation (P4) — the multi-ecosystem seam.

Proves a Prusa 3MF (INI config, ;-separated multi-material) reads into the SAME
source-neutral shape as a Bambu/STL design, and that the honesty note about
unpreserved Prusa multi-material is present. No conversion is performed."""
import struct
import zipfile

from snapstudio_core.canonical import to_canonical, _parse_prusa_ini

_MODEL = b"""<?xml version="1.0" encoding="UTF-8"?>
<model unit="millimeter" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">
 <resources><object id="1" type="model"><mesh>
  <vertices>
   <vertex x="0" y="0" z="0"/><vertex x="10" y="0" z="0"/>
   <vertex x="0" y="20" z="0"/><vertex x="0" y="0" z="30"/>
  </vertices>
  <triangles>
   <triangle v1="0" v2="1" v3="2"/><triangle v1="0" v2="1" v3="3"/>
  </triangles>
 </mesh></object></resources>
 <build><item objectid="1"/></build>
</model>"""

_PRUSA_INI = (b"# generated by PrusaSlicer\n"
              b"printer_model = XL\n"
              b"filament_colour = #FF8000;#0000FF\n"
              b"filament_type = PLA;PETG\n")


def _prusa_3mf(tmp_path):
    p = tmp_path / "liberty_eagle.3mf"
    with zipfile.ZipFile(p, "w") as z:
        z.writestr("[Content_Types].xml",
                   '<?xml version="1.0"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"/>')
        z.writestr("3D/3dmodel.model", _MODEL)
        z.writestr("Metadata/Slic3r_PE.config", _PRUSA_INI)
    return p


def _bin_tetra():
    head = b"\x00" * 80 + struct.pack("<I", 2)
    for v1, v2, v3 in [((0, 0, 0), (10, 0, 0), (0, 10, 0)),
                       ((0, 0, 0), (0, 10, 0), (0, 0, 10))]:
        head += struct.pack("<12fH", 0, 0, 0, *v1, *v2, *v3, 0)
    return head


def test_parse_prusa_ini_splits_multimaterial():
    cfg = _parse_prusa_ini(_PRUSA_INI)
    assert cfg["printer_model"] == "XL"
    assert cfg["filament_colour"] == ["#FF8000", "#0000FF"]
    assert cfg["filament_type"] == ["PLA", "PETG"]


def test_prusa_reads_into_canonical_shape(tmp_path):
    canon = to_canonical(str(_prusa_3mf(tmp_path))).to_dict()
    assert canon["schema_version"] == "canonical/1"
    assert canon["source_family"] == "prusa"
    assert canon["source_printer_model"] == "XL"
    assert [m["color"] for m in canon["materials"]] == ["#FF8000", "#0000FF"]
    assert [m["type"] for m in canon["materials"]] == ["PLA", "PETG"]
    assert canon["color_count"] == 2
    assert canon["triangles"] == 2
    # honesty: Prusa multi-material is read but not yet preserved on conversion
    assert any("multi-material" in n.lower() for n in canon["notes"])


def test_stl_reads_into_canonical_shape(tmp_path):
    stl = tmp_path / "cube.stl"; stl.write_bytes(_bin_tetra())
    canon = to_canonical(str(stl)).to_dict()
    assert canon["source_family"] == "stl"
    assert canon["triangles"] == 2
    assert canon["complexity"] == "low"
    assert canon["materials"] == []  # an STL carries no material intent
    assert canon["notes"] == []
