"""What survives when a PrusaSlicer project is prepared for a U1 — measured.

Studio has been able to *read* a Prusa project since v0.5.0. Preparing one was a
different story: the copy kept the geometry exactly and threw the print away, so a
project sliced at 0.15 mm with four walls and 45% infill arrived as the U1 starter
profile at 0.2 mm with two walls and 15%. The same shape, a different print, and
nothing on screen said so.

The rule for what crosses over is meaning, not name. Layer height means the same
thing in both slicers. A PrusaSlicer filament profile's 225 °C does not: it is
about a Prusa hotend, and copying it into a U1 project would be handing one
machine another machine's numbers while looking like fidelity.

So these tests are half about what is carried and half about what is refused, and
the refusals are the more important half.
"""
from __future__ import annotations

import zipfile

import pytest

from snapstudio_core import config_io, prusa
from snapstudio_core.container import ThreeMF
from snapstudio_core.convert import convert_to_u1

SETTINGS = "Metadata/project_settings.config"

CONFIG = """\
; generated by PrusaSlicer 2.8.0 on 2026-08-23 at 10:00:00 UTC

; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; brim_width = 4
; fill_density = 45%
; filament_colour = #FF8000;#1F8CE0
; filament_type = PETG;PLA
; first_layer_height = 0.25
; layer_height = 0.15
; perimeters = 4
; printer_model = MK4IS
; printer_variant = 0.4
; support_material = 1
; support_material_style = snug
; temperature = 245,225
"""


def carried(config=CONFIG):
    return prusa.to_u1_settings(prusa.settings(config))


def test_the_print_itself_is_carried_across():
    settings = carried()["settings"]
    assert settings["layer_height"] == "0.15"
    assert settings["initial_layer_print_height"] == "0.25"
    assert settings["sparse_infill_density"] == "45%"
    assert settings["wall_loops"] == "4"
    assert settings["enable_support"] == "1"


def test_the_materials_the_project_was_set_up_for_are_carried():
    settings = carried()["settings"]
    assert settings["filament_type"] == ["PETG", "PLA"]
    assert settings["filament_colour"] == ["#FF8000", "#1F8CE0"]


def test_temperatures_are_not_carried_because_they_belong_to_another_machine():
    settings = carried()["settings"]
    assert "nozzle_temperature" not in settings
    assert "nozzle_temperature_initial_layer" not in settings
    assert "hot_plate_temp" not in settings


def test_support_style_is_not_carried_only_whether_support_is_on():
    settings = carried()["settings"]
    assert settings["enable_support"] == "1"
    assert "support_style" not in settings
    assert "support_type" not in settings


def test_no_brim_is_carried_as_an_intention_not_just_a_width():
    """Zero width is PrusaSlicer's way of saying no brim, and Orca decides that
    with a different setting — so carrying the width alone would leave the copy
    adding a brim the project did not want."""
    settings = carried(CONFIG.replace("; brim_width = 4", "; brim_width = 0"))["settings"]
    assert settings["brim_width"] == "0"
    assert settings["brim_type"] == "no_brim"
    assert carried()["settings"]["brim_type"] == "auto_brim"


def test_every_carried_setting_says_where_it_came_from():
    for item in carried()["evidence"]:
        assert item["key"] and item["from"] and item["detail"]


def test_a_project_that_states_nothing_carries_nothing():
    assert carried("; generated by PrusaSlicer 2.8.0" + chr(10))["settings"] == {}


# --- end to end, through a real conversion -----------------------------------

@pytest.fixture
def prusa_project(tmp_path):
    """A minimal but genuine Prusa 3MF: geometry plus the two config parts."""
    source = tmp_path / "bracket.3mf"
    model = ('<?xml version="1.0" encoding="UTF-8"?>'
             '<model unit="millimeter" xml:lang="en-US" '
             'xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">'
             '<resources><object id="1" type="model"><mesh><vertices>'
             '<vertex x="0" y="0" z="0"/><vertex x="10" y="0" z="0"/>'
             '<vertex x="0" y="10" z="0"/><vertex x="0" y="0" z="10"/>'
             '</vertices><triangles>'
             '<triangle v1="0" v2="1" v3="2"/><triangle v1="0" v2="1" v3="3"/>'
             '<triangle v1="0" v2="2" v3="3"/><triangle v1="1" v2="2" v3="3"/>'
             '</triangles></mesh></object></resources>'
             '<build><item objectid="1"/></build></model>')
    rels = ('<?xml version="1.0" encoding="UTF-8"?>'
            '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
            '<Relationship Id="rel0" Target="/3D/3dmodel.model" '
            'Type="http://schemas.microsoft.com/3dmanufacturing/2013/01/3dmodel"/></Relationships>')
    types = ('<?xml version="1.0" encoding="UTF-8"?>'
             '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
             '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.'
             'relationships+xml"/><Default Extension="model" ContentType="application/vnd.'
             'ms-package.3dmanufacturing-3dmodel+xml"/></Types>')
    with zipfile.ZipFile(source, "w") as archive:
        archive.writestr("[Content_Types].xml", types)
        archive.writestr("_rels/.rels", rels)
        archive.writestr("3D/3dmodel.model", model)
        archive.writestr(prusa.SETTINGS_PART, CONFIG)
        archive.writestr(prusa.MODEL_CONFIG_PART,
                         '<?xml version="1.0" encoding="UTF-8"?><config>'
                         '<object id="1" instances_count="1">'
                         '<metadata type="object" key="name" value="bracket.stl"/>'
                         "</object></config>")
    return source


def test_a_prepared_copy_prints_the_way_the_project_did(tmp_path, prusa_project):
    result = convert_to_u1(str(prusa_project), str(tmp_path / "out"))
    settings = config_io.load_project_settings(
        ThreeMF.open(result.output_path).read_part(SETTINGS))

    assert settings["layer_height"] == "0.15"
    assert settings["wall_loops"] == "4"
    assert settings["sparse_infill_density"] == "45%"
    assert settings["enable_support"] == "1"
    assert settings["filament_type"][0] == "PETG"
    assert settings["filament_colour"][0] == "#FF8000"
    # The machine it will print on is still the U1, with the U1's temperatures.
    assert settings["printer_model"] == "Snapmaker U1"
    assert settings["nozzle_temperature"][0] == "220"


def test_the_prepared_copy_says_what_it_carried(tmp_path, prusa_project):
    result = convert_to_u1(str(prusa_project), str(tmp_path / "out"))
    mapped = result.settings_summary["mapped_to_u1"]
    keys = {item["key"] for item in mapped}
    assert {"layer_height", "wall_loops", "enable_support", "filament_type"} <= keys


def test_the_original_is_untouched(tmp_path, prusa_project):
    before = prusa_project.read_bytes()
    convert_to_u1(str(prusa_project), str(tmp_path / "out"))
    assert prusa_project.read_bytes() == before


def test_a_geometry_only_3mf_still_gets_the_starter_profile(tmp_path, prusa_project):
    """Nothing to carry is not a failure — it is the case Studio started from."""
    bare = tmp_path / "bare.3mf"
    with zipfile.ZipFile(prusa_project) as source, zipfile.ZipFile(bare, "w") as target:
        for name in source.namelist():
            if name != prusa.SETTINGS_PART:
                target.writestr(name, source.read(name))
    result = convert_to_u1(str(bare), str(tmp_path / "out2"))
    settings = config_io.load_project_settings(
        ThreeMF.open(result.output_path).read_part(SETTINGS))
    assert settings["layer_height"] == "0.2"          # the starter profile
    assert result.settings_summary.get("mapped_to_u1") in (None, [])
