"""Trying to get a private detail out of Studio through something shareable.

Studio is local-first, which protects the file but not the *report about* the
file. Three things leave the machine when a user chooses to share them: a support
bundle, a screenshot, and whatever they paste into an issue. Each new feature adds
something worth checking before it can end up in one of those — a watched folder
under a home directory, the address of a spool tracker, a spool's label, the
fingerprint of a model's object names.

The rule is not "scrub it on the way out". It is that the private form should
never be assembled in the first place, so the tests here look at what the engine
returns as well as what the bundle contains.
"""
from __future__ import annotations

import json

from snapstudio_core import diagnostics, gcode, provenance, send_state

MODEL = "grandmothers headstone rev4"

JOB = """\
; HEADER_BLOCK_START
; generated by Snapmaker Orca 2.3.5 on 2026-08-23 at 10:00:00
; total layer number: 6
; HEADER_BLOCK_END
PRINT_START
; printing object {model} id:0 copy 0
G1 X10 Y10 E1
PRINT_END
; filament used [g] = 4.00
; total filament used [g] = 4.00
; total layers count = 6
; estimated printing time (normal mode) = 41m 12s
; CONFIG_BLOCK_START
; filament_type = PLA
; filament_colour = #2D9E59
; nozzle_diameter = 0.4
; printer_model = Snapmaker U1
; CONFIG_BLOCK_END
"""


def job(tmp_path, name="secret model v4.gcode"):
    target = tmp_path / name
    target.write_text(JOB.format(model=MODEL), encoding="utf-8")
    return target


def test_a_support_bundle_carries_no_object_names_or_hashes(tmp_path):
    bundle = diagnostics.collect(gcode_path=str(job(tmp_path)))
    blob = json.dumps(bundle, default=str)
    for word in MODEL.split():
        assert word not in blob
    objects = bundle["sliced_job"]["facts"]["objects"]
    assert objects["count"] == 1
    assert "name_hashes" not in objects


def test_a_support_bundle_carries_no_file_names_or_paths(tmp_path):
    target = job(tmp_path)
    bundle = diagnostics.collect(gcode_path=str(target))
    blob = json.dumps(bundle, default=str)
    assert "secret model" not in blob
    assert str(tmp_path) not in blob


def test_the_send_fingerprint_does_not_carry_the_model_name(tmp_path):
    """It travels to the app and back with every send, so it holds a hash."""
    facts = gcode.read_facts(job(tmp_path))
    state = send_state.fingerprint(facts, {"reachable": True})
    blob = json.dumps(state)
    assert "secret model" not in blob
    for word in MODEL.split():
        assert word not in blob


def test_provenance_evidence_reads_as_english_without_naming_anything(tmp_path):
    facts = gcode.read_facts(job(tmp_path))
    traits = {"readable": True,
              "object_name_hashes": {"value": facts["objects"]["name_hashes"]}}
    result = provenance.compare(traits, facts, project_name="secret model v4.3mf",
                                gcode_name="secret model v4.gcode")
    blob = json.dumps(result)
    assert result["verdict"] == provenance.CONFIRMED
    assert "secret model" not in blob
    for word in MODEL.split():
        assert word not in blob


def test_a_spool_label_never_reaches_the_slot_state(monkeypatch):
    """Spoolman spools carry names people give them. The slot only needs the
    material, the colour and how much is left."""
    from snapstudio_core import material_providers as providers

    payload = [{"id": 7, "remaining_weight": 431.5,
                "filament": {"material": "PLA", "color_hex": "2D9E59",
                             "name": "Anna's wedding spool",
                             "vendor": {"name": "Snapmaker"}}}]
    monkeypatch.setattr(providers, "_get_json", lambda url, timeout=4.0: payload)
    state = providers.spoolman("http://spoolman.local:7912", slot_map={"0": 7})
    loaded = providers.as_loaded_filaments(providers.combine(state))
    assert "Anna" not in json.dumps(loaded)


def test_a_provider_address_is_not_echoed_into_the_material_state(monkeypatch):
    from snapstudio_core import material_providers as providers

    monkeypatch.setattr(providers, "_get_json", lambda url, timeout=4.0: [])
    state = providers.spoolman("http://192.168.1.44:7912")
    assert "192.168" not in json.dumps(state)


def test_a_watched_folder_path_is_redacted_out_of_anything_shared(tmp_path):
    """The watcher answers with real paths — the user chose the folder and needs to
    see it. What must not happen is that path surviving into a shared file."""
    scrubbed = diagnostics.redact({"folder": r"C:\Users\someone\Documents\Orca\exports"})
    assert scrubbed["folder"] == "<path>"


def test_redaction_keeps_hashes_because_they_are_not_secrets():
    kept = diagnostics.redact({"digest": "a" * 40})
    assert kept["digest"] == "a" * 40
