"""Telling one file from another when the filesystem cannot.

The send fingerprint's job is to notice that the file being uploaded is no longer
the file that was checked. Re-slicing to the same name is the ordinary case, and
the obvious identifiers do not always change: a re-slice can land on the same byte
count, and on a fast filesystem it can be written inside the same timestamp tick.
CI on Linux found exactly that, on a change this project had made deliberately to
prove the fingerprint worked.

So the file is fingerprinted by its contents as well — bounded windows at the
start, the middle and the end, which is where a slicer writes everything that
distinguishes one job from another. These tests are about the cases where size and
time are useless.
"""
from __future__ import annotations

import os

from snapstudio_api.service import _file_stat
from snapstudio_core import gcode, send_state

HEAD = """\
; HEADER_BLOCK_START
; generated by Snapmaker Orca 2.3.5 on 2026-08-24 at 10:00:00
; total layer number: 6
; HEADER_BLOCK_END
PRINT_START
"""

TAIL = """\
PRINT_END
; filament used [g] = 40.00
; total filament used [g] = 40.00
; total layers count = 6
; estimated printing time (normal mode) = 41m 12s
; CONFIG_BLOCK_START
; filament_type = PLA
; printer_model = Snapmaker U1
; CONFIG_BLOCK_END
"""


def job(path, body="G1 X10 Y10 E1\n", *, pad=0):
    path.write_text(HEAD + ("; " + "p" * 78 + "\n") * pad + body + TAIL, encoding="utf-8")
    return path


def fingerprint(path):
    return send_state.fingerprint(gcode.read_facts(path), {"reachable": True},
                                  file_stat=_file_stat(str(path)))


def same_timestamp(first, second):
    """Force both files to claim the same modification time, which is what a fast
    filesystem does on its own."""
    stamp = first.stat().st_mtime
    os.utime(second, (stamp, stamp))


def test_a_rewrite_of_the_same_length_is_noticed(tmp_path):
    """The case CI caught: same byte count, same timestamp tick."""
    target = job(tmp_path / "bracket.gcode", "G1 X10 Y10 E1\n")
    before = fingerprint(target)
    stamp = target.stat().st_mtime

    job(tmp_path / "bracket.gcode", "G1 X20 Y20 E2\n")          # identical length
    os.utime(target, (stamp, stamp))
    after = fingerprint(target)

    assert before["parts"]["job"]["size"] == after["parts"]["job"]["size"]
    assert before["parts"]["job"]["modified"] == after["parts"]["job"]["modified"]
    assert send_state.changes(before, after), "a different file passed as the same one"


def test_a_change_in_the_middle_of_a_large_file_is_noticed(tmp_path):
    """Head and tail alone would miss it, and a slicer's output is mostly middle."""
    filler = ("G1 X1 Y1 E1\n" * 20_000)
    target = tmp_path / "big.gcode"
    target.write_text(HEAD + filler + TAIL, encoding="utf-8")
    before = fingerprint(target)
    stamp = target.stat().st_mtime

    middle = filler[: len(filler) // 2] + "G1 X9 Y9 E9\n" + filler[len(filler) // 2 + 12:]
    target.write_text(HEAD + middle + TAIL, encoding="utf-8")
    os.utime(target, (stamp, stamp))
    after = fingerprint(target)

    assert before["parts"]["job"]["size"] == after["parts"]["job"]["size"]
    assert send_state.changes(before, after)


def test_the_same_file_read_twice_is_the_same_fingerprint(tmp_path):
    target = job(tmp_path / "bracket.gcode")
    assert not send_state.changes(fingerprint(target), fingerprint(target))


def test_two_different_files_of_the_same_size_do_not_share_a_fingerprint(tmp_path):
    first = job(tmp_path / "one.gcode", "G1 X10 Y10 E1\n")
    second = job(tmp_path / "two.gcode", "G1 X20 Y20 E2\n")
    same_timestamp(first, second)
    assert (_file_stat(str(first))["content"] != _file_stat(str(second))["content"])


def test_what_is_read_is_bounded(tmp_path, monkeypatch):
    """A send check must not read a 500 MB job to identify it."""
    target = tmp_path / "huge.gcode"
    target.write_text(HEAD + ("G1 X1 Y1 E1\n" * 400_000) + TAIL, encoding="utf-8")

    read_bytes = []
    real_open = type(target).open

    def counting_open(self, *args, **kwargs):
        handle = real_open(self, *args, **kwargs)
        if "b" in (args[0] if args else kwargs.get("mode", "")):
            real_read = handle.read

            def read(size=-1):
                data = real_read(size)
                read_bytes.append(len(data))
                return data

            handle.read = read
        return handle

    monkeypatch.setattr(type(target), "open", counting_open)
    _file_stat(str(target))
    assert sum(read_bytes) <= 3 * 64 * 1024, f"read {sum(read_bytes)} bytes to identify a file"


def test_an_unreadable_file_still_produces_what_it_can(tmp_path, monkeypatch):
    target = job(tmp_path / "locked.gcode")

    def refuse(self, *args, **kwargs):
        raise PermissionError(13, "in use")

    monkeypatch.setattr(type(target), "open", refuse)
    stat = _file_stat(str(target))
    assert stat["size_bytes"] > 0 and "content" not in stat


def test_a_missing_file_is_not_an_identity(tmp_path):
    assert _file_stat(str(tmp_path / "gone.gcode")) == {}
