"""The PrusaSlicer reader.

Until v0.5.0 Studio could recognise a Prusa project and read its printer model,
and nothing else — so a perfectly ordinary Prusa file produced "0 filaments, no
layer height" and every downstream check had nothing to work with. These tests
are written against the shape of a real PrusaSlicer 2.8 project, and the
real-world suite runs the same code against the genuine article.
"""
from __future__ import annotations

import pytest

from snapstudio_core import prusa

CONFIG = """\
; generated by PrusaSlicer 2.8.0-alpha3 on 2024-04-17 at 14:21:35 UTC

; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; brim_width = 0
; filament_colour = #FF8000;#1F8CE0
; filament_diameter = 1.75,1.75
; filament_settings_id = "Prusament PLA @PGIS";"Prusament PETG"
; filament_type = PLA;PETG
; filament_vendor = Prusa Polymers;Prusa Polymers
; first_layer_height = 0.2
; layer_height = 0.15
; print_settings_id = 0.15mm STRUCTURAL @MK4IS 0.4
; printer_model = MK4IS
; printer_settings_id = Original Prusa MK4 Input Shaper 0.4 nozzle
; support_material = 1
; support_material_style = snug
; temperature = 225,240
"""

MODEL_CONFIG = """\
<?xml version="1.0" encoding="UTF-8"?>
<config>
 <object id="1" instances_count="1">
  <metadata type="object" key="name" value="3DBenchy.stl"/>
  <metadata type="object" key="extruder" value="2"/>
  <metadata type="object" key="layer_height_profile" value="0 0.2 12 0.1"/>
  <volume firstid="0" lastid="225153">
   <metadata type="volume" key="name" value="3DBenchy.stl"/>
   <metadata type="volume" key="source_offset_z" value="24"/>
  </volume>
 </object>
 <object id="2" instances_count="1">
  <metadata type="object" key="name" value="Second.stl"/>
 </object>
</config>
"""


@pytest.fixture()
def summary():
    return prusa.summarise(CONFIG, MODEL_CONFIG)


def test_it_reads_the_application_and_version(summary):
    assert summary["application"] == "PrusaSlicer"
    assert summary["application_version"] == "2.8.0-alpha3"


def test_it_reads_the_printer_and_its_bed(summary):
    assert summary["printer_model"] == "MK4IS"
    assert summary["bed_mm"] == {"x": 250.0, "y": 210.0}
    assert summary["printer_settings_id"].startswith("Original Prusa MK4")


def test_it_reads_every_filament_slot_with_its_colour(summary):
    assert summary["filament_count"] == 2
    first, second = summary["filaments"]
    assert first["type"] == "PLA" and first["color"] == "#FF8000"
    assert second["type"] == "PETG" and second["color"] == "#1F8CE0"
    assert first["name"] == "Prusament PLA @PGIS"      # quoted, comma-free
    assert first["diameter_mm"] == 1.75


def test_quoted_values_containing_commas_are_not_split():
    config = prusa.settings('; filament_settings_id = "PLA, matte";"PETG"')
    assert prusa._split(config["filament_settings_id"]) == ["PLA, matte", "PETG"]


def test_it_reads_the_print_shape(summary):
    assert summary["layer_height_mm"] == 0.15
    assert summary["first_layer_height_mm"] == 0.2
    assert summary["supports"] is True
    assert summary["bed_temperature_c"] == 60.0
    assert summary["nozzle_temperature_c"] == [225.0, 240.0]


def test_it_reads_per_object_assignments_and_overrides(summary):
    assert summary["object_count"] == 2
    assert summary["extruders_assigned"] == [2]
    assert summary["variable_layer_height"] is True
    assert summary["per_object_overrides"] >= 1
    assert summary["objects"][0]["name"] == "3DBenchy.stl"


def test_a_missing_nozzle_diameter_stays_missing():
    """The real fixture does not state one. Studio must not invent 0.4."""
    assert prusa.summarise(CONFIG)["nozzle_diameters"] == []


def test_a_project_without_the_config_is_refused_clearly():
    assert prusa.summarise(None)["available"] is False


def test_what_cannot_be_carried_over_is_named_before_it_is_lost(summary):
    elements = [item["element"] for item in prusa.not_carried(summary)]
    assert any("Variable layer height" in e for e in elements)
    assert any("Per-object setting overrides" in e for e in elements)
    assert any("Support" in e for e in elements)
    for item in prusa.not_carried(summary):
        assert item["reason"], "every unsupported element must say why"


def test_nothing_is_claimed_for_a_project_with_no_extras():
    plain = prusa.summarise("; printer_model = MK3S\n; layer_height = 0.2\n")
    assert prusa.not_carried(plain) == []
    assert plain["filament_count"] == 0
    assert plain["supports"] is None


def test_traits_read_a_prusa_project_instead_of_shrugging(tmp_path):
    """The integration this whole module exists for."""
    import zipfile

    from snapstudio_core import project_traits

    target = tmp_path / "prusa.3mf"
    with zipfile.ZipFile(target, "w") as zf:
        zf.writestr("[Content_Types].xml", "<Types/>")
        zf.writestr("3D/3dmodel.model",
                    '<model unit="millimeter"><build><item objectid="1"/></build></model>')
        zf.writestr(prusa.SETTINGS_PART, CONFIG)
        zf.writestr(prusa.MODEL_CONFIG_PART, MODEL_CONFIG)

    traits = project_traits.extract(str(target))

    def value(key):
        entry = traits.get(key)
        return entry.get("value") if isinstance(entry, dict) else entry

    assert value("origin_family") == "prusa"
    assert value("origin_application") == "PrusaSlicer 2.8.0-alpha3"
    assert value("target_printer") == "MK4IS"
    assert value("foreign_printer") is True
    assert value("filament_count") == 2
    assert value("object_count") == 2
