"""Which filament each object prints in, across the crossing.

Studio reassigned every object of every PrusaSlicer project it prepared to
filament 1. The geometry was byte-identical, nothing was reported removed, and
the copy printed in the wrong colours — which is the exact failure the fidelity
audit exists to catch and could not see, because it never compared assignments
for a source that speaks a different dialect.

These cover the reading, the carrying, and the catching: every way an assignment
can be damaged between the two files has to be reported, and every legitimate
difference — a default, volumes that cannot be represented — has to be named as
what it is rather than called a loss.
"""
from __future__ import annotations

import re
import zipfile

import pytest

from snapstudio_core import assignments, fidelity
from snapstudio_core.container import ThreeMF
from snapstudio_core.convert import convert_to_u1

CUBE_MODEL = (
    '<?xml version="1.0" encoding="UTF-8"?>'
    '<model unit="millimeter" xmlns="http://schemas.microsoft.com/3dmanufacturing/core/2015/02">'
    '<resources><object id="1" type="model"><mesh>'
    '<vertices><vertex x="0" y="0" z="0"/><vertex x="10" y="0" z="0"/>'
    '<vertex x="0" y="10" z="0"/></vertices>'
    '<triangles><triangle v1="0" v2="1" v3="2"/></triangles>'
    "</mesh></object></resources>"
    '<build><item objectid="1" transform="1 0 0 0 1 0 0 0 1 0 0 0"/></build></model>')


def prusa_project(tmp_path, objects, name="prusa.3mf", config_extra=""):
    """A PrusaSlicer-shaped project: the dialect, with the assignments under test.

    The container's shape is PrusaSlicer's own — the fixtures painted in real
    slicers live in tests/fixtures/painted. What varies here is the one field
    being audited, which is what makes each case readable.
    """
    blocks = []
    for index, spec in enumerate(objects, start=1):
        slot = spec.get("slot")
        volumes = spec.get("volumes") or [None]
        slot_xml = (f'<metadata type="object" key="extruder" value="{slot}"/>'
                    if slot is not None else "")
        volume_xml = "".join(
            f'<volume firstid="0" lastid="0">'
            + (f'<metadata type="volume" key="extruder" value="{v}"/>' if v is not None else "")
            + "</volume>" for v in volumes)
        blocks.append(
            f'<object id="{index}" instances_count="1">'
            f'<metadata type="object" key="name" value="{spec.get("name", f"object {index}")}"/>'
            f"{slot_xml}{volume_xml}</object>")
    path = tmp_path / name
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("3D/3dmodel.model", CUBE_MODEL)
        archive.writestr("Metadata/Slic3r_PE_model.config",
                         '<?xml version="1.0"?><config>' + "".join(blocks) + "</config>")
        archive.writestr("Metadata/Slic3r_PE.config",
                         "; generated by PrusaSlicer 2.9.6\n; layer_height = 0.15\n"
                         "; filament_colour = #FF0000;#00FF00;#0000FF;#FFFF00;#FF00FF;#00FFFF\n"
                         + config_extra)
    return str(path)


def prepared_slots(path) -> list[str]:
    with zipfile.ZipFile(path) as archive:
        settings = archive.read("Metadata/model_settings.config").decode()
    objects = re.split(r"<object\b", settings)[1:]
    return [re.search(r'key="extruder" value="(\d+)"', block).group(1) for block in objects]


def assignment_rows(report) -> list[dict]:
    return [row for row in report["rows"] if row["element"].startswith("Filament for")]


# --- reading ------------------------------------------------------------------

def test_an_explicit_object_assignment_is_read(tmp_path):
    project = prusa_project(tmp_path, [{"slot": 3, "name": "left"}])
    found = assignments.read(ThreeMF.open(project))
    assert found["dialect"] == assignments.DIALECT_PRUSA
    assert found["objects"][0]["slot"] == 3
    assert found["objects"][0]["source"] == assignments.EXPLICIT


def test_an_object_with_no_assignment_is_default_not_slot_one(tmp_path):
    project = prusa_project(tmp_path, [{"name": "left"}])
    entry = assignments.read(ThreeMF.open(project))["objects"][0]
    assert entry["slot"] is None
    assert entry["source"] == assignments.DEFAULT


def test_a_volumes_assignment_is_read_when_the_object_is_silent(tmp_path):
    project = prusa_project(tmp_path, [{"name": "left", "volumes": [4]}])
    entry = assignments.read(ThreeMF.open(project))["objects"][0]
    assert entry["slot"] == 4
    assert entry["source"] == assignments.FROM_VOLUME


def test_the_u1_dialect_is_read_the_same_way(tmp_path):
    project = prusa_project(tmp_path, [{"slot": 2}])
    prepared = convert_to_u1(project, out_dir=str(tmp_path / "out")).output_path
    found = assignments.read(ThreeMF.open(prepared))
    assert found["dialect"] == assignments.DIALECT_BAMBU
    assert found["objects"][0]["slot"] == 2


# --- carrying -----------------------------------------------------------------

@pytest.mark.parametrize("slot", [2, 3, 4])
def test_preparing_a_copy_keeps_the_object_on_its_filament(tmp_path, slot):
    project = prusa_project(tmp_path, [{"slot": slot}], name=f"p{slot}.3mf")
    prepared = convert_to_u1(project, out_dir=str(tmp_path / f"out{slot}")).output_path
    assert prepared_slots(prepared) == [str(slot)]


def test_a_slot_beyond_four_is_carried_rather_than_renumbered(tmp_path):
    """A U1 has four toolheads; a project may still reference six colours. Quietly
    turning slot 6 into slot 4 would be Studio deciding which colours to merge."""
    project = prusa_project(tmp_path, [{"slot": 6}])
    prepared = convert_to_u1(project, out_dir=str(tmp_path / "out")).output_path
    assert prepared_slots(prepared) == ["6"]


def test_an_object_with_no_assignment_crosses_as_unassigned(tmp_path):
    """"Nobody chose" is not "somebody chose filament 1".

    This used to write slot 1, and the fidelity audit called that preserved. Both
    slicers disagree. Round-tripped through PrusaSlicer 2.9.6, a project with no
    extruder metadata comes back with none, and one with `extruder="1"` comes back
    with that stated explicitly — it does not drop it as redundant. Snapmaker Orca
    2.3.5 says the same thing in its own dialect, writing `extruder="0"` for an
    object nobody has assigned, in a file Orca itself wrote.

    Both print from filament 1 under today's defaults. They are still different
    claims about the project, and the copy must not invent the second one.
    """
    project = prusa_project(tmp_path, [{"name": "left"}])
    prepared = convert_to_u1(project, out_dir=str(tmp_path / "out")).output_path
    assert prepared_slots(prepared) == ["0"]


def test_a_volume_assignment_is_carried_when_the_volumes_agree(tmp_path):
    project = prusa_project(tmp_path, [{"name": "left", "volumes": [4, 4]}])
    prepared = convert_to_u1(project, out_dir=str(tmp_path / "out")).output_path
    assert prepared_slots(prepared) == ["4"]


def test_the_object_keeps_its_own_name(tmp_path):
    project = prusa_project(tmp_path, [{"slot": 2, "name": "bracket"}])
    prepared = convert_to_u1(project, out_dir=str(tmp_path / "out")).output_path
    with zipfile.ZipFile(prepared) as archive:
        settings = archive.read("Metadata/model_settings.config").decode()
    assert 'value="bracket"' in settings


# --- catching -----------------------------------------------------------------

def test_fidelity_reports_a_carried_assignment_as_preserved(tmp_path):
    project = prusa_project(tmp_path, [{"slot": 3, "name": "left"}])
    prepared = convert_to_u1(project, out_dir=str(tmp_path / "out")).output_path
    row = assignment_rows(fidelity.audit(project, prepared))[0]
    assert row["status"] == fidelity.PRESERVED_SEMANTIC
    assert "slot 3" in row["detail"]


def _damage(prepared, tmp_path, edit, name="damaged.3mf"):
    with zipfile.ZipFile(prepared) as archive:
        parts = {n: archive.read(n) for n in archive.namelist()}
    parts["Metadata/model_settings.config"] = edit(
        parts["Metadata/model_settings.config"].decode()).encode()
    path = tmp_path / name
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as archive:
        for part, blob in parts.items():
            archive.writestr(part, blob)
    return str(path)


def test_an_assignment_changed_in_the_copy_is_caught(tmp_path):
    project = prusa_project(tmp_path, [{"slot": 3, "name": "left"}])
    prepared = convert_to_u1(project, out_dir=str(tmp_path / "out")).output_path
    damaged = _damage(prepared, tmp_path,
                      lambda text: text.replace('key="extruder" value="3"',
                                                'key="extruder" value="1"'))
    row = assignment_rows(fidelity.audit(project, damaged))[0]
    assert row["status"] == fidelity.CHANGED
    assert row["detail"] == "slot 3 → slot 1"


def test_two_assignments_swapped_are_caught(tmp_path):
    project = prusa_project(tmp_path, [{"slot": 2, "name": "a"}, {"slot": 3, "name": "b"}])
    prepared = convert_to_u1(project, out_dir=str(tmp_path / "out")).output_path
    if prepared_slots(prepared) != ["2", "3"]:
        pytest.skip("this container carries one build object; the swap needs two")
    damaged = _damage(prepared, tmp_path, lambda text: text
                      .replace('value="2"', "value=\"TMP\"")
                      .replace('value="3"', 'value="2"')
                      .replace('value="TMP"', 'value="3"'))
    statuses = {row["status"] for row in assignment_rows(fidelity.audit(project, damaged))}
    assert fidelity.CHANGED in statuses


def test_an_assignment_removed_from_the_copy_is_caught(tmp_path):
    project = prusa_project(tmp_path, [{"slot": 3, "name": "left"}])
    prepared = convert_to_u1(project, out_dir=str(tmp_path / "out")).output_path
    damaged = _damage(prepared, tmp_path,
                      lambda text: text.replace('<metadata key="extruder" value="3"/>', "", 1))
    row = assignment_rows(fidelity.audit(project, damaged))[0]
    assert row["status"] in (fidelity.REMOVED, fidelity.CHANGED)


def test_an_explicit_assignment_replaced_by_the_default_is_caught(tmp_path):
    project = prusa_project(tmp_path, [{"slot": 5, "name": "left"}])
    prepared = convert_to_u1(project, out_dir=str(tmp_path / "out")).output_path
    damaged = _damage(prepared, tmp_path,
                      lambda text: text.replace('value="5"', 'value="1"'))
    row = assignment_rows(fidelity.audit(project, damaged))[0]
    assert row["status"] == fidelity.CHANGED
    assert "slot 5 → slot 1" in row["detail"]


def test_a_slot_beyond_four_collapsed_into_range_is_caught(tmp_path):
    project = prusa_project(tmp_path, [{"slot": 6, "name": "left"}])
    prepared = convert_to_u1(project, out_dir=str(tmp_path / "out")).output_path
    damaged = _damage(prepared, tmp_path,
                      lambda text: text.replace('value="6"', 'value="4"'))
    row = assignment_rows(fidelity.audit(project, damaged))[0]
    assert row["status"] == fidelity.CHANGED
    assert "slot 6 → slot 4" in row["detail"]


def test_volumes_that_disagree_are_reported_as_not_representable(tmp_path):
    """A prepared U1 object is one part. Two volumes on different filaments cannot
    both survive, and that is a limit of the crossing — not a silent choice."""
    project = prusa_project(tmp_path, [{"slot": 2, "name": "left", "volumes": [2, 5]}])
    prepared = convert_to_u1(project, out_dir=str(tmp_path / "out")).output_path
    row = assignment_rows(fidelity.audit(project, prepared))[0]
    assert row["status"] == fidelity.UNSUPPORTED
    # The card names each part and its filament rather than printing a set, so a
    # person can see which half of their object is not coming across.
    assert "part 1 uses filament 2" in row["detail"]
    assert "part 2 uses filament 5" in row["detail"]
    assert "does not choose one for you" in row["detail"]
    assert "cannot carry both" in row["detail"]


def test_a_copy_with_no_assignments_at_all_is_reported_as_removed(tmp_path):
    project = prusa_project(tmp_path, [{"slot": 3}])
    prepared = convert_to_u1(project, out_dir=str(tmp_path / "out")).output_path
    stripped = tmp_path / "stripped.3mf"
    with zipfile.ZipFile(prepared) as archive:
        parts = {n: archive.read(n) for n in archive.namelist()
                 if n != "Metadata/model_settings.config"}
    with zipfile.ZipFile(stripped, "w", zipfile.ZIP_DEFLATED) as archive:
        for part, blob in parts.items():
            archive.writestr(part, blob)
    rows = [row for row in fidelity.audit(project, str(stripped))["rows"]
            if row["element"] == "Which filament each object uses"]
    assert rows and rows[0]["status"] == fidelity.REMOVED


# --- files that are trying to break it ----------------------------------------

@pytest.mark.parametrize("value", ["0", "-1", "", "abc", "2.5", " 3 "])
def test_an_unusable_extruder_value_is_not_read_as_a_slot(tmp_path, value):
    path = tmp_path / f"odd-{abs(hash(value))}.3mf"
    with zipfile.ZipFile(path, "w") as archive:
        archive.writestr("3D/3dmodel.model", CUBE_MODEL)
        archive.writestr("Metadata/Slic3r_PE_model.config",
                         '<config><object id="1">'
                         f'<metadata type="object" key="extruder" value="{value}"/>'
                         "</object></config>")
    entry = assignments.read(ThreeMF.open(str(path)))["objects"][0]
    assert entry["slot"] is None or entry["slot"] > 0


def test_a_project_with_no_model_config_says_so_rather_than_guessing(tmp_path):
    path = tmp_path / "bare.3mf"
    with zipfile.ZipFile(path, "w") as archive:
        archive.writestr("3D/3dmodel.model", CUBE_MODEL)
    found = assignments.read(ThreeMF.open(str(path)))
    assert found["available"] is False
    assert "no per-object filament assignment" in found["reason"]


def test_more_objects_in_the_copy_than_the_source_are_unknown_not_matched(tmp_path):
    before = {"available": True, "dialect": "prusa",
              "objects": [{"object_id": "1", "index": 0, "name": "a", "slot": 2,
                           "source": assignments.EXPLICIT, "volume_slots": []}]}
    after = {"available": True, "dialect": "bambu",
             "objects": [{"object_id": "1", "index": 0, "name": "a", "slot": 2,
                          "source": assignments.EXPLICIT, "volume_slots": []},
                         {"object_id": "2", "index": 1, "name": "b", "slot": 1,
                          "source": assignments.EXPLICIT, "volume_slots": []}]}
    verdict = assignments.compare(before, after)
    assert verdict["rows"][0]["status"] == assignments.PRESERVED
    assert verdict["rows"][1]["status"] == assignments.UNKNOWN


def test_an_object_missing_from_the_copy_is_unknown(tmp_path):
    before = {"available": True, "dialect": "prusa",
              "objects": [{"object_id": "1", "index": 0, "name": "a", "slot": 2,
                           "source": assignments.EXPLICIT, "volume_slots": []},
                          {"object_id": "2", "index": 1, "name": "b", "slot": 3,
                           "source": assignments.EXPLICIT, "volume_slots": []}]}
    after = {"available": True, "dialect": "bambu",
             "objects": [{"object_id": "1", "index": 0, "name": "a", "slot": 2,
                          "source": assignments.EXPLICIT, "volume_slots": []}]}
    verdict = assignments.compare(before, after)
    assert verdict["rows"][1]["status"] == assignments.UNKNOWN
    assert "not in the prepared copy" in verdict["rows"][1]["detail"]


def test_quoted_and_crlf_config_still_parses(tmp_path):
    path = tmp_path / "crlf.3mf"
    config = ('<config>\r\n<object id="1">\r\n'
              '  <metadata type="object" key="name" value="left"/>\r\n'
              '  <metadata type="object" key="extruder" value="3"/>\r\n'
              "</object>\r\n</config>\r\n")
    with zipfile.ZipFile(path, "w") as archive:
        archive.writestr("3D/3dmodel.model", CUBE_MODEL)
        archive.writestr("Metadata/Slic3r_PE_model.config", config)
    entry = assignments.read(ThreeMF.open(str(path)))["objects"][0]
    assert entry["slot"] == 3 and entry["name"] == "left"


def test_reading_never_raises_on_a_malformed_config(tmp_path):
    path = tmp_path / "broken.3mf"
    with zipfile.ZipFile(path, "w") as archive:
        archive.writestr("3D/3dmodel.model", CUBE_MODEL)
        archive.writestr("Metadata/Slic3r_PE_model.config", "<config><object id=")
    found = assignments.read(ThreeMF.open(str(path)))
    assert found["available"] is True
    assert found["objects"] == [] or found["objects"][0]["slot"] is None
