"""What Studio is allowed to spend on a job it has never seen before.

Real jobs reach hundreds of megabytes, and a plate of small parts can carry
thousands of object labels. None of that is unusual, and all of it is a way to
make an app that reads files hang, or hold half a gigabyte of them in memory, or
send a megabyte of nothing over its own loopback.

These are not benchmarks. They are the bounds: what is read, what is kept, and
what is handed on. A file bigger than the bounds is answered with less detail —
never with a longer wait.

Building a 500 MB file in CI is not worth the disk, so the large cases here are
built to be *shaped* like one — the caps they exercise do not care about the
zeroes in between. The real 525 MB measurement is in the sprint record.
"""
from __future__ import annotations

import time

import pytest

from snapstudio_api import service
from snapstudio_core import gcode, print_plan, watch_folder

HEAD = """\
; HEADER_BLOCK_START
; generated by Snapmaker Orca 2.3.5 on 2026-08-23 at 10:00:00
; total layer number: 4000
; HEADER_BLOCK_END
PRINT_START
"""

TAIL = """\
PRINT_END
; EXECUTABLE_BLOCK_END
; filament used [g] = 100.0, 90.0
; total filament used [g] = 190.0
; total layers count = 4000
; estimated printing time (normal mode) = 41h 12m
; CONFIG_BLOCK_START
; filament_type = PLA;PLA
; filament_colour = #FF0000;#00FF00
; nozzle_diameter = 0.4,0.4
; printer_model = Snapmaker U1
; CONFIG_BLOCK_END
"""


def build(tmp_path, name, body, endings="\n"):
    target = tmp_path / name
    text = (HEAD + body + TAIL)
    if endings != "\n":
        text = text.replace("\n", endings)
    target.write_bytes(text.encode("utf-8"))
    return target


def test_thousands_of_objects_are_capped_and_the_cap_is_admitted(tmp_path):
    """A plate of five thousand parts is a real thing to print. Hashing every name
    would bloat every answer — and a truncated set must never be used to rule a
    project out, so the reader says the set is incomplete."""
    body = "".join(f"; printing object part_{i:05d}.stl id:{i} copy 0\nG1 X1 Y1 E1\n"
                   for i in range(5000))
    facts = gcode.read_facts(build(tmp_path, "many.gcode", body))
    assert facts["objects"]["count"] == gcode.MAX_OBJECT_NAMES
    assert facts["objects"]["complete"] is False
    assert len(facts["objects"]["name_hashes"]) == gcode.MAX_OBJECT_NAMES


def test_a_partial_object_set_never_rules_a_project_out(tmp_path):
    from snapstudio_core import provenance

    body = "".join(f"; printing object part_{i:05d}.stl id:{i} copy 0\nG1 X1 Y1 E1\n"
                   for i in range(5000))
    facts = gcode.read_facts(build(tmp_path, "many.gcode", body))
    unrelated = {"readable": True,
                 "object_name_hashes": {"value": [gcode._digest_of(["something else"])]}}
    assert provenance.compare(unrelated, facts)["verdict"] != provenance.NO_MATCH


def test_a_hundred_thousand_events_are_capped(tmp_path):
    body = "".join(f"T{i % 4}\nG1 X1 Y1 E1\n" for i in range(30_000))
    plan = print_plan.scan(build(tmp_path, "changes.gcode", body))
    assert plan["truncated"] is True
    assert len(plan["events"]) <= print_plan.MAX_EVENTS


def test_the_timeline_handed_to_the_app_is_a_sample_not_the_scan(tmp_path):
    """Twenty thousand events is a megabyte over the loopback, and the app shows
    the narration and the counts."""
    body = "".join(f"T{i % 4}\nG1 X1 Y1 E1\n" for i in range(30_000))
    plan = service.print_plan(str(build(tmp_path, "changes.gcode", body)))
    assert plan["events_sampled"] is True
    assert len(plan["events"]) <= service.EVENT_SAMPLE
    assert plan["event_count"] > service.EVENT_SAMPLE
    assert plan["narration"]


def test_a_giant_thumbnail_does_not_become_the_answer(tmp_path):
    body = ("; thumbnail begin 300x300 8000000\n"
            + "".join("; " + "QUJDRA" * 12 + "\n" for _ in range(20_000))
            + "; thumbnail end\nG1 X1 Y1 E1\n")
    facts = gcode.read_facts(build(tmp_path, "thumb.gcode", body))
    assert facts["available"] is True
    assert facts["has_thumbnail"] is True
    assert facts["printer_model"] == "Snapmaker U1"


@pytest.mark.parametrize("endings", ["\n", "\r\n"])
def test_line_endings_do_not_change_what_is_read(tmp_path, endings):
    body = ("; printing object bracket.stl id:0 copy 0\nG1 X1 Y1 E1\nM600\n"
            "; stop printing object bracket.stl id:0 copy 0\n")
    facts = gcode.read_facts(build(tmp_path, "endings.gcode", body, endings))
    assert facts["objects"]["count"] == 1
    plan = print_plan.scan(build(tmp_path, "endings2.gcode", body, endings))
    assert plan["pauses"] == 1


def test_binary_noise_in_the_middle_does_not_stop_the_read(tmp_path):
    target = tmp_path / "noisy.gcode"
    target.write_bytes(HEAD.encode() + b"\xff\xfe\x00 not text \xc3\x28\n"
                       + b"; printing object bracket.stl id:0 copy 0\nG1 X1 Y1 E1\n"
                       + TAIL.encode())
    facts = gcode.read_facts(target)
    assert facts["available"] is True
    assert facts["objects"]["count"] == 1


def test_a_folder_of_large_files_is_scanned_without_reading_them(tmp_path):
    """The watcher looks at sizes, timestamps and the last 64 KB. A folder of big
    jobs must not cost the size of the folder."""
    body = "".join(f"G1 X{i} Y{i} E1\n" for i in range(200_000))
    for index in range(6):
        build(tmp_path, f"job{index}.gcode", body)
    watch_folder.forget()
    started = time.time()
    found = watch_folder.scan(tmp_path)
    assert len(found["candidates"]) == 6
    assert time.time() - started < 3.0


# --- painted colour ----------------------------------------------------------
#
# A painted model is the biggest thing Studio decodes per facet rather than per
# file, so it is the easiest place to accidentally make opening a project take
# minutes. These fix the shape of the cost: linear in painted facets, bounded in
# what one file can ask for, and never holding the whole decode in memory.

def _painted_project(path, facets, *, subdivided=False, painted_every=1):
    from snapstudio_core import paint_codec

    deep = (0, [1, (1, [2, (2, [3, 4, 5])]), 6, 7])
    vertices, triangles = [], []
    for index in range(facets):
        z = (index % 100) * 0.5
        base = index * 3
        vertices += [f'<vertex x="0" y="0" z="{z}"/>',
                     f'<vertex x="10" y="0" z="{z}"/>',
                     f'<vertex x="0" y="10" z="{z + 0.5}"/>']
        attribute = ""
        if painted_every and index % painted_every == 0:
            tree = deep if subdivided else (index % 7) + 1
            attribute = f' paint_color="{paint_codec.encode_tree(tree)}"'
        triangles.append(f'<triangle v1="{base}" v2="{base + 1}" '
                         f'v3="{base + 2}"{attribute}/>')
    model = ('<?xml version="1.0"?><model unit="millimeter">'
             '<resources><object id="1" type="model"><mesh>'
             f"<vertices>{''.join(vertices)}</vertices>"
             f"<triangles>{''.join(triangles)}</triangles>"
             "</mesh></object></resources>"
             '<build><item objectid="1"/></build></model>')
    import zipfile
    with zipfile.ZipFile(path, "w", zipfile.ZIP_DEFLATED) as archive:
        archive.writestr("3D/3dmodel.model", model)
        archive.writestr("Metadata/project_settings.config",
                         '{"filament_colour":["#1","#2","#3","#4","#5","#6","#7"]}')
        archive.writestr("Metadata/model_settings.config",
                         '<config><object id="1"><part id="1" subtype="normal_part">'
                         '<metadata key="extruder" value="1"/></part></object></config>')
    return str(path)


def test_a_heavily_painted_mesh_is_read_in_seconds_not_minutes(tmp_path):
    from snapstudio_core import painted_color

    path = _painted_project(tmp_path / "painted.3mf", 60_000)
    start = time.perf_counter()
    result = painted_color.read(path)
    elapsed = time.perf_counter() - start
    assert result["painted_triangle_count"] == 60_000
    assert result["slots_referenced"] == [1, 2, 3, 4, 5, 6, 7]
    # Measured at about 0.4 s for this size on the sprint machine; the bound is
    # loose enough for a slow CI worker and tight enough to catch a regression
    # that makes the cost non-linear.
    assert elapsed < 8.0, f"reading 60,000 painted facets took {elapsed:.1f}s"


def test_the_painted_facet_budget_stops_a_file_asking_for_unbounded_work(tmp_path, monkeypatch):
    from snapstudio_core import painted_color

    monkeypatch.setattr(painted_color, "MAX_PAINTED_TRIANGLES", 500)
    path = _painted_project(tmp_path / "huge.3mf", 5_000)
    result = painted_color.read(path)
    assert result["truncated"] is True
    assert result["limits"]["budget_exhausted"] is True
    assert result["painted_triangle_count"] == 500


def test_a_finely_subdivided_file_is_bounded_by_patches_not_only_facets(tmp_path, monkeypatch):
    # Seven patches per facet: a file can stay under any facet bound and still
    # ask for an unbounded amount of decoding.
    from snapstudio_core import painted_color

    monkeypatch.setattr(painted_color, "MAX_PAINTED_LEAVES", 700)
    path = _painted_project(tmp_path / "deep.3mf", 5_000, subdivided=True)
    result = painted_color.read(path)
    assert result["truncated"] is True
    assert result["painted_triangle_count"] < 5_000


def test_an_unpainted_mesh_costs_almost_nothing_to_check(tmp_path):
    # The common case is a project with no painting at all, and it must not pay
    # for the decoder: no vertices are parsed and no facet is decoded.
    from snapstudio_core import painted_color

    path = _painted_project(tmp_path / "plain.3mf", 60_000, painted_every=None)
    start = time.perf_counter()
    result = painted_color.read(path)
    elapsed = time.perf_counter() - start
    assert result["slots_referenced"] == []
    assert elapsed < 2.0, f"checking an unpainted 60,000-facet mesh took {elapsed:.1f}s"
