"""Provenance, the folder watcher, and the material providers.

These three exist to close the last manual step in the workflow: after Snapmaker
Orca slices a prepared copy, Studio should notice the result and know whether it
belongs to the project the user just checked.

The tests are mostly about refusal. Picking up the wrong file and checking it
confidently against a printer is worse than picking up nothing, so a filename
must never be proof, an ambiguous answer must stay ambiguous, and a folder with
two equally good candidates must produce a question rather than a guess.
"""
from __future__ import annotations

import json
import time
from pathlib import Path

import pytest

from snapstudio_core import gcode, material_providers, provenance, watch_folder

# --- helpers ----------------------------------------------------------------

HEADER = """\
; HEADER_BLOCK_START
; generated by Snapmaker Orca 2.3.4 on 2026-08-23 at 10:00:00
; total layer number: 6
; HEADER_BLOCK_END
; EXECUTABLE_BLOCK_START
PRINT_START
"""

FOOTER = """\
PRINT_END
; EXECUTABLE_BLOCK_END

; filament used [g] = 4.00, 3.00
; total filament used [g] = 7.00
; total layers count = 6
; estimated printing time (normal mode) = 41m 12s

; CONFIG_BLOCK_START
; filament_type = PLA;PETG
; filament_colour = {colours}
; nozzle_diameter = 0.4,0.4
; printable_area = 0.5x1,270.5x1,270.5x271,0.5x271
; printer_model = {printer}
; CONFIG_BLOCK_END
"""


def write_job(tmp_path, name="job.gcode", *, colours="#FF0000;#00FF00",
              printer="Snapmaker U1", objects=("Left bracket", "Right bracket")):
    body = ""
    for index, obj in enumerate(objects or ()):
        body += f'EXCLUDE_OBJECT_DEFINE NAME={obj.replace(" ", "_")} CENTER=10,{index * 10}\n'
    body += "T0\n;LAYER_CHANGE\n;Z:0.2\nG1 X10 Y10 E1\n"
    target = tmp_path / name
    target.write_text(HEADER + body + FOOTER.format(colours=colours, printer=printer),
                      encoding="utf-8")
    return target


def traits(**over) -> dict:
    base = {
        "readable": True,
        "object_name_digest": {"value": None},
        "filament_slots": {"value": [{"tool": 0, "type": "PLA", "color": "#FF0000"},
                                     {"tool": 1, "type": "PETG", "color": "#00FF00"}]},
        "filament_count": {"value": 2},
        "target_printer": {"value": "Snapmaker U1"},
        "object_count": {"value": 2},
    }
    for key, value in over.items():
        base[key] = {"value": value}
    return base


def digest_of(job: Path) -> str:
    return (gcode.read_facts(job)["exclude_object"] or {})["name_digest"]


# --- provenance --------------------------------------------------------------

def test_the_same_object_names_confirm_the_match(tmp_path):
    job = write_job(tmp_path)
    result = provenance.compare(traits(object_name_digest=digest_of(job)),
                                gcode.read_facts(job))
    assert result["verdict"] == provenance.CONFIRMED
    assert "same set of objects" in result["summary"]


def test_different_object_names_rule_it_out(tmp_path):
    job = write_job(tmp_path)
    result = provenance.compare(traits(object_name_digest="0123456789abcdef"),
                                gcode.read_facts(job))
    assert result["verdict"] == provenance.NO_MATCH


def test_matching_colours_and_materials_make_it_likely(tmp_path):
    job = write_job(tmp_path, objects=())          # no object names to compare
    result = provenance.compare(traits(), gcode.read_facts(job))
    assert result["verdict"] == provenance.LIKELY
    assert any(e["signal"] == "filament colours" for e in result["evidence"])


def test_completely_different_filaments_rule_it_out(tmp_path):
    job = write_job(tmp_path, objects=(), colours="#123456;#654321")
    result = provenance.compare(traits(), gcode.read_facts(job))
    assert result["verdict"] == provenance.NO_MATCH


def test_a_filename_is_never_proof(tmp_path):
    """The whole point. Two files can share a name and share nothing else."""
    job = write_job(tmp_path, name="benchy_PLA_2h13m.gcode", objects=(),
                    colours="#111111;#222222")
    result = provenance.compare(traits(), gcode.read_facts(job),
                                project_name="benchy.3mf", gcode_name=job.name)
    assert result["verdict"] != provenance.CONFIRMED
    names = [e for e in result["evidence"] if e["signal"] == "file name"]
    assert names and names[0]["weight"] <= provenance.WEAK


def test_a_prepared_u1_copy_does_not_look_like_a_different_project(tmp_path):
    """Preparing a copy rewrites the printer target on purpose. That must not be
    read as evidence against the match."""
    job = write_job(tmp_path, objects=())
    result = provenance.compare(traits(target_printer="Bambu Lab X1 Carbon"),
                                gcode.read_facts(job))
    printer = next(e for e in result["evidence"] if e["signal"] == "printer")
    assert printer["weight"] > 0
    assert result["verdict"] in (provenance.LIKELY, provenance.CONFIRMED)


def test_nothing_to_compare_is_unknown_not_a_match(tmp_path):
    job = write_job(tmp_path, objects=())
    empty = {"readable": True}
    result = provenance.compare(empty, gcode.read_facts(job))
    assert result["verdict"] == provenance.UNKNOWN
    assert "cannot tell" in result["summary"]


def test_an_unreadable_job_is_reported_not_matched(tmp_path):
    bad = tmp_path / "notes.gcode"
    bad.write_text("this is prose", encoding="utf-8")
    result = provenance.compare(traits(), gcode.read_facts(bad))
    assert result["verdict"] == provenance.UNKNOWN
    assert "G-code" in result["summary"]


def test_two_equally_good_candidates_are_a_question_not_an_answer():
    same = {"provenance": {"verdict": provenance.LIKELY, "score": 50}}
    other = {"provenance": {"verdict": provenance.LIKELY, "score": 50}}
    assert provenance.best_of([same, other]) is None
    better = {"provenance": {"verdict": provenance.CONFIRMED, "score": 150}}
    assert provenance.best_of([same, better]) is better


# --- the folder watcher ------------------------------------------------------

def test_only_gcode_in_the_chosen_folder_is_considered(tmp_path, monkeypatch):
    monkeypatch.setattr(watch_folder, "SETTLE_SECONDS", 0)
    write_job(tmp_path, "a.gcode")
    (tmp_path / "notes.txt").write_text("hello", encoding="utf-8")
    (tmp_path / "model.3mf").write_bytes(b"PK\x03\x04rest")
    found = watch_folder.scan(tmp_path)
    assert found["available"] is True
    assert [c["name"] for c in found["candidates"]] == ["a.gcode"]


def test_a_file_still_being_written_is_not_offered(tmp_path, monkeypatch):
    monkeypatch.setattr(watch_folder, "SETTLE_SECONDS", 0)
    partial = tmp_path / "partial.gcode"
    partial.write_text(HEADER + "G1 X1 Y1\n", encoding="utf-8")   # no end markers
    found = watch_folder.scan(tmp_path)
    candidate = found["candidates"][0]
    assert candidate["complete"] is False
    assert "still" in candidate["state"] or "missing" in candidate["state"]


def test_an_empty_file_is_never_complete(tmp_path, monkeypatch):
    monkeypatch.setattr(watch_folder, "SETTLE_SECONDS", 0)
    (tmp_path / "empty.gcode").write_text("", encoding="utf-8")
    assert watch_folder.scan(tmp_path)["candidates"][0]["complete"] is False


def test_old_jobs_are_ignored(tmp_path, monkeypatch):
    monkeypatch.setattr(watch_folder, "SETTLE_SECONDS", 0)
    old = write_job(tmp_path, "old.gcode")
    import os
    stale = time.time() - (48 * 60 * 60)
    os.utime(old, (stale, stale))
    write_job(tmp_path, "new.gcode")
    names = [c["name"] for c in watch_folder.scan(tmp_path)["candidates"]]
    assert names == ["new.gcode"]


def test_a_missing_folder_is_an_answer_not_a_crash(tmp_path):
    found = watch_folder.scan(tmp_path / "nope")
    assert found["available"] is False
    assert "does not exist" in found["error"]


def test_the_watcher_ties_a_job_to_the_open_project(tmp_path, monkeypatch):
    monkeypatch.setattr(watch_folder, "SETTLE_SECONDS", 0)
    job = write_job(tmp_path, "match.gcode")
    write_job(tmp_path, "other.gcode", colours="#AAAAAA;#BBBBBB", objects=("Something else",))

    import snapstudio_core.project_traits as pt
    monkeypatch.setattr(pt, "extract", lambda _path: traits(object_name_digest=digest_of(job)))

    found = watch_folder.match_project(tmp_path, "project.3mf")
    assert found["best"] == str(job)
    assert found["best_verdict"] == provenance.CONFIRMED
    assert "sliced version of your project" in found["summary"]


# --- material providers ------------------------------------------------------

def test_the_stock_printer_reports_what_is_loaded_and_not_how_much(monkeypatch):
    import snapstudio_core.moonraker as mr
    monkeypatch.setattr(mr, "loaded_filaments", lambda *a, **k: [
        {"color": "#000000", "material": "PLA Matte", "vendor": "Snapmaker"}, None])
    state = material_providers.stock_u1("printer.local")
    assert state["available"] is True
    assert state["remaining_known"] is False
    assert state["slots"][0]["material"] == "PLA"
    assert state["slots"][0]["subtype"] == "Matte"
    assert state["slots"][1]["present"] is False
    assert state["slots"][0]["remaining_g"] is None


def test_a_printer_that_reports_nothing_is_unavailable_not_empty(monkeypatch):
    import snapstudio_core.moonraker as mr
    monkeypatch.setattr(mr, "loaded_filaments", lambda *a, **k: None)
    state = material_providers.stock_u1("printer.local")
    assert state["available"] is False
    assert "does not report" in state["error"]


def test_spoolman_is_read_only_and_maps_slots_the_user_declared(monkeypatch):
    payload = [
        {"id": 7, "remaining_weight": 431.5, "archived": False,
         "filament": {"material": "PLA Silk", "color_hex": "2D9E59", "name": "Green",
                      "vendor": {"name": "Snapmaker"}}},
        {"id": 9, "remaining_weight": 12.0, "archived": True,
         "filament": {"material": "PETG", "color_hex": "1F8CE0", "vendor": {"name": "Prusa"}}},
    ]
    monkeypatch.setattr(material_providers, "_get_json", lambda url, timeout=4.0: payload)
    state = material_providers.spoolman("http://spoolman.local:7912", slot_map={"1": 7})
    assert state["available"] is True
    assert state["remaining_known"] is True
    assert len(state["spools"]) == 2
    slot = state["slots"][0]
    assert slot["slot"] == 1 and slot["spool_id"] == 7
    assert slot["material"] == "PLA" and slot["subtype"] == "Silk"
    assert slot["remaining_g"] == 431.5
    # The user said which spool is where; the printer did not confirm it.
    assert slot["confidence"] == material_providers.LIKELY


def test_an_unreachable_spoolman_is_reported_not_fatal(monkeypatch):
    def boom(url, timeout=4.0):
        raise OSError("nope")
    monkeypatch.setattr(material_providers, "_get_json", boom)
    state = material_providers.spoolman("http://spoolman.local:7912")
    assert state["available"] is False
    assert "unexpected" in state["error"] or "did not answer" in state["error"]


def test_a_provider_never_overrides_what_the_printer_can_see():
    printer = {"schema_version": "materials/1", "source": material_providers.STOCK,
               "available": True, "remaining_known": False,
               "slots": [material_providers._slot(0, material="PLA", subtype="Matte",
                                                  color="#000000")]}
    tracker = {"schema_version": "materials/1", "source": material_providers.SPOOLMAN,
               "available": True, "remaining_known": True,
               "slots": [material_providers._slot(0, material="PETG", color="#FFFFFF",
                                                  spool_id=7, remaining_g=431.5,
                                                  source=material_providers.SPOOLMAN)]}
    combined = material_providers.combine(printer, tracker)
    slot = combined["slots"][0]
    assert slot["material"] == "PLA"        # the machine is looking at it
    assert slot["color"] == "#000000"
    assert slot["spool_id"] == 7            # the tracker adds what the machine cannot know
    assert slot["remaining_g"] == 431.5
    assert combined["remaining_known"] is True


def test_a_disagreement_about_an_empty_slot_is_reported_as_one():
    printer = {"source": material_providers.STOCK, "available": True,
               "slots": [material_providers._slot(0, present=False)]}
    tracker = {"source": material_providers.SPOOLMAN, "available": True,
               "slots": [material_providers._slot(0, material="PLA", spool_id=3,
                                                  source=material_providers.SPOOLMAN)]}
    slot = material_providers.combine(printer, tracker)["slots"][0]
    assert slot["confidence"] == material_providers.UNKNOWN
    assert slot["conflicts"]


def test_the_normalised_state_fits_the_shape_the_checks_already_use():
    state = material_providers.combine({
        "source": material_providers.STOCK, "available": True,
        "slots": [material_providers._slot(0, material="PLA", subtype="Matte", color="#000000"),
                  material_providers._slot(1, present=False)]})
    loaded = material_providers.as_loaded_filaments(state)
    assert loaded[0]["material"] == "PLA Matte"
    assert loaded[1] is None


def test_no_providers_means_no_state_not_an_empty_printer():
    assert material_providers.as_loaded_filaments({"available": False}) is None
    assert material_providers.combine()["available"] is False
