"""The print-plan timeline, the material plan, and the send confirmation.

These three answer the questions that only exist after slicing: what happens and
when, what should be loaded, and whether to press send. The fixtures are shaped
like real Snapmaker Orca output — the multi-tool one is modelled on a genuine
four-colour job with 764 tool changes.
"""
from __future__ import annotations

import pytest

from snapstudio_core import gcode, material_plan, print_plan, send_check

HEADER = """\
; HEADER_BLOCK_START
; generated by Snapmaker Orca 2.3.4 on 2026-08-23 at 10:00:00
; total layer number: 6
; HEADER_BLOCK_END
; EXECUTABLE_BLOCK_START
PRINT_START
M140 S65
M104 T0 S220
"""

CONFIG = """\

; filament used [g] = 4.00, 3.00, 0.00, 1.00
; total filament used [g] = 8.00
; total layers count = 6
; estimated printing time (normal mode) = 41m 12s

; CONFIG_BLOCK_START
; filament_type = PLA;PETG;PLA;PLA
; filament_colour = #FF0000;#00FF00;#0000FF;#FFFFFF
; nozzle_diameter = 0.4,0.4,0.4,0.4
; printable_area = 0.5x1,270.5x1,270.5x271,0.5x271
; printer_model = Snapmaker U1
; CONFIG_BLOCK_END
"""


def build(tmp_path, body: str, name="job.gcode"):
    target = tmp_path / name
    target.write_text(HEADER + body + "; EXECUTABLE_BLOCK_END\n" + CONFIG, encoding="utf-8")
    return target


MULTI_BODY = """\
T0
;LAYER_CHANGE
;Z:0.2
G1 X10 Y10 E1
T1
;LAYER_CHANGE
;Z:0.4
G1 X10 Y10 E1
T0
;LAYER_CHANGE
;Z:0.6
T3
;LAYER_CHANGE
;Z:0.8
M600
;LAYER_CHANGE
;Z:1.0
T1
;LAYER_CHANGE
;Z:1.2
"""


@pytest.fixture()
def multi(tmp_path):
    return build(tmp_path, MULTI_BODY)


# --- the timeline -----------------------------------------------------------

def test_the_timeline_counts_layers_tools_and_pauses(multi):
    plan = print_plan.scan(multi)
    assert plan["available"] is True
    assert plan["layers_seen"] == 6
    assert plan["tools_seen"] == [0, 1, 3]
    assert plan["tool_changes"] == 5
    assert plan["pauses"] == 1
    assert plan["first_tool"] == 0
    assert plan["last_tool"] == 1


def test_it_records_when_each_tool_arrives_and_leaves(multi):
    plan = print_plan.scan(multi)
    assert plan["tool_first_layer"]["3"] == 3
    assert plan["tool_last_layer"]["0"] == 2


def test_it_reads_the_temperature_targets_the_job_sets(multi):
    plan = print_plan.scan(multi)
    assert plan["bed_target_c"] == 65.0
    assert plan["nozzle_targets_c"]["0"] == 220.0


def test_narration_is_ordered_plain_language_with_its_evidence(multi):
    plan = print_plan.scan(multi)
    lines = print_plan.narrate(plan, gcode.read_facts(multi))
    text = " | ".join(line["text"] for line in lines)
    assert "Prints with slot 1" in text
    assert "Slot 4 joins in" in text
    assert "pauses and waits for you" in text
    assert all(line["evidence"] for line in lines)


def test_narration_names_the_material_the_printer_actually_has(multi):
    loaded = [{"color": "#101010", "material": "PLA Matte"}, None, None, None]
    lines = print_plan.narrate(print_plan.scan(multi), gcode.read_facts(multi), loaded)
    assert any("PLA Matte" in line["text"] for line in lines)


def test_a_missing_file_is_an_answer_not_a_crash(tmp_path):
    plan = print_plan.scan(tmp_path / "nope.gcode")
    assert plan["available"] is False
    assert "does not exist" in plan["error"]
    assert print_plan.narrate(plan) == []


def test_the_event_budget_is_capped_and_says_so(tmp_path, monkeypatch):
    monkeypatch.setattr(print_plan, "MAX_EVENTS", 5)
    body = "".join(f"T{i % 4}\n;LAYER_CHANGE\n;Z:{i / 10}\n" for i in range(200))
    plan = print_plan.scan(build(tmp_path, body, name="busy.gcode"))
    assert plan["truncated"] is True
    assert len(plan["events"]) <= 5
    assert "more" in print_plan.summary(plan)


def test_memory_does_not_grow_with_file_size(tmp_path):
    """A 40 MB job is scanned without holding it — the guard against someone
    dropping a 300 MB print in."""
    import tracemalloc
    padding = "G1 X10.5 Y20.5 E0.0123 F1200\n" * 900_000
    target = build(tmp_path, MULTI_BODY + padding, name="big.gcode")
    assert target.stat().st_size > 20 * 1024 * 1024
    tracemalloc.start()
    plan = print_plan.scan(target)
    peak = tracemalloc.get_traced_memory()[1]
    tracemalloc.stop()
    assert plan["available"] is True
    assert plan["tools_seen"] == [0, 1, 3]
    assert peak < 12 * 1024 * 1024


# --- what to load -----------------------------------------------------------

def loaded_four(**over):
    base = [
        {"color": "#FF0000", "material": "PLA Basic"},
        {"color": "#00FF00", "material": "PETG"},
        {"color": "#0000FF", "material": "PLA"},
        {"color": "#FFFFFF", "material": "PLA Matte"},
    ]
    for index, value in over.items():
        base[int(index)] = value
    return base


def test_a_slot_the_job_never_uses_is_left_alone(multi):
    facts = gcode.read_facts(multi)
    plan = material_plan.plan(facts["slots"], loaded_four(), facts["tools_used"])
    unused = next(s for s in plan["slots"] if s["tool"] == 2)
    assert unused["state"] == "unused"
    assert "Leave it" in unused["action"]


def test_an_empty_slot_the_job_uses_is_a_change(multi):
    facts = gcode.read_facts(multi)
    plan = material_plan.plan(facts["slots"], loaded_four(**{"1": None}), facts["tools_used"])
    empty = next(s for s in plan["slots"] if s["tool"] == 1)
    assert empty["state"] == "empty"
    assert 1 in plan["to_change"]
    assert "Load PETG here" in empty["action"]


def test_the_wrong_material_family_is_a_change_and_names_both_sides(multi):
    facts = gcode.read_facts(multi)
    wrong = loaded_four(**{"1": {"color": "#00FF00", "material": "PLA Silk"}})
    plan = material_plan.plan(facts["slots"], wrong, facts["tools_used"])
    slot = next(s for s in plan["slots"] if s["tool"] == 1)
    assert slot["state"] == "wrong_material"
    assert "PETG" in slot["detail"] and "PLA Silk" in slot["detail"]


def test_matte_and_silk_are_not_reported_as_the_wrong_material(multi):
    facts = gcode.read_facts(multi)
    plan = material_plan.plan(facts["slots"], loaded_four(), facts["tools_used"])
    assert plan["to_change"] == []
    assert 0 in plan["ready"]


def test_a_noticeably_different_colour_is_advisory_not_a_change(multi):
    facts = gcode.read_facts(multi)
    swapped = loaded_four(**{"0": {"color": "#000000", "material": "PLA"}})
    plan = material_plan.plan(facts["slots"], swapped, facts["tools_used"])
    slot = next(s for s in plan["slots"] if s["tool"] == 0)
    assert slot["state"] == "different_colour"
    assert 0 not in plan["to_change"]
    assert "Fine if you meant" in slot["action"]


def test_close_colours_do_not_nag():
    assert material_plan.colour_distance("#FFFFFF", "#C0C0C0") < material_plan.NOTICEABLE
    assert material_plan.colour_distance("#000000", "#FFFFFF") > material_plan.NOTICEABLE
    assert material_plan.colour_distance(None, "#FFFFFF") is None


def test_no_printer_means_unknown_not_a_shopping_list(multi):
    facts = gcode.read_facts(multi)
    plan = material_plan.plan(facts["slots"], None, facts["tools_used"])
    assert plan["printer_known"] is False
    assert all(s["state"] in ("unknown", "unused") for s in plan["slots"])
    assert ("Connect your printer" in plan["summary"]
            or "Connect your printer" in plan["slots"][0]["action"])


# --- ready to send ----------------------------------------------------------

def printer(**over):
    base = {
        "reachable": True, "toolhead_count": 4,
        "bed_mm": {"x": 271, "y": 335}, "print_state": "standby",
        "loaded_filaments": loaded_four(),
        "klipper_objects": ["gcode", "print_stats", "exclude_object"],
    }
    base.update(over)
    return base


def test_an_empty_slot_is_a_blocker_not_a_warning(multi):
    facts = gcode.read_facts(multi)
    report = send_check.evaluate(facts, printer(loaded_filaments=loaded_four(**{"1": None})))
    assert report["verdict"] == send_check.BLOCKER
    assert any("empty" in i["title"].lower() for i in report["items"] if i["kind"] == send_check.BLOCKER)


def test_a_colour_difference_is_a_warning_and_never_blocks(multi):
    facts = gcode.read_facts(multi)
    swapped = loaded_four(**{"0": {"color": "#000000", "material": "PLA"}})
    report = send_check.evaluate(facts, printer(loaded_filaments=swapped))
    assert report["verdict"] == send_check.WARNING
    assert report["counts"]["blocker"] == 0


def test_the_nozzle_stays_unknown_and_is_never_promoted(multi):
    facts = gcode.read_facts(multi)
    report = send_check.evaluate(facts, printer())
    unknown = [i for i in report["items"] if i["kind"] == send_check.UNKNOWN]
    assert any("nozzle" in i["title"].lower() for i in unknown)
    assert not any("nozzle" in i["title"].lower()
                   for i in report["items"] if i["kind"] == send_check.BLOCKER)


def test_unreported_storage_is_unknown_not_a_pass(multi):
    facts = gcode.read_facts(multi)
    report = send_check.evaluate(facts, printer())
    storage = next((i for i in report["items"] if "room" in i["title"].lower()
                    or "space" in i["title"].lower()), None)
    assert storage is not None and storage["kind"] == send_check.UNKNOWN


def test_a_pause_is_surfaced_before_the_user_walks_away(multi):
    facts = gcode.read_facts(multi)
    timeline = print_plan.scan(multi)
    report = send_check.evaluate(facts, printer(), timeline=timeline)
    assert any("pauses" in i["title"].lower() for i in report["items"])


def test_no_printer_leaves_everything_unknown_and_blocks_nothing(multi):
    facts = gcode.read_facts(multi)
    report = send_check.evaluate(facts, {"reachable": False})
    assert report["counts"]["blocker"] == 0
    assert report["verdict"] == send_check.UNKNOWN
    assert any("No printer" in i["title"] for i in report["items"])


def test_the_send_report_never_promises_a_successful_print(multi):
    facts = gcode.read_facts(multi)
    report = send_check.evaluate(facts, printer())
    text = (report["headline"] + report["disclaimer"]).lower()
    for promise in ("will print", "guaranteed", "100%", "safe to print"):
        assert promise not in text


def test_an_unreadable_job_cannot_be_reported_as_ready(tmp_path):
    report = send_check.evaluate({"available": False, "error": "nope"}, printer())
    assert report["available"] is False
    assert report["verdict"] != send_check.READY


# --- upload confirmation (the metadata race) --------------------------------

def test_an_accepted_upload_is_not_a_finished_upload(monkeypatch):
    """Moonraker parses metadata asynchronously. Treating the POST as completion
    is how a tool starts a job the printer cannot describe yet — the failure the
    U1 Toolkit hit, and one Studio would have hit too."""
    from snapstudio_core import moonraker

    answers = [
        None,                                        # not listed yet
        {"size": 350527},                            # listed, not parsed
        {"size": 350527, "estimated_time": 391, "layer_count": 45},   # parsed
    ]

    def fake_get(host, port, path, timeout):
        assert "metadata" in path
        value = answers.pop(0) if answers else answers
        return {"result": value} if value is not None else {}

    monkeypatch.setattr(moonraker, "_get", fake_get)
    monkeypatch.setattr(moonraker.time, "sleep", lambda *_: None)
    state = moonraker.confirm_upload("printer.local", "job.gcode", expected_size=350527,
                                     attempts=5, pause=0)
    assert state["ok"] is True
    assert state["metadata_ready"] is True
    assert state["size_matches"] is True


def test_a_file_the_printer_never_lists_is_not_confirmed(monkeypatch):
    from snapstudio_core import moonraker

    monkeypatch.setattr(moonraker, "_get", lambda *a, **k: {})
    monkeypatch.setattr(moonraker.time, "sleep", lambda *_: None)
    state = moonraker.confirm_upload("printer.local", "job.gcode", attempts=2, pause=0)
    assert state["ok"] is False
    assert state["present"] is False
    assert "may not have completed" in state["detail"]


def test_a_same_named_file_of_a_different_size_is_caught(monkeypatch):
    """The old job of the same name is still there — a real failure mode when a
    slicer re-exports with the same filename."""
    from snapstudio_core import moonraker

    monkeypatch.setattr(moonraker, "_get", lambda *a, **k: {
        "result": {"size": 999, "estimated_time": 12, "layer_count": 3}})
    monkeypatch.setattr(moonraker.time, "sleep", lambda *_: None)
    state = moonraker.confirm_upload("printer.local", "job.gcode", expected_size=350527,
                                     attempts=2, pause=0)
    assert state["ok"] is False
    assert state["size_matches"] is False
    assert "different size" in state["detail"]


def test_studio_asks_the_printer_to_rescan_before_giving_up(monkeypatch):
    from snapstudio_core import moonraker

    scanned = []
    monkeypatch.setattr(moonraker, "_get", lambda *a, **k: {"result": {"size": 1}})
    monkeypatch.setattr(moonraker, "_post",
                        lambda *a, **k: scanned.append(a) or {"result": "ok"})
    monkeypatch.setattr(moonraker.time, "sleep", lambda *_: None)
    state = moonraker.confirm_upload("printer.local", "job.gcode", attempts=4, pause=0)
    assert state["rescanned"] is True
    assert scanned, "the metascan endpoint was never called"
    assert state["ok"] is False        # still not parsed, and still not claimed
