"""Trying to make the folder watcher offer a file that is not a finished job.

The watcher exists so that a sliced job comes back to Studio on its own. Every
failure here has the same shape and the same cost: Studio picks up a file that is
not what it looks like, and every check downstream describes something that is not
going to happen. Offering nothing is always better than offering the wrong thing.

The attacks are the ones a real export folder produces: files still being written,
files written slowly, a job overwritten in place, two exports finishing at once, a
project renamed to `.gcode`, a network share that goes away mid-poll, and names
with every character Windows allows in one.
"""
from __future__ import annotations

import os
import time
import zipfile

import pytest

from snapstudio_core import watch_folder

COMPLETE = """\
; HEADER_BLOCK_START
; generated by Snapmaker Orca 2.3.5 on 2026-08-23 at 10:00:00
; total layer number: 6
; HEADER_BLOCK_END
PRINT_START
; printing object widget id:0 copy 0
G1 X10 Y10 E1
PRINT_END

; filament used [g] = 4.00
; total filament used [g] = 4.00
; estimated printing time (normal mode) = 41m 12s
; CONFIG_BLOCK_START
; filament_type = PLA
; printer_model = Snapmaker U1
; CONFIG_BLOCK_END
"""

#: What Snapmaker Orca has already written a few hundred kilobytes in: the header,
#: the start macro and the summary comments. Everything that used to be treated as
#: proof of a finished file is in here, and the file is not finished.
PART_WAY = """\
; HEADER_BLOCK_START
; generated by Snapmaker Orca 2.3.5 on 2026-08-23 at 10:00:00
; total layer number: 600
; HEADER_BLOCK_END
PRINT_START
; estimated printing time (normal mode) = 9h 12m
; total filament used [g] = 812.00
; printing object widget id:0 copy 0
G1 X10 Y10 E1
G1 X10 Y1
"""


@pytest.fixture(autouse=True)
def _instant(monkeypatch):
    monkeypatch.setattr(watch_folder, "SETTLE_SECONDS", 0)
    watch_folder.forget()
    yield
    watch_folder.forget()


def write(folder, name, text=COMPLETE):
    target = folder / name
    target.write_text(text, encoding="utf-8")
    return target


def state_of(folder, name):
    found = watch_folder.scan(folder)
    for candidate in found["candidates"]:
        if candidate["name"] == name:
            return candidate
    return None


# --- files that are not finished ---------------------------------------------

def test_a_file_that_stops_part_way_is_not_offered(tmp_path):
    """The attack the previous completion check failed: Orca writes "estimated
    printing time" and "total filament used" into the first few hundred kilobytes
    of a job, so a file cut off early contains both and is still not a job."""
    write(tmp_path, "partial.gcode", PART_WAY)
    candidate = state_of(tmp_path, "partial.gcode")
    assert candidate["complete"] is False
    assert "end of the file" in candidate["state"]


def test_a_zero_byte_file_that_later_grows_is_only_offered_when_it_ends(tmp_path):
    target = tmp_path / "growing.gcode"
    target.write_bytes(b"")
    assert state_of(tmp_path, "growing.gcode")["complete"] is False
    target.write_text(PART_WAY, encoding="utf-8")
    assert state_of(tmp_path, "growing.gcode")["complete"] is False
    target.write_text(COMPLETE, encoding="utf-8")
    assert state_of(tmp_path, "growing.gcode")["complete"] is True


def test_a_file_still_growing_is_not_offered_however_long_it_pauses(tmp_path, monkeypatch):
    """Two seconds of quiet is not the end of a file. A slicer that stalls, a
    network share that buffers, an antivirus scan — all produce the same pause."""
    monkeypatch.setattr(watch_folder, "SETTLE_SECONDS", 0)
    target = tmp_path / "slow.gcode"
    target.write_text(PART_WAY, encoding="utf-8")
    for _ in range(3):
        assert state_of(tmp_path, "slow.gcode")["complete"] is False


def test_a_freshly_appeared_file_settles_on_a_later_poll(tmp_path, monkeypatch):
    """With a real settle window, a file that has only just been written is
    reported as still being written and becomes available on the next poll —
    without the request ever blocking."""
    monkeypatch.setattr(watch_folder, "SETTLE_SECONDS", 30)
    target = write(tmp_path, "fresh.gcode")
    started = time.time()
    assert state_of(tmp_path, "fresh.gcode")["complete"] is False
    assert time.time() - started < 1.0          # it did not sleep

    older = time.time() - 60
    os.utime(target, (older, older))
    assert state_of(tmp_path, "fresh.gcode")["complete"] is True


def test_a_scan_of_a_full_folder_does_not_block(tmp_path, monkeypatch):
    """Twelve candidates once cost twelve settle windows — twenty-four seconds on
    a poll the app repeats every five."""
    monkeypatch.setattr(watch_folder, "SETTLE_SECONDS", 30)
    for index in range(12):
        write(tmp_path, f"job{index}.gcode")
    started = time.time()
    watch_folder.scan(tmp_path)
    assert time.time() - started < 2.0


def test_a_file_truncated_after_looking_complete_is_withdrawn(tmp_path):
    target = write(tmp_path, "job.gcode")
    assert state_of(tmp_path, "job.gcode")["complete"] is True
    target.write_text(PART_WAY, encoding="utf-8")
    assert state_of(tmp_path, "job.gcode")["complete"] is False


def test_a_malformed_last_line_without_a_terminator_is_not_complete(tmp_path):
    write(tmp_path, "junk.gcode", COMPLETE.replace("; CONFIG_BLOCK_END", "; CONFIG_BLOC")
          + "\x00\xff garbage")
    assert state_of(tmp_path, "junk.gcode")["complete"] is False


# --- files that are not jobs --------------------------------------------------

def test_a_project_renamed_to_gcode_is_named_not_offered(tmp_path):
    target = tmp_path / "project.gcode"
    with zipfile.ZipFile(target, "w") as archive:
        archive.writestr("3D/3dmodel.model", "<model/>")
    candidate = state_of(tmp_path, "project.gcode")
    assert candidate["complete"] is False
    assert "project file" in candidate["state"]


def test_binary_noise_that_happens_to_contain_gcode_is_not_complete(tmp_path):
    (tmp_path / "noise.gcode").write_bytes(b"\x89PNG\r\n" + b"G1 X1 Y1 E1 " * 500)
    assert state_of(tmp_path, "noise.gcode")["complete"] is False


def test_a_double_extension_is_not_treated_as_gcode(tmp_path):
    write(tmp_path, "model.gcode.3mf")
    assert state_of(tmp_path, "model.gcode.3mf") is None


def test_an_uppercase_extension_is_still_gcode(tmp_path):
    write(tmp_path, "JOB.GCODE")
    assert state_of(tmp_path, "JOB.GCODE")["complete"] is True


def test_a_slicer_temp_file_becomes_a_candidate_only_when_renamed(tmp_path):
    temporary = tmp_path / "job.gcode.tmp"
    temporary.write_text(COMPLETE, encoding="utf-8")
    assert not watch_folder.scan(tmp_path)["candidates"]
    temporary.rename(tmp_path / "job.gcode")
    assert state_of(tmp_path, "job.gcode")["complete"] is True


# --- names ---------------------------------------------------------------------

@pytest.mark.parametrize("name", [
    "Grüße & Co (v2) [final].gcode",
    "日本語のモデル.gcode",
    "spaces   and---punctuation!.gcode",
    "a" * 120 + ".gcode",
])
def test_awkward_names_are_read_like_any_other(tmp_path, name):
    write(tmp_path, name)
    candidate = state_of(tmp_path, name)
    assert candidate is not None and candidate["complete"] is True


# --- the folder itself ----------------------------------------------------------

def test_a_folder_that_disappears_mid_watch_is_an_answer(tmp_path):
    folder = tmp_path / "exports"
    folder.mkdir()
    write(folder, "job.gcode")
    assert watch_folder.scan(folder)["available"] is True
    for item in folder.iterdir():
        item.unlink()
    folder.rmdir()
    found = watch_folder.scan(folder)
    assert found["available"] is False
    assert "does not exist" in found["error"]


def test_a_file_pointed_at_instead_of_a_folder_is_refused(tmp_path):
    target = write(tmp_path, "job.gcode")
    assert watch_folder.scan(target)["available"] is False


def test_a_file_that_cannot_be_read_is_counted_not_dropped(tmp_path, monkeypatch):
    write(tmp_path, "job.gcode")
    real_stat = os.stat

    def refuse(path, *args, **kwargs):
        if str(path).endswith("job.gcode"):
            raise PermissionError(13, "Access is denied")
        return real_stat(path, *args, **kwargs)

    monkeypatch.setattr(os, "stat", refuse)
    found = watch_folder.scan(tmp_path)
    assert found["available"] is True
    assert found.get("unreadable") == 1
    assert not found["candidates"]


def test_a_file_held_open_by_another_program_is_reported_not_offered(tmp_path, monkeypatch):
    write(tmp_path, "job.gcode")
    from pathlib import Path as _Path
    real_open = _Path.open

    def refuse(self, *args, **kwargs):
        if self.name == "job.gcode" and "b" in (args[0] if args else kwargs.get("mode", "")):
            raise PermissionError(13, "The process cannot access the file")
        return real_open(self, *args, **kwargs)

    monkeypatch.setattr(_Path, "open", refuse)
    candidate = state_of(tmp_path, "job.gcode")
    assert candidate["complete"] is False
    assert "holding this file open" in candidate["state"]


# --- more than one job ----------------------------------------------------------

def test_two_exports_finishing_together_are_both_offered(tmp_path):
    write(tmp_path, "one.gcode")
    write(tmp_path, "two.gcode")
    names = {c["name"]: c["complete"] for c in watch_folder.scan(tmp_path)["candidates"]}
    assert names == {"one.gcode": True, "two.gcode": True}


def test_the_same_name_written_twice_is_re_read_not_remembered(tmp_path):
    """Re-slicing to the same filename is normal. Serving the first read of it
    afterwards would describe a job that no longer exists."""
    target = write(tmp_path, "job.gcode")
    first = state_of(tmp_path, "job.gcode")
    assert first["complete"] is True

    target.write_text(COMPLETE.replace("widget", "different widget")
                      .replace("; filament used [g] = 4.00", "; filament used [g] = 91.00"),
                      encoding="utf-8")
    second = state_of(tmp_path, "job.gcode")
    assert second["complete"] is True
    assert second["size_bytes"] != first["size_bytes"]


def test_only_the_newest_jobs_are_considered(tmp_path, monkeypatch):
    monkeypatch.setattr(watch_folder, "MAX_CANDIDATES", 3)
    for index in range(6):
        target = write(tmp_path, f"job{index}.gcode")
        stamp = time.time() - (index * 600)
        os.utime(target, (stamp, stamp))
    names = [c["name"] for c in watch_folder.scan(tmp_path)["candidates"]]
    assert names == ["job0.gcode", "job1.gcode", "job2.gcode"]


def test_what_the_watcher_remembers_is_bounded(tmp_path, monkeypatch):
    monkeypatch.setattr(watch_folder, "MAX_REMEMBERED", 4)
    monkeypatch.setattr(watch_folder, "MAX_CANDIDATES", 50)
    for index in range(20):
        write(tmp_path, f"job{index}.gcode")
    watch_folder.scan(tmp_path)
    assert len(watch_folder._OBSERVED) <= 4
