"""Changing the world between the check and the send.

Everything Studio says before an upload describes one moment: this job, this
printer, these spools. Then a person reads it, walks to the machine, comes back and
presses send. In between, a slot can be emptied, a spool swapped, another print
started, the firmware restarted, or the job re-sliced to the same filename — and
none of that changes a single pixel of the answer already on screen.

These tests change exactly those things between the check and the send, and require
that Studio notices rather than uploading on the strength of a stale answer. The
second half does the same for the upload itself: an accepted POST is not a file on
a printer, and "upload failed" is four different situations with four different
things to do about them.
"""
from __future__ import annotations

import urllib.error

import pytest

from snapstudio_api import service
from snapstudio_core import moonraker, send_state

JOB = """\
; HEADER_BLOCK_START
; generated by Snapmaker Orca 2.3.5 on 2026-08-23 at 10:00:00
; total layer number: 6
; HEADER_BLOCK_END
PRINT_START
; printing object bracket id:0 copy 0
G1 X10 Y10 E1
PRINT_END
; filament used [g] = 40.00
; total filament used [g] = 40.00
; total layers count = 6
; estimated printing time (normal mode) = 41m 12s
; CONFIG_BLOCK_START
; filament_type = PLA
; filament_colour = #2D9E59
; nozzle_diameter = 0.4
; printer_model = Snapmaker U1
; CONFIG_BLOCK_END
"""


@pytest.fixture
def job(tmp_path):
    target = tmp_path / "bracket.gcode"
    target.write_text(JOB, encoding="utf-8")
    return target


def printer(*, loaded=(("PLA", "#2D9E59"),), state="ready", tools=1,
            objects=("gcode_move", "toolhead", "exclude_object")):
    return {
        "reachable": True, "host": "printer.local", "port": 7125,
        "print_state": state, "toolhead_count": tools,
        "klipper_objects": list(objects),
        "loaded_filaments": [None if slot is None else
                             {"material": slot[0], "color": slot[1]} for slot in loaded],
        "observed_at": 1_000_000.0,
    }


@pytest.fixture
def world(monkeypatch):
    """A printer Studio can read, whose state the test can change."""
    current = {"facts": printer()}
    monkeypatch.setattr(service, "printer_facts",
                        lambda host=None, port=7125: dict(current["facts"]))
    return current


def check(job, **kwargs):
    return service.send_check(str(job), host="printer.local", **kwargs)


def upload(job, expect, uploaded):
    def fake_upload(host, path, port=7125, timeout=60.0):
        uploaded.append(path)
        return {"ok": True, "action": "upload", "filename": "bracket.gcode",
                "path": "bracket.gcode", "size": 100}

    return fake_upload


# --- what the check rests on ---------------------------------------------------

def test_a_check_records_what_it_looked_at(job, world):
    result = check(job)
    assert result["state"]["token"]
    assert set(result["state"]["hashes"]) == {"job", "printer", "materials", "provenance"}


def test_the_same_world_produces_the_same_fingerprint(job, world):
    assert check(job)["state"]["token"] == check(job)["state"]["token"]


def test_every_live_fact_says_when_it_was_read(job, world):
    """A five-minute-old spool state must not be able to pass for a live one."""
    assert check(job)["printer"]["observed_at"] == 1_000_000.0


# --- the world moving between check and send ------------------------------------

@pytest.mark.parametrize("change,part", [
    ({"loaded_filaments": [None]}, "materials"),
    ({"loaded_filaments": [{"material": "PETG", "color": "#000000"}]}, "materials"),
    ({"print_state": "printing"}, "printer"),
    ({"reachable": False}, "printer"),
    ({"toolhead_count": 4}, "printer"),
    ({"klipper_objects": ["gcode_move", "toolhead"]}, "printer"),
])
def test_a_printer_that_changed_stops_the_send(job, world, monkeypatch, change, part):
    before = check(job)["state"]
    world["facts"] = {**world["facts"], **change}

    sent = []
    monkeypatch.setattr(moonraker, "upload_gcode", upload(job, before, sent))
    result = service.printer_upload_gcode("printer.local", str(job), expect_state=before)

    assert result["ok"] is False
    assert result["state"] == "changed"
    assert result["uploaded"] is False
    assert sent == []
    assert [item["part"] for item in result["changed"]] == [part]
    assert result["check"]                 # the fresh answer comes back with the refusal


def test_a_job_re_sliced_to_the_same_name_stops_the_send(job, world, monkeypatch):
    """The file the user checked and the file on disk are no longer the same file,
    and nothing about the name says so."""
    before = check(job)["state"]
    job.write_text(JOB.replace("bracket", "something else")
                      .replace("40.00", "812.00"), encoding="utf-8")

    sent = []
    monkeypatch.setattr(moonraker, "upload_gcode", upload(job, before, sent))
    result = service.printer_upload_gcode("printer.local", str(job), expect_state=before)
    assert result["state"] == "changed"
    assert "job" in [item["part"] for item in result["changed"]]
    assert sent == []


def test_a_send_goes_ahead_when_nothing_moved(job, world, monkeypatch):
    before = check(job)["state"]
    sent = []
    monkeypatch.setattr(moonraker, "upload_gcode", upload(job, before, sent))
    monkeypatch.setattr(moonraker, "confirm_upload",
                        lambda *a, **k: {"present": True, "metadata_ready": True,
                                         "size_matches": True, "fresh": True, "ok": True,
                                         "detail": "ready"})
    result = service.printer_upload_gcode("printer.local", str(job), expect_state=before)
    assert result["ok"] is True
    assert result["state"] == "verified"
    assert sent == [str(job)]


def test_a_send_without_a_prior_check_still_works(job, world, monkeypatch):
    """Not every path through the app has a check to compare against, and this must
    not become a reason an upload cannot happen at all."""
    sent = []
    monkeypatch.setattr(moonraker, "upload_gcode", upload(job, None, sent))
    monkeypatch.setattr(moonraker, "confirm_upload",
                        lambda *a, **k: {"present": True, "metadata_ready": True,
                                         "size_matches": True, "fresh": True, "ok": True,
                                         "detail": "ready"})
    result = service.printer_upload_gcode("printer.local", str(job))
    assert result["ok"] is True and sent == [str(job)]


def test_what_changed_is_said_in_words(job, world):
    before = check(job)["state"]
    world["facts"] = {**world["facts"], "loaded_filaments": [None]}
    after = check(job)["state"]
    moved = send_state.changes(before, after)
    assert send_state.describe(moved).startswith("What is loaded in the slots changed")
    assert "no longer describe" in send_state.describe(moved)


# --- the upload itself ----------------------------------------------------------

def confirming(**over):
    base = {"present": True, "metadata_ready": True, "size_matches": True, "fresh": True,
            "attempts": 1, "rescanned": False, "filename": "bracket.gcode"}
    base.update(over)
    base["ok"] = bool(base["present"] and base["metadata_ready"]
                      and base["size_matches"] is not False and base["fresh"] is not False)
    base["detail"] = moonraker._upload_detail(base)
    return lambda *a, **k: base


def test_a_connection_that_drops_is_not_a_refusal(job, monkeypatch):
    def drop(host, path, port=7125, timeout=60.0):
        raise urllib.error.URLError("connection reset")
    monkeypatch.setattr(moonraker, "upload_gcode", drop)
    result = service.printer_upload_gcode("printer.local", str(job))
    assert result["state"] == "not_accepted"
    assert result["uploaded"] is False
    assert "Nothing on the printer has been started" in result["detail"]


@pytest.mark.parametrize("status,expected", [
    (401, "not permitted"),
    (404, "does not offer file uploads"),
    (409, "busy"),
    (413, "too large"),
    (500, "answered the upload with an error"),
])
def test_a_printer_that_answers_with_an_error_says_which(job, monkeypatch, status, expected):
    def refuse(host, port, path, timeout, body=None, content_type=None):
        raise urllib.error.HTTPError(f"http://{host}{path}", status, "no", {}, None)
    monkeypatch.setattr(moonraker, "_post", refuse)
    result = service.printer_upload_gcode("printer.local", str(job))
    assert result["state"] == "refused_by_printer"
    assert result["status"] == status
    assert expected in result["detail"]
    assert result["uploaded"] is False


def test_bytes_accepted_but_never_listed_is_its_own_answer(job, monkeypatch):
    monkeypatch.setattr(moonraker, "upload_gcode", upload(job, None, []))
    monkeypatch.setattr(moonraker, "confirm_upload", confirming(present=False,
                                                                metadata_ready=False))
    result = service.printer_upload_gcode("printer.local", str(job))
    assert result["state"] == "not_listed"
    assert result["ok"] is False


def test_bytes_accepted_and_still_being_read_is_not_a_failure(job, monkeypatch):
    """The Moonraker metadata race: the file is there and the printer has not
    finished reading it. Starting a print now is what goes wrong."""
    monkeypatch.setattr(moonraker, "upload_gcode", upload(job, None, []))
    monkeypatch.setattr(moonraker, "confirm_upload", confirming(metadata_ready=False))
    result = service.printer_upload_gcode("printer.local", str(job))
    assert result["state"] == "pending_verification"
    assert "not finished reading" in result["confirmation"]["detail"]


def test_a_file_of_the_same_name_and_a_different_size_is_a_mismatch(job, monkeypatch):
    monkeypatch.setattr(moonraker, "upload_gcode", upload(job, None, []))
    monkeypatch.setattr(moonraker, "confirm_upload", confirming(size_matches=False))
    result = service.printer_upload_gcode("printer.local", str(job))
    assert result["state"] == "mismatch"


def test_stale_metadata_for_an_overwritten_name_is_caught(job, monkeypatch):
    """Same name, same size, and the printer is still describing the file this one
    replaced — so its estimate and thumbnail belong to the previous job."""
    monkeypatch.setattr(moonraker, "upload_gcode", upload(job, None, []))
    monkeypatch.setattr(moonraker, "confirm_upload", confirming(fresh=False))
    result = service.printer_upload_gcode("printer.local", str(job))
    assert result["state"] == "mismatch"
    assert "older file of this name" in result["confirmation"]["detail"]


def test_a_confirmation_that_itself_fails_is_unknown_not_success(job, monkeypatch):
    monkeypatch.setattr(moonraker, "upload_gcode", upload(job, None, []))

    def boom(*a, **k):
        raise OSError("printer went away")
    monkeypatch.setattr(moonraker, "confirm_upload", boom)
    result = service.printer_upload_gcode("printer.local", str(job))
    assert result["state"] == "unknown"
    assert result["ok"] is False


def test_only_sliced_files_can_be_uploaded(tmp_path):
    project = tmp_path / "model.3mf"
    project.write_bytes(b"PK\x03\x04")
    with pytest.raises(ValueError):
        moonraker.upload_gcode("printer.local", str(project))


# --- the confirmation reads the printer's own answer ----------------------------

def test_confirmation_polls_metadata_and_scans_once(monkeypatch):
    calls = {"get": 0, "scan": 0}

    def fake_get(host, port, path, timeout):
        calls["get"] += 1
        if calls["get"] < 3:
            raise urllib.error.HTTPError(path, 404, "not found", {}, None)
        return {"result": {"size": 100, "layer_count": 6, "modified": 9e9}}

    def fake_post(host, port, path, timeout, body=None, content_type=None):
        calls["scan"] += 1
        return {"result": "ok"}

    monkeypatch.setattr(moonraker, "_get", fake_get)
    monkeypatch.setattr(moonraker, "_post", fake_post)
    monkeypatch.setattr(moonraker.time, "sleep", lambda _s: None)
    state = moonraker.confirm_upload("printer.local", "bracket.gcode", expected_size=100,
                                     attempts=6, pause=0)
    assert state["ok"] is True
    assert state["size_matches"] is True
    assert calls["scan"] <= 1                  # asked once, politely
