"""The sliced-G-code reader.

The fixtures here are modelled line-for-line on real Snapmaker Orca output taken
from a physical U1 — the same header, summary and configuration conventions,
trimmed to a size a test can hold. Real jobs from that machine reach 263 MB, so
one test builds a deliberately oversized file and proves the reader never loads
the middle of it.
"""
from __future__ import annotations

import textwrap

import pytest

from snapstudio_core import gcode

HEADER = """\
; HEADER_BLOCK_START
; generated by Snapmaker Orca 2.3.4 on 2026-07-01 at 13:49:33
; total layer number: 45
; filament_density: 1.24,1.24,1.24,1.24
; filament_diameter: 1.75,1.75,1.75,1.75
; max_z_height: 9.05
; HEADER_BLOCK_END

; THUMBNAIL_BLOCK_START
; thumbnail begin 48x48 1712
; iVBORw0KGgoAAAANSUhEUg
; thumbnail end
; THUMBNAIL_BLOCK_END

; EXECUTABLE_BLOCK_START
M73 P0 R6
PRINT_START
SET_PRINT_STATS_INFO TOTAL_LAYER=45 CURRENT_LAYER=0
TIMELAPSE_START
DEFECT_DETECTION_START
G1 X10 Y10 Z0.25 F1200
T1
G1 X20 Y20 E1.0
PRINT_END
; EXECUTABLE_BLOCK_END
"""

SUMMARY = """\

; filament used [mm] = 0.00, 304.94, 0.00, 0.00
; filament used [cm3] = 0.00, 0.73, 0.00, 0.00
; filament used [g] = 0.00, 0.91, 0.00, 0.00
; filament cost = 0.00, 0.09, 0.00, 0.00
; total filament used [g] = 0.91
; total filament cost = 0.09
; total layers count = 45
; estimated printing time (normal mode) = 6m 31s
; estimated first layer printing time (normal mode) = 19s
"""

CONFIG = """\

; CONFIG_BLOCK_START
; enable_prime_tower = 0
; filament_settings_id = "Snapmaker PLA";"Snapmaker PLA";"Snapmaker PLA";"Snapmaker PLA"
; filament_type = PLA;PLA;PLA;PLA
; filament_vendor = Snapmaker;Snapmaker;Snapmaker;Snapmaker
; flush_volumes_vector = 140,140,140,140
; layer_height = 0.2
; nozzle_diameter = 0.4,0.4,0.4,0.4
; printable_area = 0.5x1,270.5x1,270.5x271,0.5x271
; printer_model = Snapmaker U1
; first_layer_bed_temperature = 0
; first_layer_temperature = 220
; first_layer_height = 0.250
; CONFIG_BLOCK_END
"""


def write(tmp_path, *parts, name="job.gcode"):
    target = tmp_path / name
    target.write_text("".join(parts), encoding="utf-8")
    return target


@pytest.fixture()
def real_shaped(tmp_path):
    return write(tmp_path, HEADER, SUMMARY, CONFIG)


# --- what it reads ----------------------------------------------------------

def test_reads_the_slicer_and_the_machine(real_shaped):
    facts = gcode.read_facts(real_shaped)
    assert facts["available"] is True
    assert facts["slicer"] == "Snapmaker Orca"
    assert facts["slicer_version"] == "2.3.4"
    assert facts["sliced_on"] == "2026-07-01"
    assert facts["printer_model"] == "Snapmaker U1"


def test_reads_the_bed_from_the_printable_area(real_shaped):
    facts = gcode.read_facts(real_shaped)
    assert facts["bed_mm"] == {"x": 270.0, "y": 270.0}


def test_reads_the_job_shape(real_shaped):
    facts = gcode.read_facts(real_shaped)
    assert facts["layer_count"] == 45
    assert facts["max_z_mm"] == 9.05
    assert facts["layer_height_mm"] == 0.2
    assert facts["first_layer_height_mm"] == 0.25
    assert facts["estimated_seconds"] == 391      # 6m 31s
    assert facts["first_layer_seconds"] == 19


def test_only_slots_with_filament_count_as_used(real_shaped):
    """The real find this came from: a job that prints entirely from slot 2."""
    facts = gcode.read_facts(real_shaped)
    assert facts["tools_used"] == [1]
    used = [s for s in facts["slots"] if s["used"]]
    assert len(used) == 1
    assert used[0]["grams"] == 0.91
    assert used[0]["type"] == "PLA"
    assert used[0]["name"] == "Snapmaker PLA"


def test_reads_the_firmware_markers_the_u1_actually_emits(real_shaped):
    facts = gcode.read_facts(real_shaped)
    assert facts["markers"]["PRINT_START"] is True
    assert facts["markers"]["SET_PRINT_STATS_INFO"] is True
    assert facts["has_thumbnail"] is True


# --- what it refuses to say -------------------------------------------------

def test_a_single_tool_job_reports_no_purge(real_shaped):
    facts = gcode.read_facts(real_shaped)
    assert facts["purge"]["expected"] is False
    assert facts["purge"]["separable"] is False


def test_a_multi_tool_job_says_purge_exists_but_is_not_separable(tmp_path):
    """The honesty rule for cost: Orca reports one total per slot and does not
    break out purge, so Studio must not invent a split."""
    summary = SUMMARY.replace(
        "; filament used [g] = 0.00, 0.91, 0.00, 0.00",
        "; filament used [g] = 2.00, 0.91, 1.10, 0.00")
    facts = gcode.read_facts(write(tmp_path, HEADER, summary, CONFIG))
    assert facts["tools_used"] == [0, 1, 2]
    assert facts["purge"]["expected"] is True
    assert facts["purge"]["separable"] is False
    assert "not separate" in facts["purge"]["detail"]


def test_missing_facts_are_unknown_not_invented(tmp_path):
    bare = "; EXECUTABLE_BLOCK_START\nG1 X1 Y1\n; EXECUTABLE_BLOCK_END\n"
    facts = gcode.read_facts(write(tmp_path, bare))
    assert facts["available"] is True
    assert facts["printer_model"] is None
    assert facts["layer_count"] is None
    assert facts["estimated_seconds"] is None
    assert facts["tools_used"] is None
    assert "which slicer produced this file" in facts["unknowns"]


def test_object_names_are_never_carried_out_of_the_file(tmp_path):
    """EXCLUDE_OBJECT_DEFINE lines carry model names, which are the user's
    business. The count is what the checks need."""
    body = HEADER.replace("PRINT_START",
                          'PRINT_START\nEXCLUDE_OBJECT_DEFINE NAME=SecretProject_v3 CENTER=10,10\n'
                          'EXCLUDE_OBJECT_DEFINE NAME=AlsoPrivate CENTER=40,40')
    facts = gcode.read_facts(write(tmp_path, body, SUMMARY, CONFIG))
    assert facts["exclude_object"]["present"] is True
    assert facts["exclude_object"]["objects"] == 2
    assert "SecretProject_v3" not in repr(facts)
    assert "AlsoPrivate" not in repr(facts)


# --- files that are not what they claim -------------------------------------

def test_a_missing_file_is_an_answer_not_a_crash(tmp_path):
    facts = gcode.read_facts(tmp_path / "nope.gcode")
    assert facts["available"] is False
    assert "does not exist" in facts["error"]


def test_a_non_gcode_file_is_refused_clearly(tmp_path):
    target = tmp_path / "notes.gcode"
    target.write_text("this is just prose about printing\n", encoding="utf-8")
    facts = gcode.read_facts(target)
    assert facts["available"] is False
    assert "sliced G-code" in facts["error"]


# --- the size constraint ----------------------------------------------------

def test_a_huge_file_is_read_from_both_ends_and_never_in_full(tmp_path, monkeypatch):
    """Real jobs reach hundreds of megabytes. The reader must stay bounded, and
    must still find the header at the top and the summary at the bottom."""
    monkeypatch.setattr(gcode, "HEAD_BYTES", 64 * 1024)
    monkeypatch.setattr(gcode, "TAIL_BYTES", 64 * 1024)

    filler = "G1 X10 Y10 E0.1 F1200\n" * 40_000     # ~880 KB of toolpaths
    target = write(tmp_path, HEADER, filler, SUMMARY, CONFIG, name="huge.gcode")
    assert target.stat().st_size > 256 * 1024

    facts = gcode.read_facts(target)
    assert facts["available"] is True
    assert facts["read_fully"] is False
    # Found at the top:
    assert facts["slicer"] == "Snapmaker Orca"
    # Found at the bottom:
    assert facts["printer_model"] == "Snapmaker U1"
    assert facts["tools_used"] == [1]
    assert facts["estimated_seconds"] == 391


def test_the_read_window_is_configurable_by_environment(monkeypatch):
    monkeypatch.setenv("SNAPSTUDIO_GCODE_HEAD_BYTES", "12345")
    assert gcode._limit("SNAPSTUDIO_GCODE_HEAD_BYTES", 999) == 12345
    monkeypatch.setenv("SNAPSTUDIO_GCODE_HEAD_BYTES", "not-a-number")
    assert gcode._limit("SNAPSTUDIO_GCODE_HEAD_BYTES", 999) == 999


# --- other slicers ----------------------------------------------------------

def test_prusaslicer_output_is_read_where_it_overlaps(tmp_path):
    prusa = textwrap.dedent("""\
        ; generated by PrusaSlicer 2.9.0+win64 on 2026-05-02 at 11:02:31
        G1 X10 Y10 E0.2
        ; filament used [g] = 12.4
        ; estimated printing time (normal mode) = 1h 4m 12s
        ; nozzle_diameter = 0.4
        ; printer_model = MK4
        """)
    facts = gcode.read_facts(write(tmp_path, prusa, name="prusa.gcode"))
    assert facts["slicer"] == "PrusaSlicer"
    assert facts["printer_model"] == "MK4"
    assert facts["estimated_seconds"] == 3852
    assert facts["filament"]["total_g"] == 12.4


def test_summary_line_never_claims_more_than_it_read(tmp_path):
    facts = gcode.read_facts(write(tmp_path, HEADER, SUMMARY, CONFIG))
    line = gcode.summary_line(facts)
    assert "Snapmaker U1" in line and "45 layers" in line
    broken = gcode.read_facts(tmp_path / "gone.gcode")
    assert gcode.summary_line(broken) == broken["error"]
