"""Trying to make Studio claim the wrong file is the slice of your project.

The post-slice half of Studio answers questions about a job: is the right filament
loaded, will it fit, is there enough of it. Every one of those answers is wrong if
the job is not the one the user thinks it is — and confidently wrong, which is the
worst kind. So this file is written to break `provenance`, not to demonstrate it.

The cases come in three groups:

* pairs that genuinely belong together, in the awkward shapes real work produces:
  renamed, re-sliced, re-coloured, one plate of several, read only in part;
* pairs that do not belong together but look like they might — the same machine,
  the same spools, a similar name, the same object count;
* files that state almost nothing, where the only correct answer is "cannot tell".

The rule under all of it: a wrong `confirmed` is a serious defect, a wrong
`no_match` blocks legitimate work, and an honest `ambiguous` is neither.
"""
from __future__ import annotations

from pathlib import Path

from snapstudio_core import gcode, provenance

# --- building jobs -----------------------------------------------------------

HEADER = """\
; HEADER_BLOCK_START
; generated by {slicer} on 2026-08-23 at 10:00:00
; total layer number: {layers}
; max_z_height: {height}
; HEADER_BLOCK_END
; EXECUTABLE_BLOCK_START
PRINT_START
"""

CONFIG = """\
PRINT_END
; EXECUTABLE_BLOCK_END

; filament used [g] = {grams}
; total filament used [g] = 12.00
; total layers count = {layers}
; estimated printing time (normal mode) = 41m 12s

; CONFIG_BLOCK_START
; filament_type = {types}
; filament_colour = {colours}
; nozzle_diameter = {nozzles}
; printable_area = 0.5x1,270.5x1,270.5x271,0.5x271
; printer_model = {printer}
; CONFIG_BLOCK_END
"""

PRUSA = """\
; generated by PrusaSlicer 2.8.1 on 2026-08-23 at 10:00:00
M486 A{first}
G1 X10 Y10 E1
M486 A{second}
G1 X20 Y20 E2
; filament used [g] = 8.10
; estimated printing time (normal mode) = 1h 2m
; prusaslicer_config = begin
; filament_type = PLA
; nozzle_diameter = 0.4
; printer_model = MK4
; prusaslicer_config = end
"""


def job(tmp_path, name="job.gcode", *, objects=("left bracket", "right bracket"),
        colours="#FF0000;#00FF00", types="PLA;PETG", printer="Snapmaker U1",
        layers=6, height="12.4", grams="4.00, 3.00", nozzles="0.4,0.4",
        slicer="Snapmaker Orca 2.3.5", label="printing object") -> Path:
    """A job that labels its objects the way Snapmaker Orca really does."""
    body = ""
    for index, obj in enumerate(objects or ()):
        if label == "printing object":
            body += f"; printing object {obj} id:{index} copy 0\nG1 X10 Y{index} E1\n"
            body += f"; stop printing object {obj} id:{index} copy 0\n"
        elif label == "exclude":
            body += f"EXCLUDE_OBJECT_DEFINE NAME={obj.replace(' ', '_')}.stl_id_{index}_copy_0\n"
            body += "G1 X10 Y10 E1\n"
        else:
            body += "G1 X10 Y10 E1\n"
    if not objects:
        body = "G1 X10 Y10 E1\n"
    target = tmp_path / name
    target.write_text(
        HEADER.format(layers=layers, height=height, slicer=slicer) + body
        + CONFIG.format(colours=colours, printer=printer, types=types, layers=layers,
                        grams=grams, nozzles=nozzles),
        encoding="utf-8")
    return target


def project(*, objects=("left bracket", "right bracket"),
            colours=("#FF0000", "#00FF00"), types=("PLA", "PETG"),
            printer="Snapmaker U1", object_count=None) -> dict:
    """The traits Studio reads from a project, in the shape `extract` returns."""
    hashes = [gcode._digest_of([gcode._clean_name(o)]) for o in objects or ()]
    return {
        "readable": True,
        "object_name_hashes": {"value": hashes},
        "object_name_digest": {"value": gcode._digest_of(
            [gcode._clean_name(o) for o in objects or ()])},
        "filament_slots": {"value": [{"tool": index, "type": t, "color": c}
                                     for index, (t, c) in enumerate(zip(types, colours))]},
        "filament_count": {"value": len(types)},
        "target_printer": {"value": printer},
        "object_count": {"value": object_count if object_count is not None
                         else len(objects or ())},
    }


def verdict(traits, path, **names) -> str:
    return provenance.compare(traits, gcode.read_facts(path), **names)["verdict"]


# --- pairs that really do belong together ------------------------------------

def test_a_project_and_its_own_slice_are_confirmed(tmp_path):
    assert verdict(project(), job(tmp_path)) == provenance.CONFIRMED


def test_snapmaker_orcas_real_object_labels_are_read(tmp_path):
    """The label style that matters most: three jobs pulled off a real U1 had 90,
    52 and 3476 `printing object` lines between them and not one
    EXCLUDE_OBJECT_DEFINE, because object exclusion is off by default."""
    facts = gcode.read_facts(job(tmp_path))
    assert facts["objects"]["count"] == 2
    assert facts["objects"]["sources"] == ["object labels in the toolpath"]
    assert len(facts["objects"]["name_hashes"]) == 2


def test_exclusion_defines_and_printing_labels_agree(tmp_path):
    """The same objects named in either dialect must fingerprint the same, or a
    project would stop matching its own slice when a setting changed."""
    labelled = gcode.read_facts(job(tmp_path, "a.gcode"))
    excluded = gcode.read_facts(job(tmp_path, "b.gcode", label="exclude"))
    assert labelled["objects"]["name_digest"] == excluded["objects"]["name_digest"]


def test_renaming_the_project_changes_nothing(tmp_path):
    assert verdict(project(), job(tmp_path, "whatever-i-called-it.gcode"),
                   project_name="renamed.3mf", gcode_name="whatever-i-called-it.gcode") \
        == provenance.CONFIRMED


def test_renaming_the_gcode_changes_nothing(tmp_path):
    assert verdict(project(), job(tmp_path, "final_v3_REAL.gcode"),
                   project_name="bracket.3mf", gcode_name="final_v3_REAL.gcode") \
        == provenance.CONFIRMED


def test_a_reslice_in_a_different_material_is_still_the_same_project(tmp_path):
    """Changing the filament is a setup change, not a different model. Reading it
    as a different project would block a legitimate send."""
    re_sliced = job(tmp_path, types="PETG;PETG", colours="#0000FF;#0000FF")
    assert verdict(project(), re_sliced) in (provenance.CONFIRMED, provenance.LIKELY)


def test_a_reslice_after_moving_objects_is_still_the_same_project(tmp_path):
    moved = job(tmp_path, layers=9, height="18.2")
    assert verdict(project(), moved) == provenance.CONFIRMED


def test_a_reslice_after_removing_an_object_is_recognised_as_part_of_it(tmp_path):
    """Deleting one of two objects and re-slicing leaves a job that prints a
    subset. That is the project, minus something — not a stranger."""
    fewer = job(tmp_path, objects=("left bracket",))
    result = provenance.compare(project(), gcode.read_facts(fewer))
    assert result["verdict"] in (provenance.CONFIRMED, provenance.LIKELY)
    assert result["verdict"] != provenance.NO_MATCH


def test_one_plate_of_a_multi_plate_project_is_part_of_it(tmp_path):
    big = project(objects=("hull", "deck", "mast", "rudder"))
    plate = job(tmp_path, objects=("hull", "deck"))
    result = provenance.compare(big, gcode.read_facts(plate))
    assert result["verdict"] in (provenance.CONFIRMED, provenance.LIKELY)
    assert "part of the project" in result["evidence"][0]["label"]


def test_a_stale_older_slice_of_the_same_project_still_matches(tmp_path):
    """Studio cannot tell an old slice from a new one by content, and must not
    pretend to. It is the same project either way; freshness is a separate
    question, answered by the file's age."""
    assert verdict(project(), job(tmp_path, "yesterday.gcode")) == provenance.CONFIRMED


# --- pairs that do not belong together ---------------------------------------

def test_the_same_basename_with_the_wrong_job_is_not_a_match(tmp_path):
    other = job(tmp_path, "bracket.gcode", objects=("gear housing",))
    assert verdict(project(), other, project_name="bracket.3mf",
                   gcode_name="bracket.gcode") == provenance.NO_MATCH


def test_two_almost_identical_filenames_are_told_apart_by_content(tmp_path):
    mine = job(tmp_path, "bracket_v2_PLA.gcode")
    theirs = job(tmp_path, "bracket_v3_PLA.gcode", objects=("something else",))
    assert verdict(project(), mine, gcode_name="bracket_v2_PLA.gcode") == provenance.CONFIRMED
    assert verdict(project(), theirs, gcode_name="bracket_v3_PLA.gcode") == provenance.NO_MATCH


def test_an_unrelated_model_sliced_on_the_same_printer_is_not_a_match(tmp_path):
    """The case that made this rewrite necessary. Same machine, same spools, same
    materials, same colours — everything a workshop's jobs always share."""
    stranger = job(tmp_path, objects=("dragon",))
    assert verdict(project(), stranger) == provenance.NO_MATCH


def test_an_unrelated_model_with_no_object_labels_is_never_confirmed(tmp_path):
    """With object labelling off there is nothing left that identifies a model, so
    the only honest answers are "cannot tell" and "no"."""
    stranger = job(tmp_path, objects=(), label="none")
    assert verdict(project(), stranger) == provenance.AMBIGUOUS


def test_the_same_object_count_is_not_the_same_objects(tmp_path):
    two_others = job(tmp_path, objects=("front panel", "back panel"))
    assert verdict(project(), two_others) == provenance.NO_MATCH


def test_the_same_names_with_different_tool_assignments_still_match(tmp_path):
    """Re-slicing with the objects assigned to different slots is a setup change."""
    swapped = job(tmp_path, colours="#00FF00;#FF0000", types="PETG;PLA")
    assert verdict(project(), swapped) in (provenance.CONFIRMED, provenance.LIKELY)


def test_a_job_for_another_machine_with_different_objects_is_not_a_match(tmp_path):
    stranger = job(tmp_path, objects=("calibration cube",), printer="Bambu Lab X1 Carbon")
    assert verdict(project(), stranger) == provenance.NO_MATCH


# --- files that say almost nothing -------------------------------------------

def test_a_job_with_no_object_names_and_no_colours_is_unknown(tmp_path):
    bare = job(tmp_path, objects=(), colours="", types="", nozzles="", label="none")
    result = provenance.compare({"readable": True}, gcode.read_facts(bare))
    assert result["verdict"] == provenance.UNKNOWN


def test_a_job_with_minimal_metadata_is_not_promoted_by_its_filename(tmp_path):
    bare = job(tmp_path, "bracket.gcode", objects=(), colours="", types="", label="none")
    result = provenance.compare(project(), gcode.read_facts(bare),
                                project_name="bracket.3mf", gcode_name="bracket.gcode")
    assert result["verdict"] in (provenance.UNKNOWN, provenance.AMBIGUOUS)
    weights = [e["weight"] for e in result["evidence"] if e["signal"] == "file name"]
    assert not weights or max(weights) <= provenance.WEAK


def test_a_prusa_job_is_read_and_compared(tmp_path):
    target = tmp_path / "prusa.gcode"
    target.write_text(PRUSA.format(first="left bracket", second="right bracket"),
                      encoding="utf-8")
    facts = gcode.read_facts(target)
    assert facts["objects"]["count"] == 2
    assert verdict(project(printer="MK4"), target) == provenance.CONFIRMED


def test_a_prusa_job_of_something_else_is_refused(tmp_path):
    target = tmp_path / "prusa.gcode"
    target.write_text(PRUSA.format(first="whistle", second="lanyard"), encoding="utf-8")
    assert verdict(project(printer="MK4"), target) == provenance.NO_MATCH


def test_a_project_file_handed_in_as_gcode_is_named_not_matched(tmp_path):
    fake = tmp_path / "project.gcode"
    fake.write_bytes(b"PK\x03\x04" + b"G1 X1 Y1 E1 " * 400)
    result = provenance.compare(project(), gcode.read_facts(fake))
    assert result["verdict"] == provenance.UNKNOWN
    assert "project file" in result["summary"]


# --- how it explains itself ---------------------------------------------------

def test_every_piece_of_evidence_says_what_kind_it_is(tmp_path):
    result = provenance.compare(project(), gcode.read_facts(job(tmp_path)))
    assert result["evidence"]
    for item in result["evidence"]:
        assert item["kind"] in (provenance.IDENTITY, provenance.PROFILE,
                                provenance.CIRCUMSTANTIAL)
        assert item["label"] and item["detail"]


def test_the_reason_for_a_less_than_certain_answer_is_stated(tmp_path):
    bare = job(tmp_path, objects=(), label="none")
    result = provenance.compare(project(), gcode.read_facts(bare))
    assert result["verdict"] == provenance.AMBIGUOUS
    assert "identifies the model" in result["why"]


def test_no_object_name_ever_leaves_the_reader(tmp_path):
    """The names are the user's model names. Hashes are what travel."""
    import json

    secret = "grandmothers headstone rev4"
    facts = gcode.read_facts(job(tmp_path, objects=(secret,)))
    result = provenance.compare(project(objects=(secret,)), facts)
    blob = json.dumps({"facts": facts, "provenance": result})
    assert secret not in blob
    for word in secret.split():
        assert word not in blob
