class SnapStudioError(Exception): ...
class PartNotFound(SnapStudioError): ...
class PreservationError(SnapStudioError): ...
class FilamentLimitError(SnapStudioError): ...


class UnsafeArchive(SnapStudioError):
    """A 3MF that Studio refuses to open: too many entries, or it decompresses to
    more data than the reader budget allows (a zip bomb, or a corrupt file that
    looks like one). The message is safe to show a user verbatim."""
