"""Read what a sliced G-code file actually says, without reading all of it.

Studio's checks up to this point all look at the *source project*. This module
looks at the other half: the file the printer will really execute. Everything it
reports is a fact the slicer wrote down — nothing is inferred from geometry,
because by this point the geometry has already been turned into toolpaths.

Two constraints shape the whole design.

**Size.** Real jobs on a U1 reach hundreds of megabytes; the largest on the
machine this was developed against is 263 MB. Slicers put the header, thumbnail
and object definitions at the top and the summary and full configuration at the
bottom, so this reads a bounded window at each end and never the middle. A file
that is smaller than both windows is simply read once.

**Honesty.** A fact the file does not state is `None` at `unknown`. In particular
Snapmaker Orca's summary does *not* separate model filament from support or purge
filament, so this module reports what it can prove and says the rest is not
separable — it never divides a total by a guess.

Supported dialects: Snapmaker Orca, OrcaSlicer, BambuStudio (the same
HEADER_BLOCK/CONFIG_BLOCK convention) and PrusaSlicer/SuperSlicer (a different
comment convention, handled where it overlaps).
"""
from __future__ import annotations

import os
import re
from pathlib import Path

SCHEMA = "gcode/1"


def _limit(name: str, default: int) -> int:
    try:
        value = int(os.environ.get(name, ""))
    except ValueError:
        return default
    return value if value > 0 else default


#: How much of each end of the file is read. The header, thumbnail and object
#: definitions live in the first window; the summary and configuration in the last.
HEAD_BYTES = _limit("SNAPSTUDIO_GCODE_HEAD_BYTES", 4 * 1024 * 1024)
TAIL_BYTES = _limit("SNAPSTUDIO_GCODE_TAIL_BYTES", 4 * 1024 * 1024)

#: Configuration keys worth carrying. The CONFIG_BLOCK of a real job holds well
#: over a thousand entries; hoarding them all would make every report unreadable
#: and every payload enormous.
CONFIG_KEYS = (
    "printer_model", "printer_settings_id", "printable_area", "bed_shape",
    "nozzle_diameter", "filament_type", "filament_settings_id", "filament_vendor",
    "filament_density", "filament_diameter", "filament_cost", "filament_colour",
    "filament_color",
    "layer_height", "first_layer_height", "first_layer_temperature",
    "first_layer_bed_temperature", "temperature", "bed_temperature",
    "enable_prime_tower", "wipe_tower_x", "wipe_tower_y",
    "flush_volumes_vector", "flush_multiplier", "flush_into_objects",
    "flush_into_infill", "flush_into_support",
    "support_material", "enable_support", "sparse_infill_density",
    "print_settings_id", "gcode_flavor", "exclude_object",
    "curr_bed_type", "wall_loops", "brim_type", "raft_layers",
)

_HEADER_GENERATED = re.compile(
    r";\s*generated by\s+(?P<slicer>.+?)\s+(?P<version>[\d][\w.\-]*)\s+on\s+(?P<date>[\d-]+)", re.I)
_PRUSA_GENERATED = re.compile(
    r";\s*generated by\s+(?P<slicer>PrusaSlicer|SuperSlicer)\s+(?P<version>[\w.+\-]+)", re.I)
_COMMENT_KV = re.compile(r"^;\s*([A-Za-z_][A-Za-z0-9_ \[\]%]*?)\s*=\s*(.*)$")
_TOTAL_LAYERS = re.compile(r";\s*total layers? (?:count|number)\s*[:=]\s*(\d+)", re.I)
_MAX_Z = re.compile(r";\s*max_z_height\s*[:=]\s*([\d.]+)", re.I)
_TIME = re.compile(r";\s*estimated printing time \(normal mode\)\s*=\s*(.+)", re.I)
_FIRST_LAYER_TIME = re.compile(r";\s*estimated first layer printing time \(normal mode\)\s*=\s*(.+)", re.I)
_PRUSA_TIME = re.compile(r";\s*estimated printing time \(normal mode\)\s*=\s*(.+)", re.I)
_DURATION = re.compile(r"(?:(\d+)\s*d)?\s*(?:(\d+)\s*h)?\s*(?:(\d+)\s*m)?\s*(?:(\d+)\s*s)?", re.I)
_EXCLUDE_DEFINE = re.compile(r"^EXCLUDE_OBJECT_DEFINE\b(.*)$", re.M)
_OBJECT_NAME = re.compile(r"NAME=([^\s]+)")


def _read_ends(path: Path) -> tuple[str, str, int]:
    """Return (head, tail, size). The two never overlap and are never the whole
    of a large file."""
    size = path.stat().st_size
    with path.open("rb") as handle:
        if size <= HEAD_BYTES + TAIL_BYTES:
            whole = handle.read().decode("utf-8", errors="replace")
            return whole, "", size
        head = handle.read(HEAD_BYTES).decode("utf-8", errors="replace")
        handle.seek(max(0, size - TAIL_BYTES))
        tail = handle.read(TAIL_BYTES).decode("utf-8", errors="replace")
    return head, tail, size


def _floats(raw: str) -> list[float]:
    out = []
    for piece in re.split(r"[,;]", raw):
        piece = piece.strip().strip('"')
        try:
            out.append(float(piece))
        except ValueError:
            continue
    return out


def _strings(raw: str) -> list[str]:
    return [p.strip().strip('"') for p in re.split(r"[;,]", raw) if p.strip().strip('"')]


def _seconds(text: str) -> int | None:
    text = text.strip()
    match = _DURATION.fullmatch(text)
    if not match or not any(match.groups()):
        return None
    days, hours, minutes, seconds = (int(g) if g else 0 for g in match.groups())
    return ((days * 24 + hours) * 60 + minutes) * 60 + seconds


def _config(blob: str) -> dict[str, str]:
    """Pull the allow-listed configuration comments out of a blob."""
    found: dict[str, str] = {}
    for line in blob.splitlines():
        if not line.startswith(";"):
            continue
        match = _COMMENT_KV.match(line)
        if not match:
            continue
        key = match.group(1).strip()
        if key in CONFIG_KEYS:
            found[key] = match.group(2).strip()
    return found


def _usage(blob: str) -> dict:
    """Per-slot filament usage from the summary block."""
    usage: dict = {}
    for unit, key in (("mm", "filament used [mm]"), ("cm3", "filament used [cm3]"),
                      ("g", "filament used [g]"), ("cost", "filament cost")):
        match = re.search(rf";\s*{re.escape(key)}\s*=\s*(.+)", blob, re.I)
        if match:
            usage[unit] = _floats(match.group(1))
    total = re.search(r";\s*total filament used \[g\]\s*=\s*([\d.]+)", blob, re.I)
    if total:
        usage["total_g"] = float(total.group(1))
    total_cost = re.search(r";\s*total filament cost\s*=\s*([\d.]+)", blob, re.I)
    if total_cost:
        usage["total_cost"] = float(total_cost.group(1))
    # Not every slicer states a total. PrusaSlicer, for one, prints a single
    # `filament used [g]` and leaves the caller to add it up.
    if "total_g" not in usage and usage.get("g"):
        usage["total_g"] = round(sum(usage["g"]), 3)
    return usage


def read_facts(path: str | Path) -> dict:
    """Read a sliced G-code file and report only what it states.

    Never raises for a file that is merely unusual: an unreadable or non-G-code
    file comes back with ``available: False`` and a reason, because "Studio could
    not read this" is a useful answer and a traceback is not.
    """
    target = Path(path)
    facts: dict = {
        "schema_version": SCHEMA,
        "available": False,
        "file": target.name,
        "unknowns": [],
    }
    if not target.exists() or not target.is_file():
        facts["error"] = "that file does not exist"
        return facts

    # A 3MF is a ZIP, and its compressed bytes decode into enough noise to
    # contain "G1 " by accident. Handing Studio a project file instead of a
    # sliced job is the likeliest mistake here, so name it rather than producing
    # a report that looks empty for no stated reason.
    try:
        with target.open("rb") as handle:
            magic = handle.read(4)
    except OSError as exc:
        facts["error"] = f"could not read the file: {exc.strerror or exc}"
        return facts
    if magic[:2] == b"PK":
        facts["error"] = ("that is a project file, not a sliced G-code file - open"
                          " the .gcode your slicer produced")
        return facts

    try:
        head, tail, size = _read_ends(target)
    except OSError as exc:
        facts["error"] = f"could not read the file: {exc.strerror or exc}"
        return facts

    blob = head + "\n" + tail
    if "G1 " not in blob and "G0 " not in blob and "PRINT_START" not in blob:
        facts["error"] = "that does not look like a sliced G-code file"
        return facts

    facts["available"] = True
    facts["size_bytes"] = size
    facts["read_fully"] = not tail

    # --- who made it ---------------------------------------------------------
    generated = _HEADER_GENERATED.search(head) or _PRUSA_GENERATED.search(head) \
        or _HEADER_GENERATED.search(tail) or _PRUSA_GENERATED.search(tail)
    if generated:
        facts["slicer"] = generated.group("slicer").strip()
        facts["slicer_version"] = generated.group("version")
        try:
            facts["sliced_on"] = generated.group("date")
        except IndexError:
            pass
    else:
        facts["unknowns"].append("which slicer produced this file")

    config = _config(blob)
    facts["config"] = config

    # --- the machine it was sliced for --------------------------------------
    facts["printer_model"] = config.get("printer_model")
    if not facts["printer_model"]:
        facts["unknowns"].append("which printer this was sliced for")

    area = config.get("printable_area") or config.get("bed_shape")
    facts["bed_mm"] = _bed_from_area(area)
    if facts["bed_mm"] is None and area:
        facts["unknowns"].append("the bed size this was sliced for")

    nozzles = _floats(config.get("nozzle_diameter", ""))
    facts["nozzle_diameter_mm"] = nozzles or None
    facts["slot_count"] = len(nozzles) or None

    # --- what it will do -----------------------------------------------------
    layers = _TOTAL_LAYERS.search(tail) or _TOTAL_LAYERS.search(head)
    facts["layer_count"] = int(layers.group(1)) if layers else None
    if facts["layer_count"] is None:
        facts["unknowns"].append("how many layers")

    max_z = _MAX_Z.search(head) or _MAX_Z.search(tail)
    facts["max_z_mm"] = float(max_z.group(1)) if max_z else None

    time_match = _TIME.search(tail) or _TIME.search(head)
    facts["estimated_seconds"] = _seconds(time_match.group(1)) if time_match else None
    if facts["estimated_seconds"] is None:
        facts["unknowns"].append("the estimated print time")
    first_layer = _FIRST_LAYER_TIME.search(tail) or _FIRST_LAYER_TIME.search(head)
    facts["first_layer_seconds"] = _seconds(first_layer.group(1)) if first_layer else None

    facts["layer_height_mm"] = _one_float(config.get("layer_height"))
    facts["first_layer_height_mm"] = _one_float(config.get("first_layer_height"))
    facts["nozzle_temperature_c"] = _floats(config.get("first_layer_temperature", "")) or None
    facts["bed_temperature_c"] = _floats(config.get("first_layer_bed_temperature", "")) or None

    # --- materials, per slot -------------------------------------------------
    usage = _usage(tail) or _usage(head)
    facts["filament"] = usage
    types = _strings(config.get("filament_type", ""))
    names = _strings(config.get("filament_settings_id", ""))
    vendors = _strings(config.get("filament_vendor", ""))
    colours = _strings(config.get("filament_colour", "") or config.get("filament_color", ""))

    grams = usage.get("g") or []
    millimetres = usage.get("mm") or []
    slots = []
    count = max(len(grams), len(millimetres), len(types), facts["slot_count"] or 0)
    for index in range(count):
        gram = grams[index] if index < len(grams) else None
        milli = millimetres[index] if index < len(millimetres) else None
        used = None
        if gram is not None or milli is not None:
            used = bool((gram or 0) > 0 or (milli or 0) > 0)
        slots.append({
            "tool": index,
            "used": used,
            "grams": gram,
            "mm": milli,
            "type": types[index] if index < len(types) else None,
            "name": names[index] if index < len(names) else None,
            "vendor": vendors[index] if index < len(vendors) else None,
            "color": _hex(colours[index]) if index < len(colours) else None,
        })
    facts["slots"] = slots
    facts["tools_used"] = [s["tool"] for s in slots if s["used"]]
    if not any(s["used"] is not None for s in slots):
        facts["tools_used"] = None
        facts["unknowns"].append("which tools the job uses")

    # --- purge, and why it cannot be separated -------------------------------
    facts["purge"] = _purge(config, facts["tools_used"])

    # --- object exclusion ----------------------------------------------------
    defines = _EXCLUDE_DEFINE.findall(head)
    facts["exclude_object"] = {
        "present": bool(defines),
        "objects": len(defines),
        # Object names are model names and are the user's business; the count is
        # what the checks need, so the names are deliberately not carried. A
        # digest of them is, because recognising that a sliced job contains the
        # same set of objects as an open project is the strongest provenance
        # evidence there is — and sixteen hex characters give that away to nobody.
        "name_digest": _name_digest(defines),
        "source": "EXCLUDE_OBJECT_DEFINE lines" if defines else "no EXCLUDE_OBJECT_DEFINE lines found",
    }

    # --- firmware-flavour markers the U1 actually uses ------------------------
    facts["markers"] = {
        name: (name in head)
        for name in ("PRINT_START", "PRINT_END", "TIMELAPSE_START",
                     "DEFECT_DETECTION_START", "SET_PRINT_STATS_INFO",
                     "EXCLUDE_OBJECT_START", "M73")
    }
    facts["has_thumbnail"] = "thumbnail begin" in head

    return facts


def _name_digest(defines: list[str]) -> str | None:
    """Fingerprint the object names a job declares, without carrying them."""
    import hashlib

    names = []
    for tail in defines:
        found = _OBJECT_NAME.search(tail or "")
        if found:
            names.append(found.group(1).strip().strip('"').lower())
    names = sorted({n for n in names if n})
    if not names:
        return None
    return hashlib.sha256(chr(0).join(names).encode("utf-8")).hexdigest()[:16]


def _hex(value: str | None) -> str | None:
    """`#8080FF` from whatever the slicer wrote, or None."""
    if not value:
        return None
    text = value.strip().lstrip("#")
    if len(text) >= 6 and all(c in "0123456789abcdefABCDEF" for c in text[:6]):
        return "#" + text[:6].upper()
    return None


def _one_float(raw: str | None) -> float | None:
    values = _floats(raw or "")
    return values[0] if values else None


def _bed_from_area(area: str | None) -> dict | None:
    """`printable_area = 0.5x1,270.5x1,270.5x271,0.5x271` -> width/depth."""
    if not area:
        return None
    points = []
    for piece in area.split(","):
        bits = piece.strip().split("x")
        if len(bits) != 2:
            continue
        try:
            points.append((float(bits[0]), float(bits[1])))
        except ValueError:
            continue
    if len(points) < 3:
        return None
    xs = [p[0] for p in points]
    ys = [p[1] for p in points]
    return {"x": round(max(xs) - min(xs), 2), "y": round(max(ys) - min(ys), 2)}


def _purge(config: dict, tools_used) -> dict:
    """What can honestly be said about purge and waste.

    Snapmaker Orca's summary reports total filament per slot and nothing else. It
    does not break out model, support and purge. So when more than one tool is
    used this reports that purge is *included and not separable*, rather than
    inventing a split.
    """
    tower = config.get("enable_prime_tower")
    tower_on = tower not in (None, "", "0")
    flush = _floats(config.get("flush_volumes_vector", ""))
    multi_tool = bool(tools_used and len(tools_used) > 1)

    if not multi_tool:
        return {
            "separable": False,
            "expected": False,
            "detail": "single-tool job — no tool-change purge",
            "confidence": "confirmed",
        }
    return {
        "separable": False,
        "expected": True,
        "prime_tower": tower_on,
        "flush_volumes_mm3": flush or None,
        "detail": ("this job changes tools, so some filament is purged — the slicer's "
                   "summary reports one total per slot and does not separate purge "
                   "from printed material, so Studio will not split it"),
        "confidence": "confirmed",
    }


def summary_line(facts: dict) -> str:
    """One sentence for a caller that wants a headline."""
    if not facts.get("available"):
        return facts.get("error", "Studio could not read that file.")
    bits = []
    if facts.get("printer_model"):
        bits.append(f"sliced for {facts['printer_model']}")
    if facts.get("slicer"):
        version = facts.get("slicer_version") or ""
        bits.append(f"by {facts['slicer']} {version}".strip())
    if facts.get("layer_count"):
        bits.append(f"{facts['layer_count']} layers")
    tools = facts.get("tools_used")
    if tools:
        bits.append(f"{len(tools)} tool{'s' if len(tools) != 1 else ''}")
    total = (facts.get("filament") or {}).get("total_g")
    if total is not None:
        bits.append(f"{total:g} g")
    return ", ".join(bits) + "." if bits else "Studio read the file but it stated very little."
