"""Read a PrusaSlicer project properly, instead of only recognising one.

Until now Studio could tell that a 3MF came from PrusaSlicer and could read its
printer model, and nothing else — so a Prusa project produced "0 filaments, no
layer height, no printer", and every check downstream had nothing to work with.
The README said "detected; full conversion planned", which is an honest way of
describing an unfinished feature and a poor thing to ship in a stable product.

A Prusa project is not exotic. It carries two extra parts:

* ``Metadata/Slic3r_PE.config`` — the whole print, filament and printer
  configuration as ``; key = value`` lines. It is the same dialect PrusaSlicer
  writes at the end of its G-code, which is why the parser here and the one in
  `gcode.py` recognise each other's files.
* ``Metadata/Slic3r_PE_model.config`` — per-object and per-volume metadata as
  XML: names, matrices, source files, per-object setting overrides, extruder
  assignments and layer-height profiles.

Everything here comes from those two. Nothing is inferred from geometry, and a
key that is absent stays absent rather than becoming a default.
"""
from __future__ import annotations

import re

SETTINGS_PART = "Metadata/Slic3r_PE.config"
MODEL_CONFIG_PART = "Metadata/Slic3r_PE_model.config"

_KV = re.compile(r"^\s*(?:;\s*)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$", re.M)
_OBJECT = re.compile(r"<object\b[^>]*>", re.I)
_METADATA = re.compile(
    r'<metadata\s+type="(?P<type>[^"]+)"\s+key="(?P<key>[^"]+)"\s+value="(?P<value>[^"]*)"', re.I)
_GENERATED = re.compile(r";\s*generated by\s+(?P<app>PrusaSlicer|SuperSlicer)\s+(?P<version>[\w.+\-]+)", re.I)


def settings(raw: bytes | str) -> dict[str, str]:
    """The configuration block as a flat dict. Missing keys are simply absent."""
    text = raw.decode("utf-8", "ignore") if isinstance(raw, (bytes, bytearray)) else raw
    return {match.group(1): match.group(2) for match in _KV.finditer(text)}


def application(raw: bytes | str) -> tuple[str | None, str | None]:
    """("PrusaSlicer", "2.8.0-alpha3") from the config header, or (None, None)."""
    text = raw.decode("utf-8", "ignore") if isinstance(raw, (bytes, bytearray)) else raw
    found = _GENERATED.search(text)
    return (found.group("app"), found.group("version")) if found else (None, None)


def _split(value: str | None) -> list[str]:
    """Per-extruder values, however this file separates them.

    PrusaSlicer uses semicolons between string settings and commas between
    numeric ones, and quotes any value that contains a separator — a filament
    called "PLA, matte" is one value, not two. Both separators are honoured
    because a project can contain both forms, and a wrong split here would
    silently invent an extra extruder.
    """
    if not value:
        return []
    parts, current, quoted = [], "", False
    for char in value:
        if char == '"':
            quoted = not quoted
            continue
        if char in ",;" and not quoted:
            parts.append(current.strip())
            current = ""
            continue
        current += char
    parts.append(current.strip())
    return [p for p in parts if p != ""]


def _hex(value: str | None) -> str | None:
    if not value:
        return None
    text = value.strip().lstrip("#")
    if len(text) >= 6 and all(c in "0123456789abcdefABCDEF" for c in text[:6]):
        return "#" + text[:6].upper()
    return None


def _float(value: str | None) -> float | None:
    try:
        return float(str(value).strip().rstrip("%"))
    except (TypeError, ValueError):
        return None


def _truthy(value: str | None) -> bool | None:
    if value is None:
        return None
    return str(value).strip().lower() in {"1", "true", "yes", "on"}


def filaments(config: dict) -> list[dict]:
    """One entry per extruder slot the project defines."""
    types = _split(config.get("filament_type"))
    colours = _split(config.get("filament_colour") or config.get("filament_color"))
    names = _split(config.get("filament_settings_id"))
    vendors = _split(config.get("filament_vendor"))
    diameters = _split(config.get("filament_diameter"))

    count = max(len(types), len(colours), len(names), len(diameters))
    out = []
    for index in range(count):
        out.append({
            "tool": index,
            "type": types[index] if index < len(types) else None,
            "color": _hex(colours[index]) if index < len(colours) else None,
            "name": names[index] if index < len(names) else None,
            "vendor": vendors[index] if index < len(vendors) else None,
            "diameter_mm": _float(diameters[index]) if index < len(diameters) else None,
        })
    return out


def bed_mm(config: dict) -> dict | None:
    """`bed_shape = 0x0,250x0,250x210,0x210` -> {"x": 250.0, "y": 210.0}."""
    shape = config.get("bed_shape")
    if not shape:
        return None
    points = []
    for piece in shape.split(","):
        bits = piece.strip().split("x")
        if len(bits) != 2:
            continue
        first, second = _float(bits[0]), _float(bits[1])
        if first is None or second is None:
            continue
        points.append((first, second))
    if len(points) < 3:
        return None
    xs = [p[0] for p in points]
    ys = [p[1] for p in points]
    return {"x": round(max(xs) - min(xs), 2), "y": round(max(ys) - min(ys), 2)}


def objects(raw: bytes | str) -> list[dict]:
    """Per-object metadata from the model config: name, extruder, overrides."""
    text = raw.decode("utf-8", "ignore") if isinstance(raw, (bytes, bytearray)) else raw
    out: list[dict] = []
    # Each <object> block runs until the next one, so the metadata inside it
    # belongs to it.
    starts = [m.start() for m in _OBJECT.finditer(text)]
    for position, start in enumerate(starts):
        end = starts[position + 1] if position + 1 < len(starts) else len(text)
        block = text[start:end]
        entry: dict = {"index": position, "name": None, "extruder": None,
                       "settings": {}, "has_layer_profile": False}
        for meta in _METADATA.finditer(block):
            kind, key, value = meta.group("type"), meta.group("key"), meta.group("value")
            if key == "name" and entry["name"] is None:
                entry["name"] = value
            elif key == "extruder":
                try:
                    entry["extruder"] = int(value)
                except ValueError:
                    pass
            elif kind in ("object", "volume") and key not in ("matrix", "source_file",
                                                              "source_object_id",
                                                              "source_volume_id", "name",
                                                              "volume_type"):
                entry["settings"][key] = value
        entry["has_layer_profile"] = "layer_height_profile" in block
        out.append(entry)
    return out


def summarise(settings_raw: bytes | str | None,
              model_config_raw: bytes | str | None = None) -> dict:
    """Everything Studio can establish about a Prusa project, in one call."""
    if not settings_raw:
        return {"available": False, "reason": "this project has no Slic3r_PE.config"}

    config = settings(settings_raw)
    app, version = application(settings_raw)
    slots = filaments(config)
    parsed_objects = objects(model_config_raw) if model_config_raw else []

    # An object carrying its own extruder number is what makes a Prusa project
    # multi-material in practice, even when only one filament profile is listed.
    assigned = sorted({o["extruder"] for o in parsed_objects if o.get("extruder")})

    return {
        "available": True,
        "application": app,
        "application_version": version,
        "printer_model": config.get("printer_model") or None,
        "printer_settings_id": config.get("printer_settings_id") or None,
        "print_settings_id": config.get("print_settings_id") or None,
        "bed_mm": bed_mm(config),
        "nozzle_diameters": _split(config.get("nozzle_diameter")),
        "layer_height_mm": _float(config.get("layer_height")),
        "first_layer_height_mm": _float(config.get("first_layer_height")),
        "filaments": slots,
        "filament_count": len(slots),
        "supports": _truthy(config.get("support_material")),
        "support_style": config.get("support_material_style") or None,
        "brim_mm": _float(config.get("brim_width")),
        "raft_layers": _float(config.get("raft_layers")),
        "objects": parsed_objects,
        "object_count": len(parsed_objects),
        "extruders_assigned": assigned,
        "variable_layer_height": any(o.get("has_layer_profile") for o in parsed_objects),
        "per_object_overrides": sum(1 for o in parsed_objects if o.get("settings")),
        "bed_temperature_c": _float(config.get("bed_temperature")),
        "nozzle_temperature_c": [_float(v) for v in _split(config.get("temperature"))],
    }


def not_carried(summary: dict) -> list[dict]:
    """What a U1 copy cannot keep, stated before anyone asks.

    The fidelity report is the place this ends up. Saying it here, once, keeps
    the claim in one place instead of scattered through the converter.
    """
    if not summary.get("available"):
        return []
    out = []
    if summary.get("variable_layer_height"):
        out.append({
            "element": "Variable layer height",
            "reason": ("PrusaSlicer stores a per-object layer-height profile that Snapmaker "
                       "Orca has no equivalent for. The object keeps its shape; the varying "
                       "layer height does not survive."),
        })
    if summary.get("per_object_overrides"):
        out.append({
            "element": f"Per-object setting overrides ({summary['per_object_overrides']} object(s))",
            "reason": ("Settings attached to individual objects are named differently in "
                       "Snapmaker Orca and are not translated. Review them after opening the copy."),
        })
    if summary.get("supports"):
        out.append({
            "element": "Support settings",
            "reason": ("Support is carried across as on or off. The style and its detailed "
                       "parameters are PrusaSlicer's own and do not map one-to-one."),
        })
    return out
