"""Read a PrusaSlicer project properly, instead of only recognising one.

Until now Studio could tell that a 3MF came from PrusaSlicer and could read its
printer model, and nothing else — so a Prusa project produced "0 filaments, no
layer height, no printer", and every check downstream had nothing to work with.
The README said "detected; full conversion planned", which is an honest way of
describing an unfinished feature and a poor thing to ship in a stable product.

A Prusa project is not exotic. It carries two extra parts:

* ``Metadata/Slic3r_PE.config`` — the whole print, filament and printer
  configuration as ``; key = value`` lines. It is the same dialect PrusaSlicer
  writes at the end of its G-code, which is why the parser here and the one in
  `gcode.py` recognise each other's files.
* ``Metadata/Slic3r_PE_model.config`` — per-object and per-volume metadata as
  XML: names, matrices, source files, per-object setting overrides, extruder
  assignments and layer-height profiles.

Everything here comes from those two. Nothing is inferred from geometry, and a
key that is absent stays absent rather than becoming a default.
"""
from __future__ import annotations

import re

SETTINGS_PART = "Metadata/Slic3r_PE.config"
MODEL_CONFIG_PART = "Metadata/Slic3r_PE_model.config"

_KV = re.compile(r"^\s*(?:;\s*)?([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*?)\s*$", re.M)
_OBJECT = re.compile(r"<object\b[^>]*>", re.I)
_METADATA = re.compile(
    r'<metadata\s+type="(?P<type>[^"]+)"\s+key="(?P<key>[^"]+)"\s+value="(?P<value>[^"]*)"', re.I)
_GENERATED = re.compile(r";\s*generated by\s+(?P<app>PrusaSlicer|SuperSlicer)\s+(?P<version>[\w.+\-]+)", re.I)

#: Metadata PrusaSlicer writes to remember where an object came from — the source
#: file, its id, and how far it was offset when it was imported. It is not a
#: setting anybody changed, and counting it as one told users their project had
#: per-object overrides that would not be carried across when it had none.
IMPORT_METADATA = frozenset({
    "matrix", "source_file", "source_object_id", "source_volume_id",
    "source_offset_x", "source_offset_y", "source_offset_z",
    "source_in_inches", "source_in_meters",
    "name", "volume_type",
    # Reported in its own right as variable layer height; counting it here as
    # well would report the same loss twice under two names.
    "layer_height_profile",
})


def settings(raw: bytes | str) -> dict[str, str]:
    """The configuration block as a flat dict. Missing keys are simply absent."""
    text = raw.decode("utf-8", "ignore") if isinstance(raw, (bytes, bytearray)) else raw
    return {match.group(1): match.group(2) for match in _KV.finditer(text)}


def application(raw: bytes | str) -> tuple[str | None, str | None]:
    """("PrusaSlicer", "2.8.0-alpha3") from the config header, or (None, None)."""
    text = raw.decode("utf-8", "ignore") if isinstance(raw, (bytes, bytearray)) else raw
    found = _GENERATED.search(text)
    return (found.group("app"), found.group("version")) if found else (None, None)


def _split(value: str | None) -> list[str]:
    """Per-extruder values, however this file separates them.

    PrusaSlicer uses semicolons between string settings and commas between
    numeric ones, and quotes any value that contains a separator — a filament
    called "PLA, matte" is one value, not two. Both separators are honoured
    because a project can contain both forms, and a wrong split here would
    silently invent an extra extruder.
    """
    if not value:
        return []
    parts, current, quoted = [], "", False
    for char in value:
        if char == '"':
            quoted = not quoted
            continue
        if char in ",;" and not quoted:
            parts.append(current.strip())
            current = ""
            continue
        current += char
    parts.append(current.strip())
    return [p for p in parts if p != ""]


def _hex(value: str | None) -> str | None:
    if not value:
        return None
    text = value.strip().lstrip("#")
    if len(text) >= 6 and all(c in "0123456789abcdefABCDEF" for c in text[:6]):
        return "#" + text[:6].upper()
    return None


def _float(value: str | None) -> float | None:
    try:
        return float(str(value).strip().rstrip("%"))
    except (TypeError, ValueError):
        return None


def _truthy(value: str | None) -> bool | None:
    if value is None:
        return None
    return str(value).strip().lower() in {"1", "true", "yes", "on"}


def filaments(config: dict) -> list[dict]:
    """One entry per extruder slot the project defines."""
    types = _split(config.get("filament_type"))
    colours = _split(config.get("filament_colour") or config.get("filament_color"))
    names = _split(config.get("filament_settings_id"))
    vendors = _split(config.get("filament_vendor"))
    diameters = _split(config.get("filament_diameter"))

    count = max(len(types), len(colours), len(names), len(diameters))
    out = []
    for index in range(count):
        out.append({
            "tool": index,
            "type": types[index] if index < len(types) else None,
            "color": _hex(colours[index]) if index < len(colours) else None,
            "name": names[index] if index < len(names) else None,
            "vendor": vendors[index] if index < len(vendors) else None,
            "diameter_mm": _float(diameters[index]) if index < len(diameters) else None,
        })
    return out


def bed_mm(config: dict) -> dict | None:
    """`bed_shape = 0x0,250x0,250x210,0x210` -> {"x": 250.0, "y": 210.0}."""
    shape = config.get("bed_shape")
    if not shape:
        return None
    points = []
    for piece in shape.split(","):
        bits = piece.strip().split("x")
        if len(bits) != 2:
            continue
        first, second = _float(bits[0]), _float(bits[1])
        if first is None or second is None:
            continue
        points.append((first, second))
    if len(points) < 3:
        return None
    xs = [p[0] for p in points]
    ys = [p[1] for p in points]
    return {"x": round(max(xs) - min(xs), 2), "y": round(max(ys) - min(ys), 2)}


def objects(raw: bytes | str) -> list[dict]:
    """Per-object metadata from the model config: name, extruder, overrides."""
    text = raw.decode("utf-8", "ignore") if isinstance(raw, (bytes, bytearray)) else raw
    out: list[dict] = []
    # Each <object> block runs until the next one, so the metadata inside it
    # belongs to it.
    starts = [m.start() for m in _OBJECT.finditer(text)]
    for position, start in enumerate(starts):
        end = starts[position + 1] if position + 1 < len(starts) else len(text)
        block = text[start:end]
        entry: dict = {"index": position, "name": None, "extruder": None,
                       "settings": {}, "has_layer_profile": False}
        for meta in _METADATA.finditer(block):
            kind, key, value = meta.group("type"), meta.group("key"), meta.group("value")
            if key == "name" and entry["name"] is None:
                entry["name"] = value
            elif key == "extruder":
                try:
                    entry["extruder"] = int(value)
                except ValueError:
                    pass
            elif kind in ("object", "volume") and key not in IMPORT_METADATA:
                entry["settings"][key] = value
        entry["has_layer_profile"] = "layer_height_profile" in block
        out.append(entry)
    return out


def _overrides_carried(parsed_objects: list[dict]) -> int:
    """How many object-specific settings cross in Snapmaker Orca's own words."""
    from . import overrides as object_overrides

    return sum(len(object_overrides.plan(o.get("settings"))["carry"])
               for o in parsed_objects)


def _overrides_not_carried(parsed_objects: list[dict]) -> list[str]:
    """The object-specific settings that stay behind, named once each.

    Named rather than counted: "three settings were not carried" tells somebody
    to worry, and `ironing_type, seam_position` tells them what to set in Orca.
    """
    from . import overrides as object_overrides

    seen: list[str] = []
    for entry in parsed_objects:
        for row in object_overrides.plan(entry.get("settings"))["rows"]:
            if not row["carried"] and row["source_key"] not in seen:
                seen.append(row["source_key"])
    return seen


def _nozzles(config: dict) -> tuple[list[str], str | None]:
    """Which nozzle the project was set up for, and how that is known.

    A PrusaSlicer *project* does not carry `nozzle_diameter` — that lives in the
    printer profile, and what the project keeps is the variant it was selected
    with and the profile's name. Reading only the missing key reported "no
    nozzle" for every Prusa project Studio has ever opened; reading the variant
    without saying where it came from would present a profile name as a
    measurement. So both come back together.
    """
    direct = _split(config.get("nozzle_diameter"))
    if direct:
        return direct, "stated by the project"
    variant = (config.get("printer_variant") or "").strip()
    if _float(variant) is not None:
        return [variant], "the printer variant the project was saved with"
    # "Original Prusa MK4 Input Shaper 0.4 nozzle"
    found = re.search(r"([0-9]*\.?[0-9]+)\s*nozzle", config.get("printer_settings_id") or "", re.I)
    if found:
        return [found.group(1)], "the name of the printer profile the project uses"
    return [], None


def summarise(settings_raw: bytes | str | None,
              model_config_raw: bytes | str | None = None) -> dict:
    """Everything Studio can establish about a Prusa project, in one call."""
    if not settings_raw:
        return {"available": False, "reason": "this project has no Slic3r_PE.config"}

    config = settings(settings_raw)
    nozzles, nozzle_source = _nozzles(config)
    app, version = application(settings_raw)
    slots = filaments(config)
    parsed_objects = objects(model_config_raw) if model_config_raw else []

    # An object carrying its own extruder number is what makes a Prusa project
    # multi-material in practice, even when only one filament profile is listed.
    assigned = sorted({o["extruder"] for o in parsed_objects if o.get("extruder")})

    return {
        "available": True,
        "application": app,
        "application_version": version,
        "printer_model": config.get("printer_model") or None,
        "printer_settings_id": config.get("printer_settings_id") or None,
        "print_settings_id": config.get("print_settings_id") or None,
        "bed_mm": bed_mm(config),
        "nozzle_diameters": nozzles,
        "nozzle_source": nozzle_source,
        "layer_height_mm": _float(config.get("layer_height")),
        "first_layer_height_mm": _float(config.get("first_layer_height")),
        "filaments": slots,
        "filament_count": len(slots),
        "supports": _truthy(config.get("support_material")),
        "support_style": config.get("support_material_style") or None,
        "brim_mm": _float(config.get("brim_width")),
        "raft_layers": _float(config.get("raft_layers")),
        "objects": parsed_objects,
        "object_count": len(parsed_objects),
        "extruders_assigned": assigned,
        "variable_layer_height": any(o.get("has_layer_profile") for o in parsed_objects),
        "per_object_overrides": sum(1 for o in parsed_objects if o.get("settings")),
        "per_object_overrides_carried": _overrides_carried(parsed_objects),
        "per_object_overrides_not_carried": _overrides_not_carried(parsed_objects),
        "bed_temperature_c": _float(config.get("bed_temperature")),
        "nozzle_temperature_c": [_float(v) for v in _split(config.get("temperature"))],
    }


#: What a Prusa project says, and the Snapmaker Orca setting that means the same
#: thing. Only settings whose *meaning* survives the crossing are here.
#:
#: Temperatures are deliberately absent. A PrusaSlicer filament profile's 225 °C
#: is about a Prusa hotend and a Prusa filament profile; copying it into a U1
#: project would look like carrying the user's intent across and would in fact be
#: giving one machine another machine's numbers. Support style, seam position,
#: ironing and per-object overrides are absent for the same reason: they have
#: names in both slicers and not the same behaviour behind them.
CARRIED = (
    ("layer_height", "layer_height", "layer height"),
    ("first_layer_height", "initial_layer_print_height", "first layer height"),
    ("fill_density", "sparse_infill_density", "infill density"),
    ("perimeters", "wall_loops", "number of walls"),
    ("brim_width", "brim_width", "brim width"),
)


def to_u1_settings(config: dict, summary: dict | None = None) -> dict:
    """The Prusa settings that can be carried into a U1 project, and their evidence.

    Geometry has always survived the crossing; the print itself did not. A project
    sliced at 0.15 mm with four walls and 45% infill arrived as the U1 starter
    profile — 0.2 mm, two walls, 15% — which is a different print of the same
    shape, and nothing said so.

    This carries only what means the same thing on both sides, and returns why for
    each one, so the fidelity report can show the mapping rather than assert it.
    Everything else is left to `not_carried` to name.
    """
    mapped: dict[str, str] = {}
    evidence: list[dict] = []

    for prusa_key, u1_key, english in CARRIED:
        raw = (config or {}).get(prusa_key)
        value = _float(raw)
        if raw is None or value is None:
            continue
        if prusa_key == "fill_density":
            mapped[u1_key] = f"{value:g}%"
        elif prusa_key == "perimeters":
            mapped[u1_key] = str(int(value))
        else:
            mapped[u1_key] = f"{value:g}"
        evidence.append({"key": u1_key, "from": prusa_key, "value": mapped[u1_key],
                         "detail": f"{english} carried from the PrusaSlicer project"})

    # A brim width of zero is PrusaSlicer's way of saying "no brim". Carrying the
    # width without the intent would leave the U1 copy set to add one anyway,
    # because Orca decides that with a separate setting.
    brim = _float((config or {}).get("brim_width"))
    if brim is not None:
        mapped["brim_type"] = "no_brim" if brim <= 0 else "auto_brim"
        evidence.append({"key": "brim_type", "from": "brim_width",
                         "value": mapped["brim_type"],
                         "detail": ("no brim, as the project had it" if brim <= 0
                                    else "a brim, as the project had it")})

    supports = _truthy((config or {}).get("support_material"))
    if supports is not None:
        mapped["enable_support"] = "1" if supports else "0"
        evidence.append({"key": "enable_support", "from": "support_material",
                         "value": mapped["enable_support"],
                         "detail": ("support turned " + ("on" if supports else "off")
                                    + " as the project had it — the style and its settings "
                                      "are PrusaSlicer's own and are not carried")})

    slots = (summary or {}).get("filaments") or filaments(config or {})
    types = [s.get("type") for s in slots if s.get("type")]
    colours = [s.get("color") for s in slots if s.get("color")]
    if types:
        mapped["filament_type"] = types
        evidence.append({"key": "filament_type", "from": "filament_type",
                         "value": ", ".join(types),
                         "detail": "the materials the project was set up for"})
    if colours:
        mapped["filament_colour"] = colours
        evidence.append({"key": "filament_colour", "from": "filament_colour",
                         "value": ", ".join(colours),
                         "detail": "the filament colours the project was set up for"})
    return {"settings": mapped, "evidence": evidence}


def not_carried(summary: dict) -> list[dict]:
    """What a U1 copy cannot keep, stated before anyone asks.

    The fidelity report is the place this ends up. Saying it here, once, keeps
    the claim in one place instead of scattered through the converter.
    """
    if not summary.get("available"):
        return []
    out = []
    if summary.get("variable_layer_height"):
        out.append({
            "element": "Variable layer height",
            "reason": ("PrusaSlicer stores a per-object layer-height profile that Snapmaker "
                       "Orca has no equivalent for. The object keeps its shape; the varying "
                       "layer height does not survive."),
        })
    uncarried = summary.get("per_object_overrides_not_carried") or []
    if uncarried:
        listed = ", ".join(uncarried[:4]) + ("…" if len(uncarried) > 4 else "")
        out.append({
            "element": f"Object-specific settings not carried ({len(uncarried)})",
            "reason": (f"{listed} — Studio has not established what these mean to "
                       "Snapmaker Orca, so it reports them rather than guessing. Set "
                       "them on the object in Orca after opening the copy."),
        })
    if summary.get("supports"):
        out.append({
            "element": "Support settings",
            "reason": ("Support is carried across as on or off. The style and its detailed "
                       "parameters are PrusaSlicer's own and do not map one-to-one."),
        })
    if summary.get("nozzle_temperature_c") or summary.get("bed_temperature_c"):
        out.append({
            "element": "Temperatures",
            "reason": ("The project's temperatures belong to a Prusa hotend and a Prusa "
                       "filament profile. The copy keeps the U1 profile's own, which is why "
                       "they may differ from what you set in PrusaSlicer."),
        })
    return out
