"""U1 identity normalization — make a foreign (Bambu/Orca) project read as a
genuine Snapmaker U1 project so Snapmaker Orca loads it with zero warnings.

Ground truth is a known-good Snapmaker U1 export: its preset
identity strings, version, and filament identity are the canonical targets.
Snapmaker Orca's three warnings all trace to project metadata, not geometry:
  - "newer version"      -> the `version` key and slice_info X-BBL-Client-Version
  - "Customized Preset"  -> *_settings_id / *_profile not matching a U1 system preset
  - Bambu/H2D references  -> foreign preset ids + leftover Bambu machine G-code

This layer rewrites the identity block to the known-good values, scrubs any
remaining Bambu/BBL/H2D strings, and blanks the slice_info version stamp.
Geometry, object layout, filament colours/types and count are left untouched.
"""
from __future__ import annotations
import re

# Canonical U1 identity, copied verbatim from a known-good Snapmaker U1 export.
U1_VERSION = "2.3.3"
U1_PRINTER_MODEL = "Snapmaker U1"
U1_PRINTER_SETTINGS_ID = "Snapmaker U1 (0.4 nozzle)"
U1_PRINTER_VARIANT = "0.4"
U1_PRINT_SETTINGS_ID = "0.20 Standard @Snapmaker U1 (0.4 nozzle)"
U1_NOZZLE_TYPE = "hardened_steel"
U1_FILAMENT_SETTINGS_ID = "Snapmaker PLA"
U1_FILAMENT_VENDOR = "Snapmaker"

# Substrings that must never survive in a clean U1 project (case-insensitive).
FOREIGN_TOKENS = ("bbl", "h2d", "bambu")

# Setting values from a newer Orca schema that Snapmaker Orca would otherwise
# "replace" on load (which raises the "generated by a newer version" notice).
# Pre-normalize them to the value Snapmaker Orca expects (matches the known-good
# Snapmaker U1 export). key -> {newer_value: u1_value}
VALUE_NORMALIZATIONS = {
    "ensure_vertical_shell_thickness": {"enabled": "ensure_all"},
}


def normalize_values(cfg: dict) -> list[dict]:
    """Replace newer-schema enum values with the values Snapmaker Orca expects.
    Returns the changes applied (old->new)."""
    changes = []
    for key, mapping in VALUE_NORMALIZATIONS.items():
        cur = cfg.get(key)
        if isinstance(cur, str) and cur in mapping:
            new = mapping[cur]
            changes.append({"key": key, "old": cur, "new": new})
            cfg[key] = new
    return changes


def _has_foreign(value) -> bool:
    if isinstance(value, str):
        low = value.lower()
        return any(t in low for t in FOREIGN_TOKENS)
    if isinstance(value, list):
        return any(_has_foreign(x) for x in value)
    return False


def normalize_project_identity(cfg: dict, n_filaments: int) -> dict:
    """Force the U1 preset identity block. Returns the changes applied (old->new).
    Filament identity arrays are sized to `n_filaments` (the real colour count)."""
    n = max(1, n_filaments)
    targets = {
        "version": U1_VERSION,
        "printer_model": U1_PRINTER_MODEL,
        "printer_settings_id": U1_PRINTER_SETTINGS_ID,
        "printer_variant": U1_PRINTER_VARIANT,
        "print_settings_id": U1_PRINT_SETTINGS_ID,
        "default_print_profile": U1_PRINT_SETTINGS_ID,
        "default_filament_profile": [U1_FILAMENT_SETTINGS_ID],
        "compatible_printers": [U1_PRINTER_SETTINGS_ID],
        "print_compatible_printers": [U1_PRINTER_SETTINGS_ID],
        "nozzle_type": U1_NOZZLE_TYPE,
        "filament_settings_id": [U1_FILAMENT_SETTINGS_ID] * n,
        "filament_vendor": [U1_FILAMENT_VENDOR] * n,
    }
    changes = []
    for k, v in targets.items():
        if cfg.get(k) != v:
            changes.append({"key": k, "old": cfg.get(k), "new": v})
            cfg[k] = v
    return {"changed": changes}


# Clean-import normalization (Snapmaker Orca dialogs on a real beta file):
#  - "Customized Preset"  -> `different_settings_to_system` non-empty (the
#    "differs from the system preset" marker, carried from the source slice).
#  - "Print By Object" collision -> `print_sequence == "by object"`.
# A genuine clean U1 export carries neither. We reset the markers/sequence; the
# customized *values* themselves stay in the project (intent preserved).
U1_PRINT_SEQUENCE = "by layer"


def normalize_presets(cfg: dict) -> list[dict]:
    """Clear the markers Snapmaker Orca uses to flag a project as customized and
    reset the print sequence to the U1 default. Returns the changes (old->new)."""
    changes = []
    # 1. different_settings_to_system — blank every entry, keep list shape.
    dss = cfg.get("different_settings_to_system")
    if isinstance(dss, list) and any(str(x) for x in dss):
        cleared = [""] * len(dss)
        changes.append({"key": "different_settings_to_system", "old": dss, "new": cleared})
        cfg["different_settings_to_system"] = cleared
    elif isinstance(dss, str) and dss:
        changes.append({"key": "different_settings_to_system", "old": dss, "new": ""})
        cfg["different_settings_to_system"] = ""
    # 2. print_sequence — "by object" triggers the collision warning.
    if cfg.get("print_sequence") not in (None, U1_PRINT_SEQUENCE):
        changes.append({"key": "print_sequence", "old": cfg.get("print_sequence"), "new": U1_PRINT_SEQUENCE})
        cfg["print_sequence"] = U1_PRINT_SEQUENCE
    # 3. Defensive: explicit custom-preset flag, cleared only if actually set
    #    (absent/None on the investigated sample — guard against other sources).
    v = cfg.get("is_custom_defined")
    if v not in (None, "", "0"):
        changes.append({"key": "is_custom_defined", "old": v, "new": "0"})
        cfg["is_custom_defined"] = "0"
    return changes


def scrub_foreign(cfg: dict) -> list[str]:
    """Blank any remaining Bambu/BBL/H2D-bearing values (typically leftover
    machine G-code blocks like time_lapse_gcode / wrapping_detection_gcode).
    Returns the list of keys that were cleared."""
    cleared = []
    for k, v in list(cfg.items()):
        if isinstance(v, str) and _has_foreign(v):
            cfg[k] = ""
            cleared.append(k)
        elif isinstance(v, list) and _has_foreign(v):
            cfg[k] = ["" if _has_foreign(x) else x for x in v]
            cleared.append(k)
    return cleared


def find_foreign(cfg: dict) -> list[str]:
    """Keys whose value still contains a foreign token (for validation)."""
    return [k for k, v in cfg.items() if _has_foreign(v)]


def is_u1_clean(cfg: dict) -> tuple[bool, list[str]]:
    """True only if the project reads as a genuine U1 project: no foreign tokens
    and the identity block matches U1 expectations."""
    issues = []
    foreign = find_foreign(cfg)
    if foreign:
        issues.append(f"foreign Bambu/BBL/H2D metadata remains in: {', '.join(sorted(foreign)[:8])}")
    if cfg.get("printer_model") != U1_PRINTER_MODEL:
        issues.append(f"printer_model is {cfg.get('printer_model')!r}, expected {U1_PRINTER_MODEL!r}")
    if not str(cfg.get("printer_settings_id", "")).startswith("Snapmaker U1"):
        issues.append(f"printer_settings_id {cfg.get('printer_settings_id')!r} is not a U1 preset")
    if "@Snapmaker U1" not in str(cfg.get("print_settings_id", "")):
        issues.append(f"print_settings_id {cfg.get('print_settings_id')!r} is not a U1 process preset")
    fsi = cfg.get("filament_settings_id")
    if isinstance(fsi, list) and not all(str(x).startswith("Snapmaker") for x in fsi):
        issues.append("filament_settings_id contains non-Snapmaker presets")
    if not cfg.get("version"):
        issues.append("missing version")
    # Clean-import markers (Snapmaker Orca dialogs):
    dss = cfg.get("different_settings_to_system")
    if (isinstance(dss, list) and any(str(x) for x in dss)) or (isinstance(dss, str) and dss):
        issues.append("different_settings_to_system is non-empty (triggers 'Customized Preset')")
    ps = cfg.get("print_sequence")
    if ps not in (None, U1_PRINT_SEQUENCE):
        issues.append(f"print_sequence is {ps!r}, expected {U1_PRINT_SEQUENCE!r} (triggers 'Print By Object')")
    return (not issues, issues)


# slice_info.config carries an X-BBL-Client-Version stamp; the known-good U1
# file leaves it blank. A non-empty Bambu version here triggers the
# "generated by a newer version" warning.
_SLICE_VERSION_RE = re.compile(
    rb'(key="X-BBL-Client-Version"\s+value=")[^"]*(")'
)


def normalize_slice_info(xml: bytes) -> bytes:
    """Blank the X-BBL-Client-Version stamp to match a clean U1 export."""
    return _SLICE_VERSION_RE.sub(rb"\1\2", xml)
