"""U1 identity normalization — make a foreign (Bambu/Orca) project read as a
genuine Snapmaker U1 project so Snapmaker Orca loads it with zero warnings.

Ground truth is a known-good Snapmaker U1 export: its preset
identity strings, version, and filament identity are the canonical targets.
Snapmaker Orca's three warnings all trace to project metadata, not geometry:
  - "newer version"      -> the `version` key and slice_info X-BBL-Client-Version
  - "Customized Preset"  -> *_settings_id / *_profile not matching a U1 system preset
  - Bambu/H2D references  -> foreign preset ids + leftover Bambu machine G-code

This layer rewrites the identity block to the known-good values, scrubs any
remaining Bambu/BBL/H2D strings, and blanks the slice_info version stamp.
Geometry, object layout, filament colours/types and count are left untouched.
"""
from __future__ import annotations
import re
from .profile import load_profile

# Canonical U1 identity, copied verbatim from a known-good Snapmaker U1 export.
U1_VERSION = "2.3.3"
U1_PRINTER_MODEL = "Snapmaker U1"
U1_PRINTER_SETTINGS_ID = "Snapmaker U1 (0.4 nozzle)"
U1_PRINTER_VARIANT = "0.4"
U1_PRINT_SETTINGS_ID = "0.20 Standard @Snapmaker U1 (0.4 nozzle)"
U1_NOZZLE_TYPE = "hardened_steel"
U1_FILAMENT_SETTINGS_ID = "Snapmaker PLA"
U1_FILAMENT_VENDOR = "Snapmaker"

# Substrings that must never survive in a clean U1 project (case-insensitive).
FOREIGN_TOKENS = ("bbl", "h2d", "bambu")

# Setting values from a newer Orca schema that Snapmaker Orca would otherwise
# "replace" on load (which raises the "generated by a newer version" notice).
# Pre-normalize them to the value Snapmaker Orca expects (matches the known-good
# Snapmaker U1 export). key -> {newer_value: u1_value}
VALUE_NORMALIZATIONS = {
    "ensure_vertical_shell_thickness": {"enabled": "ensure_all"},
}

# Profile-defined G-code is authoritative for the bundled U1 template.  These
# are template machine blocks that are not currently represented in that
# profile; keep the list here so both scrub and validation use the same set.
_EXTRA_MACHINE_GCODE_KEYS = frozenset({
    "change_extrusion_role_gcode",
    "printing_by_object_gcode",
    "time_lapse_gcode",
    "wrapping_detection_gcode",
})


def machine_gcode_keys() -> frozenset[str]:
    """Return every machine G-code key recognized by the U1 template.

    New G-code blocks in the profile are included automatically; template
    blocks absent from the profile remain in the small maintained supplement.
    """
    profile_keys = load_profile("snapmaker_u1")["keys"]
    return frozenset(k for k in profile_keys if k.endswith("_gcode")) | _EXTRA_MACHINE_GCODE_KEYS


def normalize_values(cfg: dict) -> list[dict]:
    """Replace newer-schema enum values with the values Snapmaker Orca expects.
    Returns the changes applied (old->new)."""
    changes = []
    for key, mapping in VALUE_NORMALIZATIONS.items():
        cur = cfg.get(key)
        if isinstance(cur, str) and cur in mapping:
            new = mapping[cur]
            changes.append({"key": key, "old": cur, "new": new,
                            "reason": "value from a newer Orca schema mapped for Snapmaker Orca"})
            cfg[key] = new
    return changes


def _has_foreign(value) -> bool:
    if isinstance(value, str):
        low = value.lower()
        return any(t in low for t in FOREIGN_TOKENS)
    if isinstance(value, list):
        return any(_has_foreign(x) for x in value)
    return False


def normalize_project_identity(cfg: dict, n_filaments: int,
                               *, preserve_filament_identity: bool = False) -> dict:
    """Force the U1 preset identity block. Returns the changes applied (old->new).
    Filament identity arrays are sized to `n_filaments` (the real colour count)."""
    n = max(1, n_filaments)

    # The preset *name* has to describe the project. Preserve mode keeps the
    # creator's layer height, so stamping one fixed name onto every project
    # labelled a 0.12 mm project as "0.20 Standard" — right settings, wrong
    # label, which Snapmaker Orca then reports as a customised preset with no
    # explanation. Pick the name that fits; when none does, keep the default and
    # let the caller tell the user why.
    from . import process_preset

    preset = process_preset.choose(cfg)
    if preset["matched"]:
        print_settings_id = preset["print_settings_id"]
        printer_settings_id = preset["printer_settings_id"]
        printer_variant = preset["printer_variant"]
    else:
        print_settings_id = U1_PRINT_SETTINGS_ID
        printer_settings_id = U1_PRINTER_SETTINGS_ID
        printer_variant = U1_PRINTER_VARIANT

    targets = {
        "version": U1_VERSION,
        "printer_model": U1_PRINTER_MODEL,
        "printer_settings_id": printer_settings_id,
        "printer_variant": printer_variant,
        "print_settings_id": print_settings_id,
        "default_print_profile": print_settings_id,
        "compatible_printers": [printer_settings_id],
        "print_compatible_printers": [printer_settings_id],
        "nozzle_type": U1_NOZZLE_TYPE,
    }
    if not preserve_filament_identity:
        targets.update({
            "default_filament_profile": [U1_FILAMENT_SETTINGS_ID],
            "filament_settings_id": [U1_FILAMENT_SETTINGS_ID] * n,
            "filament_vendor": [U1_FILAMENT_VENDOR] * n,
        })
    changes = []
    for k, v in targets.items():
        if cfg.get(k) != v:
            changes.append({"key": k, "old": cfg.get(k), "new": v,
                            "reason": "U1 project identity normalized"})
            cfg[k] = v
    return {"changed": changes, "preset": preset}


# Clean-import normalization (Snapmaker Orca dialogs on a real beta file):
#  - "Customized Preset"  -> `different_settings_to_system` non-empty (the
#    "differs from the system preset" marker, carried from the source slice).
#  - "Print By Object" collision -> `print_sequence == "by object"`.
# A genuine clean U1 export carries neither. We reset the markers/sequence; the
# customized *values* themselves stay in the project (intent preserved).
U1_PRINT_SEQUENCE = "by layer"


def normalize_presets(cfg: dict, *, preserve_creator_settings: bool = False) -> list[dict]:
    """Clear the markers Snapmaker Orca uses to flag a project as customized and
    reset the print sequence to the U1 default. Returns the changes (old->new)."""
    changes = []
    # 1. different_settings_to_system — blank every entry, keep list shape.
    dss = cfg.get("different_settings_to_system")
    if not preserve_creator_settings:
        if isinstance(dss, list) and any(str(x) for x in dss):
            cleared = [""] * len(dss)
            changes.append({"key": "different_settings_to_system", "old": dss, "new": cleared,
                            "reason": "custom-preset marker cleared"})
            cfg["different_settings_to_system"] = cleared
        elif isinstance(dss, str) and dss:
            changes.append({"key": "different_settings_to_system", "old": dss, "new": "",
                            "reason": "custom-preset marker cleared"})
            cfg["different_settings_to_system"] = ""
    # 2. print_sequence — "by object" triggers the collision warning.
    if (not preserve_creator_settings
            and cfg.get("print_sequence") not in (None, U1_PRINT_SEQUENCE)):
        changes.append({"key": "print_sequence", "old": cfg.get("print_sequence"),
                        "new": U1_PRINT_SEQUENCE,
                        "reason": "print sequence normalized to the U1 default"})
        cfg["print_sequence"] = U1_PRINT_SEQUENCE
    # 3. Defensive: explicit custom-preset flag, cleared only if actually set
    #    (absent/None on the investigated sample — guard against other sources).
    v = cfg.get("is_custom_defined")
    if v not in (None, "", "0"):
        changes.append({"key": "is_custom_defined", "old": v, "new": "0",
                        "reason": "custom-preset flag cleared"})
        cfg["is_custom_defined"] = "0"
    return changes


def scrub_foreign(cfg: dict, *, preserve_creator_settings: bool = False,
                  compat_keys: set[str] | None = None) -> dict:
    """Blank any remaining Bambu/BBL/H2D-bearing values (typically leftover
    machine G-code blocks like time_lapse_gcode / wrapping_detection_gcode).
    Returns the list of keys that were cleared."""
    cleared = []
    warnings = []
    machine_keys = machine_gcode_keys()
    allowed = set(compat_keys or ()) | machine_keys | {
        "printhost",
        "printhost_type", "printhost_authorization_type", "printhost_port",
        "printhost_api_key", "device_ip", "device_type", "device_name",
    }
    for k, v in list(cfg.items()):
        if not _has_foreign(v):
            continue
        machine_or_device = k in allowed or "printhost" in k or k.startswith("device_")
        if preserve_creator_settings and not machine_or_device:
            warnings.append(f"Creator setting '{k}' contains foreign slicer metadata and was kept from the original file.")
            continue
        old = v
        if isinstance(v, str):
            cfg[k] = ""
        elif isinstance(v, list):
            cfg[k] = ["" if _has_foreign(x) else x for x in v]
        cleared.append({"key": k, "old": old, "new": cfg[k],
                        "reason": "foreign machine or device metadata is not carried"})
    return {"cleared": cleared, "warnings": warnings}


def find_foreign(cfg: dict, *, preserve_creator_settings: bool = False,
                 compat_keys: set[str] | None = None) -> list[str]:
    """Keys whose value still contains a foreign token (for validation)."""
    foreign = [k for k, v in cfg.items() if _has_foreign(v)]
    if not preserve_creator_settings:
        return foreign
    allowed = set(compat_keys or ()) | machine_gcode_keys() | {
                                        "printhost", "printhost_type", "printhost_authorization_type",
                                        "printhost_port", "printhost_api_key", "device_ip",
                                        "device_type", "device_name"}
    return [key for key in foreign
            if key in allowed or "printhost" in key or key.startswith("device_")]


def is_u1_clean(cfg: dict, *, preserve_creator_settings: bool = False,
                compat_keys: set[str] | None = None) -> tuple[bool, list[str]]:
    """True only if the project reads as a genuine U1 project: no foreign tokens
    and the identity block matches U1 expectations."""
    issues = []
    foreign = find_foreign(cfg, preserve_creator_settings=preserve_creator_settings,
                           compat_keys=compat_keys)
    if foreign:
        issues.append(f"foreign Bambu/BBL/H2D metadata remains in: {', '.join(sorted(foreign)[:8])}")
    if cfg.get("printer_model") != U1_PRINTER_MODEL:
        issues.append(f"printer_model is {cfg.get('printer_model')!r}, expected {U1_PRINTER_MODEL!r}")
    if not str(cfg.get("printer_settings_id", "")).startswith("Snapmaker U1"):
        issues.append(f"printer_settings_id {cfg.get('printer_settings_id')!r} is not a U1 preset")
    if "@Snapmaker U1" not in str(cfg.get("print_settings_id", "")):
        issues.append(f"print_settings_id {cfg.get('print_settings_id')!r} is not a U1 process preset")
    fsi = cfg.get("filament_settings_id")
    if (not preserve_creator_settings and isinstance(fsi, list)
            and not all(str(x).startswith("Snapmaker") for x in fsi)):
        issues.append("filament_settings_id contains non-Snapmaker presets")
    if not cfg.get("version"):
        issues.append("missing version")
    # Clean-import markers (Snapmaker Orca dialogs):
    dss = cfg.get("different_settings_to_system")
    if (not preserve_creator_settings
            and ((isinstance(dss, list) and any(str(x) for x in dss)) or (isinstance(dss, str) and dss))):
        issues.append("different_settings_to_system is non-empty (triggers 'Customized Preset')")
    elif preserve_creator_settings and ((isinstance(dss, list) and any(str(x) for x in dss))
                                         or (isinstance(dss, str) and dss)):
        issues.append("warning: creator's different_settings_to_system was kept")
    ps = cfg.get("print_sequence")
    if not preserve_creator_settings and ps not in (None, U1_PRINT_SEQUENCE):
        issues.append(f"print_sequence is {ps!r}, expected {U1_PRINT_SEQUENCE!r} (triggers 'Print By Object')")
    elif preserve_creator_settings and ps == "by object":
        issues.append("warning: creator's print_sequence 'by object' was kept")
    if preserve_creator_settings and isinstance(fsi, list) and not all(str(x).startswith("Snapmaker") for x in fsi):
        issues.append("warning: Orca may ask to map an unknown filament preset")
    return (not [issue for issue in issues if not issue.startswith("warning:")], issues)


# slice_info.config carries an X-BBL-Client-Version stamp; the known-good U1
# file leaves it blank. A non-empty Bambu version here triggers the
# "generated by a newer version" warning.
_SLICE_VERSION_RE = re.compile(
    rb'(key="X-BBL-Client-Version"\s+value=")[^"]*(")'
)


def normalize_slice_info(xml: bytes) -> bytes:
    """Blank the X-BBL-Client-Version stamp to match a clean U1 export."""
    return _SLICE_VERSION_RE.sub(rb"\1\2", xml)
